#include "hpc/gpu/adreno/a6xx.h"

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

unsigned int hpc_gpu_adreno_a6xx_perfcounter_get_selector(
    hpc_gpu_adreno_a6xx_perfcounter_t perfcounter) {
  return perfcounter & (256u - 1u);
}
//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//
