#include "hpc/gpu/adreno/a6xx.h"

#include <stdint.h>

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

inline uint32_t adreno_a6xx_perfcounter_get_group(
    hpc_gpu_adreno_a6xx_perfcounter_t perfcounter) {
  return perfcounter >> 8u;
}

inline uint32_t adreno_a6xx_perfcounter_get_selector(
    hpc_gpu_adreno_a6xx_perfcounter_t perfcounter) {
  return perfcounter & (256u - 1u);
}

//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//
