#ifndef HPC_GPU_ADRENO_COMMON_H_
#define HPC_GPU_ADRENO_COMMON_H_

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

typedef enum hpc_gpu_adreno_common_perfcounter_e {
  // Cache and Compression Unit: busy cycles
  HPC_GPU_ADRENO_COMMON_CCU_BUSY_CYCLES = 0,
  // Cache and Compression Unit: stall cycles RB depth return
  HPC_GPU_ADRENO_COMMON_CCU_STALL_CYCLES_RB_DEPTH_RETURN = 1,
  // Cache and Compression Unit: stall cycles RB color return
  HPC_GPU_ADRENO_COMMON_CCU_STALL_CYCLES_RB_COLOR_RETURN = 2,
  // Cache and Compression Unit: starve cycles flag return
  HPC_GPU_ADRENO_COMMON_CCU_STARVE_CYCLES_FLAG_RETURN = 3,
  // Cache and Compression Unit: depth blocks
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_BLOCKS = 4,
  // Cache and Compression Unit: color blocks
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_BLOCKS = 5,
  // Cache and Compression Unit: depth block hit
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_BLOCK_HIT = 6,
  // Cache and Compression Unit: color block hit
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_BLOCK_HIT = 7,
  // Cache and Compression Unit: partial block read
  HPC_GPU_ADRENO_COMMON_CCU_PARTIAL_BLOCK_READ = 8,
  // Cache and Compression Unit: gmem read
  HPC_GPU_ADRENO_COMMON_CCU_GMEM_READ = 9,
  // Cache and Compression Unit: gmem write
  HPC_GPU_ADRENO_COMMON_CCU_GMEM_WRITE = 10,
  // Cache and Compression Unit: depth read flag0 count
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_READ_FLAG0_COUNT = 11,
  // Cache and Compression Unit: depth read flag1 count
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_READ_FLAG1_COUNT = 12,
  // Cache and Compression Unit: depth read flag2 count
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_READ_FLAG2_COUNT = 13,
  // Cache and Compression Unit: depth read flag3 count
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_READ_FLAG3_COUNT = 14,
  // Cache and Compression Unit: depth read flag4 count
  HPC_GPU_ADRENO_COMMON_CCU_DEPTH_READ_FLAG4_COUNT = 15,
  // Cache and Compression Unit: color read flag0 count
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_READ_FLAG0_COUNT = 19,
  // Cache and Compression Unit: color read flag1 count
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_READ_FLAG1_COUNT = 20,
  // Cache and Compression Unit: color read flag2 count
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_READ_FLAG2_COUNT = 21,
  // Cache and Compression Unit: color read flag3 count
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_READ_FLAG3_COUNT = 22,
  // Cache and Compression Unit: color read flag4 count
  HPC_GPU_ADRENO_COMMON_CCU_COLOR_READ_FLAG4_COUNT = 23,
  // Cache and Compression Unit: 2D RD req
  HPC_GPU_ADRENO_COMMON_CCU_2D_RD_REQ = 27,
  // Cache and Compression Unit: 2D WR req
  HPC_GPU_ADRENO_COMMON_CCU_2D_WR_REQ = 28,
  // CMP: cmpdecmp vbif latency cycles
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_LATENCY_CYCLES = 257,
  // CMP: cmpdecmp vbif latency samples
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_LATENCY_SAMPLES = 258,
  // CMP: cmpdecmp vbif read data CCU
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_READ_DATA_CCU = 259,
  // CMP: cmpdecmp vbif write data CCU
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_WRITE_DATA_CCU = 260,
  // CMP: cmpdecmp vbif read request
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_READ_REQUEST = 261,
  // CMP: cmpdecmp vbif write request
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_WRITE_REQUEST = 262,
  // CMP: cmpdecmp vbif read data
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_READ_DATA = 263,
  // CMP: cmpdecmp vbif write data
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_VBIF_WRITE_DATA = 264,
  // CMP: cmpdecmp flag fetch cycles
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_FLAG_FETCH_CYCLES = 265,
  // CMP: cmpdecmp flag fetch samples
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_FLAG_FETCH_SAMPLES = 266,
  // CMP: cmpdecmp depth write flag1 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_DEPTH_WRITE_FLAG1_COUNT = 267,
  // CMP: cmpdecmp depth write flag2 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_DEPTH_WRITE_FLAG2_COUNT = 268,
  // CMP: cmpdecmp depth write flag3 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_DEPTH_WRITE_FLAG3_COUNT = 269,
  // CMP: cmpdecmp depth write flag4 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_DEPTH_WRITE_FLAG4_COUNT = 270,
  // CMP: cmpdecmp color write flag1 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_COLOR_WRITE_FLAG1_COUNT = 274,
  // CMP: cmpdecmp color write flag2 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_COLOR_WRITE_FLAG2_COUNT = 275,
  // CMP: cmpdecmp color write flag3 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_COLOR_WRITE_FLAG3_COUNT = 276,
  // CMP: cmpdecmp color write flag4 count
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_COLOR_WRITE_FLAG4_COUNT = 277,
  // CMP: cmpdecmp 2D stall cycles vbif req
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_REQ = 281,
  // CMP: cmpdecmp 2D stall cycles vbif WR
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_WR = 282,
  // CMP: cmpdecmp 2D stall cycles vbif return
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_RETURN = 283,
  // CMP: cmpdecmp 2D RD data
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_2D_RD_DATA = 284,
  // CMP: cmpdecmp 2D WR data
  HPC_GPU_ADRENO_COMMON_CMP_CMPDECMP_2D_WR_DATA = 285,
  // Command Parser: always count
  HPC_GPU_ADRENO_COMMON_CP_ALWAYS_COUNT = 512,
  // Command Parser: busy gfx core idle
  HPC_GPU_ADRENO_COMMON_CP_BUSY_GFX_CORE_IDLE = 513,
  // Command Parser: busy cycles
  HPC_GPU_ADRENO_COMMON_CP_BUSY_CYCLES = 514,
  // Command Parser: num preemptions
  HPC_GPU_ADRENO_COMMON_CP_NUM_PREEMPTIONS = 515,
  // Command Parser: preemption reaction delay
  HPC_GPU_ADRENO_COMMON_CP_PREEMPTION_REACTION_DELAY = 516,
  // Command Parser: preemption switch out time
  HPC_GPU_ADRENO_COMMON_CP_PREEMPTION_SWITCH_OUT_TIME = 517,
  // Command Parser: preemption switch IN time
  HPC_GPU_ADRENO_COMMON_CP_PREEMPTION_SWITCH_IN_TIME = 518,
  // Command Parser: dead draws IN bin render
  HPC_GPU_ADRENO_COMMON_CP_DEAD_DRAWS_IN_BIN_RENDER = 519,
  // Command Parser: predicated draws killed
  HPC_GPU_ADRENO_COMMON_CP_PREDICATED_DRAWS_KILLED = 520,
  // Command Parser: mode switch
  HPC_GPU_ADRENO_COMMON_CP_MODE_SWITCH = 521,
  // Command Parser: zpass done
  HPC_GPU_ADRENO_COMMON_CP_ZPASS_DONE = 522,
  // Command Parser: context done
  HPC_GPU_ADRENO_COMMON_CP_CONTEXT_DONE = 523,
  // Command Parser: cache flush
  HPC_GPU_ADRENO_COMMON_CP_CACHE_FLUSH = 524,
  // Command Parser: long preemptions
  HPC_GPU_ADRENO_COMMON_CP_LONG_PREEMPTIONS = 525,
  // High Level SeQuencer: busy cycles
  HPC_GPU_ADRENO_COMMON_HLSQ_BUSY_CYCLES = 768,
  // High Level SeQuencer: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_HLSQ_STALL_CYCLES_UCHE = 769,
  // High Level SeQuencer: stall cycles SP state
  HPC_GPU_ADRENO_COMMON_HLSQ_STALL_CYCLES_SP_STATE = 770,
  // High Level SeQuencer: stall cycles SP FS stage
  HPC_GPU_ADRENO_COMMON_HLSQ_STALL_CYCLES_SP_FS_STAGE = 771,
  // High Level SeQuencer: UCHE latency cycles
  HPC_GPU_ADRENO_COMMON_HLSQ_UCHE_LATENCY_CYCLES = 772,
  // High Level SeQuencer: UCHE latency count
  HPC_GPU_ADRENO_COMMON_HLSQ_UCHE_LATENCY_COUNT = 773,
  // High Level SeQuencer: quads
  HPC_GPU_ADRENO_COMMON_HLSQ_QUADS = 776,
  // High Level SeQuencer: CS invocations
  HPC_GPU_ADRENO_COMMON_HLSQ_CS_INVOCATIONS = 777,
  // High Level SeQuencer: compute drawcalls
  HPC_GPU_ADRENO_COMMON_HLSQ_COMPUTE_DRAWCALLS = 778,
  // Low Resolution Z: busy cycles
  HPC_GPU_ADRENO_COMMON_LRZ_BUSY_CYCLES = 1024,
  // Low Resolution Z: starve cycles RAS
  HPC_GPU_ADRENO_COMMON_LRZ_STARVE_CYCLES_RAS = 1025,
  // Low Resolution Z: stall cycles RB
  HPC_GPU_ADRENO_COMMON_LRZ_STALL_CYCLES_RB = 1026,
  // Low Resolution Z: stall cycles VSC
  HPC_GPU_ADRENO_COMMON_LRZ_STALL_CYCLES_VSC = 1027,
  // Low Resolution Z: stall cycles VPC
  HPC_GPU_ADRENO_COMMON_LRZ_STALL_CYCLES_VPC = 1028,
  // Low Resolution Z: stall cycles flag prefetch
  HPC_GPU_ADRENO_COMMON_LRZ_STALL_CYCLES_FLAG_PREFETCH = 1029,
  // Low Resolution Z: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_LRZ_STALL_CYCLES_UCHE = 1030,
  // Low Resolution Z: LRZ read
  HPC_GPU_ADRENO_COMMON_LRZ_LRZ_READ = 1031,
  // Low Resolution Z: LRZ write
  HPC_GPU_ADRENO_COMMON_LRZ_LRZ_WRITE = 1032,
  // Low Resolution Z: read latency
  HPC_GPU_ADRENO_COMMON_LRZ_READ_LATENCY = 1033,
  // Low Resolution Z: merge cache updating
  HPC_GPU_ADRENO_COMMON_LRZ_MERGE_CACHE_UPDATING = 1034,
  // Low Resolution Z: prim killed BY maskgen
  HPC_GPU_ADRENO_COMMON_LRZ_PRIM_KILLED_BY_MASKGEN = 1035,
  // Low Resolution Z: prim killed BY LRZ
  HPC_GPU_ADRENO_COMMON_LRZ_PRIM_KILLED_BY_LRZ = 1036,
  // Low Resolution Z: visible prim after LRZ
  HPC_GPU_ADRENO_COMMON_LRZ_VISIBLE_PRIM_AFTER_LRZ = 1037,
  // Low Resolution Z: full 8x8 tiles
  HPC_GPU_ADRENO_COMMON_LRZ_FULL_8X8_TILES = 1038,
  // Low Resolution Z: partial 8x8 tiles
  HPC_GPU_ADRENO_COMMON_LRZ_PARTIAL_8X8_TILES = 1039,
  // Low Resolution Z: tile killed
  HPC_GPU_ADRENO_COMMON_LRZ_TILE_KILLED = 1040,
  // Low Resolution Z: total pixel
  HPC_GPU_ADRENO_COMMON_LRZ_TOTAL_PIXEL = 1041,
  // Low Resolution Z: visible pixel after LRZ
  HPC_GPU_ADRENO_COMMON_LRZ_VISIBLE_PIXEL_AFTER_LRZ = 1042,
  // PC: busy cycles
  HPC_GPU_ADRENO_COMMON_PC_BUSY_CYCLES = 1280,
  // PC: working cycles
  HPC_GPU_ADRENO_COMMON_PC_WORKING_CYCLES = 1281,
  // PC: stall cycles VFD
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_VFD = 1282,
  // PC: stall cycles TSE
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_TSE = 1283,
  // PC: stall cycles VPC
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_VPC = 1284,
  // PC: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_UCHE = 1285,
  // PC: stall cycles tess
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_TESS = 1286,
  // PC: stall cycles TSE only
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_TSE_ONLY = 1287,
  // PC: stall cycles VPC only
  HPC_GPU_ADRENO_COMMON_PC_STALL_CYCLES_VPC_ONLY = 1288,
  // PC: pass1 TF stall cycles
  HPC_GPU_ADRENO_COMMON_PC_PASS1_TF_STALL_CYCLES = 1289,
  // PC: starve cycles for index
  HPC_GPU_ADRENO_COMMON_PC_STARVE_CYCLES_FOR_INDEX = 1290,
  // PC: starve cycles for tess factor
  HPC_GPU_ADRENO_COMMON_PC_STARVE_CYCLES_FOR_TESS_FACTOR = 1291,
  // PC: starve cycles for viz stream
  HPC_GPU_ADRENO_COMMON_PC_STARVE_CYCLES_FOR_VIZ_STREAM = 1292,
  // PC: starve cycles for position
  HPC_GPU_ADRENO_COMMON_PC_STARVE_CYCLES_FOR_POSITION = 1293,
  // PC: starve cycles DI
  HPC_GPU_ADRENO_COMMON_PC_STARVE_CYCLES_DI = 1294,
  // PC: vis streams loaded
  HPC_GPU_ADRENO_COMMON_PC_VIS_STREAMS_LOADED = 1295,
  // PC: instances
  HPC_GPU_ADRENO_COMMON_PC_INSTANCES = 1296,
  // PC: VPC primitives
  HPC_GPU_ADRENO_COMMON_PC_VPC_PRIMITIVES = 1297,
  // PC: dead prim
  HPC_GPU_ADRENO_COMMON_PC_DEAD_PRIM = 1298,
  // PC: live prim
  HPC_GPU_ADRENO_COMMON_PC_LIVE_PRIM = 1299,
  // PC: vertex hits
  HPC_GPU_ADRENO_COMMON_PC_VERTEX_HITS = 1300,
  // PC: IA vertices
  HPC_GPU_ADRENO_COMMON_PC_IA_VERTICES = 1301,
  // PC: IA primitives
  HPC_GPU_ADRENO_COMMON_PC_IA_PRIMITIVES = 1302,
  // PC: GS primitives
  HPC_GPU_ADRENO_COMMON_PC_GS_PRIMITIVES = 1303,
  // PC: HS invocations
  HPC_GPU_ADRENO_COMMON_PC_HS_INVOCATIONS = 1304,
  // PC: DS invocations
  HPC_GPU_ADRENO_COMMON_PC_DS_INVOCATIONS = 1305,
  // PC: VS invocations
  HPC_GPU_ADRENO_COMMON_PC_VS_INVOCATIONS = 1306,
  // PC: GS invocations
  HPC_GPU_ADRENO_COMMON_PC_GS_INVOCATIONS = 1307,
  // PC: DS primitives
  HPC_GPU_ADRENO_COMMON_PC_DS_PRIMITIVES = 1308,
  // PC: VPC pos data transaction
  HPC_GPU_ADRENO_COMMON_PC_VPC_POS_DATA_TRANSACTION = 1309,
  // PC: 3D drawcalls
  HPC_GPU_ADRENO_COMMON_PC_3D_DRAWCALLS = 1310,
  // PC: 2D drawcalls
  HPC_GPU_ADRENO_COMMON_PC_2D_DRAWCALLS = 1311,
  // PC: non drawcall global events
  HPC_GPU_ADRENO_COMMON_PC_NON_DRAWCALL_GLOBAL_EVENTS = 1312,
  // PC: tess busy cycles
  HPC_GPU_ADRENO_COMMON_PC_TESS_BUSY_CYCLES = 1313,
  // PC: tess working cycles
  HPC_GPU_ADRENO_COMMON_PC_TESS_WORKING_CYCLES = 1314,
  // PC: tess stall cycles PC
  HPC_GPU_ADRENO_COMMON_PC_TESS_STALL_CYCLES_PC = 1315,
  // PC: tess starve cycles PC
  HPC_GPU_ADRENO_COMMON_PC_TESS_STARVE_CYCLES_PC = 1316,
  // RAS: busy cycles
  HPC_GPU_ADRENO_COMMON_RAS_BUSY_CYCLES = 1536,
  // RAS: supertile active cycles
  HPC_GPU_ADRENO_COMMON_RAS_SUPERTILE_ACTIVE_CYCLES = 1537,
  // RAS: stall cycles LRZ
  HPC_GPU_ADRENO_COMMON_RAS_STALL_CYCLES_LRZ = 1538,
  // RAS: starve cycles TSE
  HPC_GPU_ADRENO_COMMON_RAS_STARVE_CYCLES_TSE = 1539,
  // RAS: super tiles
  HPC_GPU_ADRENO_COMMON_RAS_SUPER_TILES = 1540,
  // RAS: 8x4 tiles
  HPC_GPU_ADRENO_COMMON_RAS_8X4_TILES = 1541,
  // RAS: maskgen active
  HPC_GPU_ADRENO_COMMON_RAS_MASKGEN_ACTIVE = 1542,
  // RAS: fully covered super tiles
  HPC_GPU_ADRENO_COMMON_RAS_FULLY_COVERED_SUPER_TILES = 1543,
  // RAS: fully covered 8x4 tiles
  HPC_GPU_ADRENO_COMMON_RAS_FULLY_COVERED_8X4_TILES = 1544,
  // RAS: prim killed invisilbe
  HPC_GPU_ADRENO_COMMON_RAS_PRIM_KILLED_INVISILBE = 1545,
  // RB: busy cycles
  HPC_GPU_ADRENO_COMMON_RB_BUSY_CYCLES = 1792,
  // RB: stall cycles HLSQ
  HPC_GPU_ADRENO_COMMON_RB_STALL_CYCLES_HLSQ = 1793,
  // RB: stall cycles fifo0 full
  HPC_GPU_ADRENO_COMMON_RB_STALL_CYCLES_FIFO0_FULL = 1794,
  // RB: stall cycles fifo1 full
  HPC_GPU_ADRENO_COMMON_RB_STALL_CYCLES_FIFO1_FULL = 1795,
  // RB: stall cycles fifo2 full
  HPC_GPU_ADRENO_COMMON_RB_STALL_CYCLES_FIFO2_FULL = 1796,
  // RB: starve cycles SP
  HPC_GPU_ADRENO_COMMON_RB_STARVE_CYCLES_SP = 1797,
  // RB: starve cycles LRZ tile
  HPC_GPU_ADRENO_COMMON_RB_STARVE_CYCLES_LRZ_TILE = 1798,
  // RB: starve cycles CCU
  HPC_GPU_ADRENO_COMMON_RB_STARVE_CYCLES_CCU = 1799,
  // RB: starve cycles Z plane
  HPC_GPU_ADRENO_COMMON_RB_STARVE_CYCLES_Z_PLANE = 1800,
  // RB: starve cycles bary plane
  HPC_GPU_ADRENO_COMMON_RB_STARVE_CYCLES_BARY_PLANE = 1801,
  // RB: Z workload
  HPC_GPU_ADRENO_COMMON_RB_Z_WORKLOAD = 1802,
  // RB: HLSQ active
  HPC_GPU_ADRENO_COMMON_RB_HLSQ_ACTIVE = 1803,
  // RB: Z read
  HPC_GPU_ADRENO_COMMON_RB_Z_READ = 1804,
  // RB: Z write
  HPC_GPU_ADRENO_COMMON_RB_Z_WRITE = 1805,
  // RB: C read
  HPC_GPU_ADRENO_COMMON_RB_C_READ = 1806,
  // RB: C write
  HPC_GPU_ADRENO_COMMON_RB_C_WRITE = 1807,
  // RB: total pass
  HPC_GPU_ADRENO_COMMON_RB_TOTAL_PASS = 1808,
  // RB: Z pass
  HPC_GPU_ADRENO_COMMON_RB_Z_PASS = 1809,
  // RB: Z fail
  HPC_GPU_ADRENO_COMMON_RB_Z_FAIL = 1810,
  // RB: S fail
  HPC_GPU_ADRENO_COMMON_RB_S_FAIL = 1811,
  // RB: blended fxp components
  HPC_GPU_ADRENO_COMMON_RB_BLENDED_FXP_COMPONENTS = 1812,
  // RB: blended fp16 components
  HPC_GPU_ADRENO_COMMON_RB_BLENDED_FP16_COMPONENTS = 1813,
  // RB: 2D alive cycles
  HPC_GPU_ADRENO_COMMON_RB_2D_ALIVE_CYCLES = 1815,
  // RB: 2D stall cycles a2d
  HPC_GPU_ADRENO_COMMON_RB_2D_STALL_CYCLES_A2D = 1816,
  // RB: 2D starve cycles src
  HPC_GPU_ADRENO_COMMON_RB_2D_STARVE_CYCLES_SRC = 1817,
  // RB: 2D starve cycles SP
  HPC_GPU_ADRENO_COMMON_RB_2D_STARVE_CYCLES_SP = 1818,
  // RB: 2D starve cycles dst
  HPC_GPU_ADRENO_COMMON_RB_2D_STARVE_CYCLES_DST = 1819,
  // RB: 2D valid pixels
  HPC_GPU_ADRENO_COMMON_RB_2D_VALID_PIXELS = 1820,
  // RB: stall cycles CCU
  HPC_GPU_ADRENO_COMMON_RB_STALL_CYCLES_CCU = 1836,
  // RBBM: always count
  HPC_GPU_ADRENO_COMMON_RBBM_ALWAYS_COUNT = 2048,
  // RBBM: always ON
  HPC_GPU_ADRENO_COMMON_RBBM_ALWAYS_ON = 2049,
  // RBBM: TSE busy
  HPC_GPU_ADRENO_COMMON_RBBM_TSE_BUSY = 2050,
  // RBBM: RAS busy
  HPC_GPU_ADRENO_COMMON_RBBM_RAS_BUSY = 2051,
  // RBBM: PC dcall busy
  HPC_GPU_ADRENO_COMMON_RBBM_PC_DCALL_BUSY = 2052,
  // RBBM: PC vsd busy
  HPC_GPU_ADRENO_COMMON_RBBM_PC_VSD_BUSY = 2053,
  // RBBM: status masked
  HPC_GPU_ADRENO_COMMON_RBBM_STATUS_MASKED = 2054,
  // RBBM: com busy
  HPC_GPU_ADRENO_COMMON_RBBM_COM_BUSY = 2055,
  // RBBM: dcom busy
  HPC_GPU_ADRENO_COMMON_RBBM_DCOM_BUSY = 2056,
  // RBBM: vbif busy
  HPC_GPU_ADRENO_COMMON_RBBM_VBIF_BUSY = 2057,
  // RBBM: VSC busy
  HPC_GPU_ADRENO_COMMON_RBBM_VSC_BUSY = 2058,
  // RBBM: tess busy
  HPC_GPU_ADRENO_COMMON_RBBM_TESS_BUSY = 2059,
  // RBBM: UCHE busy
  HPC_GPU_ADRENO_COMMON_RBBM_UCHE_BUSY = 2060,
  // RBBM: HLSQ busy
  HPC_GPU_ADRENO_COMMON_RBBM_HLSQ_BUSY = 2061,
  // Shader/Streaming Processor: busy cycles
  HPC_GPU_ADRENO_COMMON_SP_BUSY_CYCLES = 2304,
  // Shader/Streaming Processor: ALU working cycles
  HPC_GPU_ADRENO_COMMON_SP_ALU_WORKING_CYCLES = 2305,
  // Shader/Streaming Processor: EFU working cycles
  HPC_GPU_ADRENO_COMMON_SP_EFU_WORKING_CYCLES = 2306,
  // Shader/Streaming Processor: stall cycles VPC
  HPC_GPU_ADRENO_COMMON_SP_STALL_CYCLES_VPC = 2307,
  // Shader/Streaming Processor: stall cycles TP
  HPC_GPU_ADRENO_COMMON_SP_STALL_CYCLES_TP = 2308,
  // Shader/Streaming Processor: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_SP_STALL_CYCLES_UCHE = 2309,
  // Shader/Streaming Processor: stall cycles RB
  HPC_GPU_ADRENO_COMMON_SP_STALL_CYCLES_RB = 2310,
  // Shader/Streaming Processor: wave contexts
  HPC_GPU_ADRENO_COMMON_SP_WAVE_CONTEXTS = 2312,
  // Shader/Streaming Processor: wave context cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_CONTEXT_CYCLES = 2313,
  // Shader/Streaming Processor: FS stage wave cycles
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_WAVE_CYCLES = 2314,
  // Shader/Streaming Processor: FS stage wave samples
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_WAVE_SAMPLES = 2315,
  // Shader/Streaming Processor: VS stage wave cycles
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_WAVE_CYCLES = 2316,
  // Shader/Streaming Processor: VS stage wave samples
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_WAVE_SAMPLES = 2317,
  // Shader/Streaming Processor: FS stage duration cycles
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_DURATION_CYCLES = 2318,
  // Shader/Streaming Processor: VS stage duration cycles
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_DURATION_CYCLES = 2319,
  // Shader/Streaming Processor: wave ctrl cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_CTRL_CYCLES = 2320,
  // Shader/Streaming Processor: wave load cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_LOAD_CYCLES = 2321,
  // Shader/Streaming Processor: wave emit cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_EMIT_CYCLES = 2322,
  // Shader/Streaming Processor: wave nop cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_NOP_CYCLES = 2323,
  // Shader/Streaming Processor: wave wait cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_WAIT_CYCLES = 2324,
  // Shader/Streaming Processor: wave fetch cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_FETCH_CYCLES = 2325,
  // Shader/Streaming Processor: wave idle cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_IDLE_CYCLES = 2326,
  // Shader/Streaming Processor: wave end cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_END_CYCLES = 2327,
  // Shader/Streaming Processor: wave long sync cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_LONG_SYNC_CYCLES = 2328,
  // Shader/Streaming Processor: wave short sync cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_SHORT_SYNC_CYCLES = 2329,
  // Shader/Streaming Processor: wave join cycles
  HPC_GPU_ADRENO_COMMON_SP_WAVE_JOIN_CYCLES = 2330,
  // Shader/Streaming Processor: LM load instructions
  HPC_GPU_ADRENO_COMMON_SP_LM_LOAD_INSTRUCTIONS = 2331,
  // Shader/Streaming Processor: LM store instructions
  HPC_GPU_ADRENO_COMMON_SP_LM_STORE_INSTRUCTIONS = 2332,
  // Shader/Streaming Processor: LM atomics
  HPC_GPU_ADRENO_COMMON_SP_LM_ATOMICS = 2333,
  // Shader/Streaming Processor: GM load instructions
  HPC_GPU_ADRENO_COMMON_SP_GM_LOAD_INSTRUCTIONS = 2334,
  // Shader/Streaming Processor: GM store instructions
  HPC_GPU_ADRENO_COMMON_SP_GM_STORE_INSTRUCTIONS = 2335,
  // Shader/Streaming Processor: GM atomics
  HPC_GPU_ADRENO_COMMON_SP_GM_ATOMICS = 2336,
  // Shader/Streaming Processor: VS stage tex instructions
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_TEX_INSTRUCTIONS = 2337,
  // Shader/Streaming Processor: VS stage EFU instructions
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_EFU_INSTRUCTIONS = 2338,
  // Shader/Streaming Processor: VS stage full ALU instructions
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_FULL_ALU_INSTRUCTIONS = 2339,
  // Shader/Streaming Processor: VS stage half ALU instructions
  HPC_GPU_ADRENO_COMMON_SP_VS_STAGE_HALF_ALU_INSTRUCTIONS = 2340,
  // Shader/Streaming Processor: FS stage tex instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_TEX_INSTRUCTIONS = 2341,
  // Shader/Streaming Processor: FS stage cflow instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_CFLOW_INSTRUCTIONS = 2342,
  // Shader/Streaming Processor: FS stage EFU instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_EFU_INSTRUCTIONS = 2343,
  // Shader/Streaming Processor: FS stage full ALU instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_FULL_ALU_INSTRUCTIONS = 2344,
  // Shader/Streaming Processor: FS stage half ALU instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_HALF_ALU_INSTRUCTIONS = 2345,
  // Shader/Streaming Processor: FS stage bary instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_STAGE_BARY_INSTRUCTIONS = 2346,
  // Shader/Streaming Processor: VS instructions
  HPC_GPU_ADRENO_COMMON_SP_VS_INSTRUCTIONS = 2347,
  // Shader/Streaming Processor: FS instructions
  HPC_GPU_ADRENO_COMMON_SP_FS_INSTRUCTIONS = 2348,
  // Shader/Streaming Processor: addr lock count
  HPC_GPU_ADRENO_COMMON_SP_ADDR_LOCK_COUNT = 2349,
  // Shader/Streaming Processor: UCHE read trans
  HPC_GPU_ADRENO_COMMON_SP_UCHE_READ_TRANS = 2350,
  // Shader/Streaming Processor: UCHE write trans
  HPC_GPU_ADRENO_COMMON_SP_UCHE_WRITE_TRANS = 2351,
  // Shader/Streaming Processor: export VPC trans
  HPC_GPU_ADRENO_COMMON_SP_EXPORT_VPC_TRANS = 2352,
  // Shader/Streaming Processor: export RB trans
  HPC_GPU_ADRENO_COMMON_SP_EXPORT_RB_TRANS = 2353,
  // Shader/Streaming Processor: pixels killed
  HPC_GPU_ADRENO_COMMON_SP_PIXELS_KILLED = 2354,
  // Shader/Streaming Processor: icl1 requests
  HPC_GPU_ADRENO_COMMON_SP_ICL1_REQUESTS = 2355,
  // Shader/Streaming Processor: icl1 misses
  HPC_GPU_ADRENO_COMMON_SP_ICL1_MISSES = 2356,
  // Shader/Streaming Processor: HS instructions
  HPC_GPU_ADRENO_COMMON_SP_HS_INSTRUCTIONS = 2357,
  // Shader/Streaming Processor: DS instructions
  HPC_GPU_ADRENO_COMMON_SP_DS_INSTRUCTIONS = 2358,
  // Shader/Streaming Processor: GS instructions
  HPC_GPU_ADRENO_COMMON_SP_GS_INSTRUCTIONS = 2359,
  // Shader/Streaming Processor: CS instructions
  HPC_GPU_ADRENO_COMMON_SP_CS_INSTRUCTIONS = 2360,
  // Shader/Streaming Processor: GPR read
  HPC_GPU_ADRENO_COMMON_SP_GPR_READ = 2361,
  // Shader/Streaming Processor: GPR write
  HPC_GPU_ADRENO_COMMON_SP_GPR_WRITE = 2362,
  // Shader/Streaming Processor: LM bank conflicts
  HPC_GPU_ADRENO_COMMON_SP_LM_BANK_CONFLICTS = 2365,
  // Texture Processor: busy cycles
  HPC_GPU_ADRENO_COMMON_TP_BUSY_CYCLES = 2560,
  // Texture Processor: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_TP_STALL_CYCLES_UCHE = 2561,
  // Texture Processor: latency cycles
  HPC_GPU_ADRENO_COMMON_TP_LATENCY_CYCLES = 2562,
  // Texture Processor: latency trans
  HPC_GPU_ADRENO_COMMON_TP_LATENCY_TRANS = 2563,
  // Texture Processor: flag cache request samples
  HPC_GPU_ADRENO_COMMON_TP_FLAG_CACHE_REQUEST_SAMPLES = 2564,
  // Texture Processor: flag cache request latency
  HPC_GPU_ADRENO_COMMON_TP_FLAG_CACHE_REQUEST_LATENCY = 2565,
  // Texture Processor: L1 cacheline requests
  HPC_GPU_ADRENO_COMMON_TP_L1_CACHELINE_REQUESTS = 2566,
  // Texture Processor: L1 cacheline misses
  HPC_GPU_ADRENO_COMMON_TP_L1_CACHELINE_MISSES = 2567,
  // Texture Processor: SP TP trans
  HPC_GPU_ADRENO_COMMON_TP_SP_TP_TRANS = 2568,
  // Texture Processor: TP SP trans
  HPC_GPU_ADRENO_COMMON_TP_TP_SP_TRANS = 2569,
  // Texture Processor: output pixels
  HPC_GPU_ADRENO_COMMON_TP_OUTPUT_PIXELS = 2570,
  // Texture Processor: filter workload 16bit
  HPC_GPU_ADRENO_COMMON_TP_FILTER_WORKLOAD_16BIT = 2571,
  // Texture Processor: filter workload 32bit
  HPC_GPU_ADRENO_COMMON_TP_FILTER_WORKLOAD_32BIT = 2572,
  // Texture Processor: quads received
  HPC_GPU_ADRENO_COMMON_TP_QUADS_RECEIVED = 2573,
  // Texture Processor: quads offset
  HPC_GPU_ADRENO_COMMON_TP_QUADS_OFFSET = 2574,
  // Texture Processor: quads shadow
  HPC_GPU_ADRENO_COMMON_TP_QUADS_SHADOW = 2575,
  // Texture Processor: quads array
  HPC_GPU_ADRENO_COMMON_TP_QUADS_ARRAY = 2576,
  // Texture Processor: quads gradient
  HPC_GPU_ADRENO_COMMON_TP_QUADS_GRADIENT = 2577,
  // Texture Processor: quads 1D
  HPC_GPU_ADRENO_COMMON_TP_QUADS_1D = 2578,
  // Texture Processor: quads 2D
  HPC_GPU_ADRENO_COMMON_TP_QUADS_2D = 2579,
  // Texture Processor: quads buffer
  HPC_GPU_ADRENO_COMMON_TP_QUADS_BUFFER = 2580,
  // Texture Processor: quads 3D
  HPC_GPU_ADRENO_COMMON_TP_QUADS_3D = 2581,
  // Texture Processor: quads cube
  HPC_GPU_ADRENO_COMMON_TP_QUADS_CUBE = 2582,
  // Texture Processor: divergent quads received
  HPC_GPU_ADRENO_COMMON_TP_DIVERGENT_QUADS_RECEIVED = 2583,
  // Texture Processor: prt non resident events
  HPC_GPU_ADRENO_COMMON_TP_PRT_NON_RESIDENT_EVENTS = 2584,
  // Texture Processor: output pixels point
  HPC_GPU_ADRENO_COMMON_TP_OUTPUT_PIXELS_POINT = 2585,
  // Texture Processor: output pixels bilinear
  HPC_GPU_ADRENO_COMMON_TP_OUTPUT_PIXELS_BILINEAR = 2586,
  // Texture Processor: output pixels mip
  HPC_GPU_ADRENO_COMMON_TP_OUTPUT_PIXELS_MIP = 2587,
  // Texture Processor: output pixels aniso
  HPC_GPU_ADRENO_COMMON_TP_OUTPUT_PIXELS_ANISO = 2588,
  // Texture Processor: output pixels zero lod
  HPC_GPU_ADRENO_COMMON_TP_OUTPUT_PIXELS_ZERO_LOD = 2589,
  // Texture Processor: flag cache requests
  HPC_GPU_ADRENO_COMMON_TP_FLAG_CACHE_REQUESTS = 2590,
  // Texture Processor: flag cache misses
  HPC_GPU_ADRENO_COMMON_TP_FLAG_CACHE_MISSES = 2591,
  // Texture Processor: L1 5 L2 requests
  HPC_GPU_ADRENO_COMMON_TP_L1_5_L2_REQUESTS = 2592,
  // Texture Processor: 2D output pixels
  HPC_GPU_ADRENO_COMMON_TP_2D_OUTPUT_PIXELS = 2593,
  // Texture Processor: 2D output pixels point
  HPC_GPU_ADRENO_COMMON_TP_2D_OUTPUT_PIXELS_POINT = 2594,
  // Texture Processor: 2D output pixels bilinear
  HPC_GPU_ADRENO_COMMON_TP_2D_OUTPUT_PIXELS_BILINEAR = 2595,
  // Texture Processor: 2D filter workload 16bit
  HPC_GPU_ADRENO_COMMON_TP_2D_FILTER_WORKLOAD_16BIT = 2596,
  // Texture Processor: 2D filter workload 32bit
  HPC_GPU_ADRENO_COMMON_TP_2D_FILTER_WORKLOAD_32BIT = 2597,
  // Triangle Setup Engine: busy cycles
  HPC_GPU_ADRENO_COMMON_TSE_BUSY_CYCLES = 2816,
  // Triangle Setup Engine: clipping cycles
  HPC_GPU_ADRENO_COMMON_TSE_CLIPPING_CYCLES = 2817,
  // Triangle Setup Engine: stall cycles RAS
  HPC_GPU_ADRENO_COMMON_TSE_STALL_CYCLES_RAS = 2818,
  // Triangle Setup Engine: stall cycles LRZ baryplane
  HPC_GPU_ADRENO_COMMON_TSE_STALL_CYCLES_LRZ_BARYPLANE = 2819,
  // Triangle Setup Engine: stall cycles LRZ zplane
  HPC_GPU_ADRENO_COMMON_TSE_STALL_CYCLES_LRZ_ZPLANE = 2820,
  // Triangle Setup Engine: starve cycles PC
  HPC_GPU_ADRENO_COMMON_TSE_STARVE_CYCLES_PC = 2821,
  // Triangle Setup Engine: input prim
  HPC_GPU_ADRENO_COMMON_TSE_INPUT_PRIM = 2822,
  // Triangle Setup Engine: input null prim
  HPC_GPU_ADRENO_COMMON_TSE_INPUT_NULL_PRIM = 2823,
  // Triangle Setup Engine: trival rej prim
  HPC_GPU_ADRENO_COMMON_TSE_TRIVAL_REJ_PRIM = 2824,
  // Triangle Setup Engine: clipped prim
  HPC_GPU_ADRENO_COMMON_TSE_CLIPPED_PRIM = 2825,
  // Triangle Setup Engine: zero area prim
  HPC_GPU_ADRENO_COMMON_TSE_ZERO_AREA_PRIM = 2826,
  // Triangle Setup Engine: faceness culled prim
  HPC_GPU_ADRENO_COMMON_TSE_FACENESS_CULLED_PRIM = 2827,
  // Triangle Setup Engine: zero pixel prim
  HPC_GPU_ADRENO_COMMON_TSE_ZERO_PIXEL_PRIM = 2828,
  // Triangle Setup Engine: output null prim
  HPC_GPU_ADRENO_COMMON_TSE_OUTPUT_NULL_PRIM = 2829,
  // Triangle Setup Engine: output visible prim
  HPC_GPU_ADRENO_COMMON_TSE_OUTPUT_VISIBLE_PRIM = 2830,
  // Triangle Setup Engine: cinvocation
  HPC_GPU_ADRENO_COMMON_TSE_CINVOCATION = 2831,
  // Triangle Setup Engine: cprimitives
  HPC_GPU_ADRENO_COMMON_TSE_CPRIMITIVES = 2832,
  // Triangle Setup Engine: 2D input prim
  HPC_GPU_ADRENO_COMMON_TSE_2D_INPUT_PRIM = 2833,
  // Unified L2 Cache: busy cycles
  HPC_GPU_ADRENO_COMMON_UCHE_BUSY_CYCLES = 3072,
  // Unified L2 Cache: vbif latency cycles
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_LATENCY_CYCLES = 3074,
  // Unified L2 Cache: vbif latency samples
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_LATENCY_SAMPLES = 3075,
  // Unified L2 Cache: vbif read beats TP
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_TP = 3076,
  // Unified L2 Cache: vbif read beats VFD
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_VFD = 3077,
  // Unified L2 Cache: vbif read beats HLSQ
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_HLSQ = 3078,
  // Unified L2 Cache: vbif read beats LRZ
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_LRZ = 3079,
  // Unified L2 Cache: vbif read beats SP
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_SP = 3080,
  // Unified L2 Cache: read requests TP
  HPC_GPU_ADRENO_COMMON_UCHE_READ_REQUESTS_TP = 3081,
  // Unified L2 Cache: read requests VFD
  HPC_GPU_ADRENO_COMMON_UCHE_READ_REQUESTS_VFD = 3082,
  // Unified L2 Cache: read requests HLSQ
  HPC_GPU_ADRENO_COMMON_UCHE_READ_REQUESTS_HLSQ = 3083,
  // Unified L2 Cache: read requests LRZ
  HPC_GPU_ADRENO_COMMON_UCHE_READ_REQUESTS_LRZ = 3084,
  // Unified L2 Cache: read requests SP
  HPC_GPU_ADRENO_COMMON_UCHE_READ_REQUESTS_SP = 3085,
  // Unified L2 Cache: write requests LRZ
  HPC_GPU_ADRENO_COMMON_UCHE_WRITE_REQUESTS_LRZ = 3086,
  // Unified L2 Cache: write requests SP
  HPC_GPU_ADRENO_COMMON_UCHE_WRITE_REQUESTS_SP = 3087,
  // Unified L2 Cache: write requests VPC
  HPC_GPU_ADRENO_COMMON_UCHE_WRITE_REQUESTS_VPC = 3088,
  // Unified L2 Cache: write requests VSC
  HPC_GPU_ADRENO_COMMON_UCHE_WRITE_REQUESTS_VSC = 3089,
  // Unified L2 Cache: evicts
  HPC_GPU_ADRENO_COMMON_UCHE_EVICTS = 3090,
  // Unified L2 Cache: bank req0
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ0 = 3091,
  // Unified L2 Cache: bank req1
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ1 = 3092,
  // Unified L2 Cache: bank req2
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ2 = 3093,
  // Unified L2 Cache: bank req3
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ3 = 3094,
  // Unified L2 Cache: bank req4
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ4 = 3095,
  // Unified L2 Cache: bank req5
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ5 = 3096,
  // Unified L2 Cache: bank req6
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ6 = 3097,
  // Unified L2 Cache: bank req7
  HPC_GPU_ADRENO_COMMON_UCHE_BANK_REQ7 = 3098,
  // Unified L2 Cache: vbif read beats ch0
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_CH0 = 3099,
  // Unified L2 Cache: vbif read beats ch1
  HPC_GPU_ADRENO_COMMON_UCHE_VBIF_READ_BEATS_CH1 = 3100,
  // Unified L2 Cache: gmem read beats
  HPC_GPU_ADRENO_COMMON_UCHE_GMEM_READ_BEATS = 3101,
  // VFD: busy cycles
  HPC_GPU_ADRENO_COMMON_VFD_BUSY_CYCLES = 3328,
  // VFD: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_VFD_STALL_CYCLES_UCHE = 3329,
  // VFD: stall cycles VPC alloc
  HPC_GPU_ADRENO_COMMON_VFD_STALL_CYCLES_VPC_ALLOC = 3330,
  // VFD: stall cycles SP info
  HPC_GPU_ADRENO_COMMON_VFD_STALL_CYCLES_SP_INFO = 3331,
  // VFD: stall cycles SP attr
  HPC_GPU_ADRENO_COMMON_VFD_STALL_CYCLES_SP_ATTR = 3332,
  // VFD: starve cycles UCHE
  HPC_GPU_ADRENO_COMMON_VFD_STARVE_CYCLES_UCHE = 3333,
  // VFD: rbuffer full
  HPC_GPU_ADRENO_COMMON_VFD_RBUFFER_FULL = 3334,
  // VFD: attr info fifo full
  HPC_GPU_ADRENO_COMMON_VFD_ATTR_INFO_FIFO_FULL = 3335,
  // VFD: decoded attribute bytes
  HPC_GPU_ADRENO_COMMON_VFD_DECODED_ATTRIBUTE_BYTES = 3336,
  // VFD: num attributes
  HPC_GPU_ADRENO_COMMON_VFD_NUM_ATTRIBUTES = 3337,
  // VFD: upper shader fibers
  HPC_GPU_ADRENO_COMMON_VFD_UPPER_SHADER_FIBERS = 3338,
  // VFD: lower shader fibers
  HPC_GPU_ADRENO_COMMON_VFD_LOWER_SHADER_FIBERS = 3339,
  // VFD: mode 0 fibers
  HPC_GPU_ADRENO_COMMON_VFD_MODE_0_FIBERS = 3340,
  // VFD: mode 1 fibers
  HPC_GPU_ADRENO_COMMON_VFD_MODE_1_FIBERS = 3341,
  // VFD: mode 2 fibers
  HPC_GPU_ADRENO_COMMON_VFD_MODE_2_FIBERS = 3342,
  // VFD: mode 3 fibers
  HPC_GPU_ADRENO_COMMON_VFD_MODE_3_FIBERS = 3343,
  // VFD: mode 4 fibers
  HPC_GPU_ADRENO_COMMON_VFD_MODE_4_FIBERS = 3344,
  // VFD: total vertices
  HPC_GPU_ADRENO_COMMON_VFD_TOTAL_VERTICES = 3345,
  // VFD: vfdp stall cycles VFD
  HPC_GPU_ADRENO_COMMON_VFD_VFDP_STALL_CYCLES_VFD = 3346,
  // VFD: vfdp stall cycles VFD index
  HPC_GPU_ADRENO_COMMON_VFD_VFDP_STALL_CYCLES_VFD_INDEX = 3347,
  // VFD: vfdp stall cycles VFD prog
  HPC_GPU_ADRENO_COMMON_VFD_VFDP_STALL_CYCLES_VFD_PROG = 3348,
  // VFD: vfdp starve cycles PC
  HPC_GPU_ADRENO_COMMON_VFD_VFDP_STARVE_CYCLES_PC = 3349,
  // VPC: busy cycles
  HPC_GPU_ADRENO_COMMON_VPC_BUSY_CYCLES = 3584,
  // VPC: working cycles
  HPC_GPU_ADRENO_COMMON_VPC_WORKING_CYCLES = 3585,
  // VPC: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_VPC_STALL_CYCLES_UCHE = 3586,
  // VPC: stall cycles VFD wack
  HPC_GPU_ADRENO_COMMON_VPC_STALL_CYCLES_VFD_WACK = 3587,
  // VPC: stall cycles HLSQ prim alloc
  HPC_GPU_ADRENO_COMMON_VPC_STALL_CYCLES_HLSQ_PRIM_ALLOC = 3588,
  // VPC: stall cycles PC
  HPC_GPU_ADRENO_COMMON_VPC_STALL_CYCLES_PC = 3589,
  // VPC: stall cycles SP LM
  HPC_GPU_ADRENO_COMMON_VPC_STALL_CYCLES_SP_LM = 3590,
  // VPC: starve cycles SP
  HPC_GPU_ADRENO_COMMON_VPC_STARVE_CYCLES_SP = 3591,
  // VPC: starve cycles LRZ
  HPC_GPU_ADRENO_COMMON_VPC_STARVE_CYCLES_LRZ = 3592,
  // VPC: PC primitives
  HPC_GPU_ADRENO_COMMON_VPC_PC_PRIMITIVES = 3593,
  // VPC: SP components
  HPC_GPU_ADRENO_COMMON_VPC_SP_COMPONENTS = 3594,
  // VSC: busy cycles
  HPC_GPU_ADRENO_COMMON_VSC_BUSY_CYCLES = 3840,
  // VSC: working cycles
  HPC_GPU_ADRENO_COMMON_VSC_WORKING_CYCLES = 3841,
  // VSC: stall cycles UCHE
  HPC_GPU_ADRENO_COMMON_VSC_STALL_CYCLES_UCHE = 3842,
  // VSC: eot num
  HPC_GPU_ADRENO_COMMON_VSC_EOT_NUM = 3843,
} hpc_gpu_adreno_common_perfcounter_t;

//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//

#endif  // HPC_GPU_ADRENO_COMMON_H_
