#ifndef HPC_GPU_MALI_COMMON_H_
#define HPC_GPU_MALI_COMMON_H_

#include <stdint.h>

#include "hpc/gpu/base_utilities.h"

// Forward declaration of counter enums.
typedef enum hpc_gpu_mali_common_counter_e hpc_gpu_mali_common_counter_t;

/// The context for sampling Mali GPU counters.
typedef struct hpc_gpu_mali_context_t hpc_gpu_mali_context_t;

/// Creates a context for sampling counters available to all known Mali GPUs.
///
/// Creating the context means talking with the Mali GPU kernel driver and
/// allocating resources for sampling the given counters.
///
/// @param[in]  num_counters The number of counters to sample later.
/// @param[in]  counters     The pointer to the list of counters to sample
///                          later.
/// @param[in]  allocator    The allocator used to allocate host memory for
///                          sampling counters later.
/// @param[out] out_context  The pointer to the object receiving the resultant
///                          context.
int hpc_gpu_mali_common_create_context(
    uint32_t num_counters, hpc_gpu_mali_common_counter_t *counters,
    const hpc_gpu_host_allocation_callbacks_t *allocator,
    hpc_gpu_mali_context_t **out_context);

/// Destroys the context for common Mali GPU counters.
///
/// @param[in] context   The counter sampling context.
/// @param[in] allocator The allocator used to free allocated host memory.
int hpc_gpu_mali_common_destroy_context(
    hpc_gpu_mali_context_t *context,
    const hpc_gpu_host_allocation_callbacks_t *allocator);

/// Starts sampling the common Mali GPU counters specified when creating
/// the context.
///
/// This zeros the registered counters in preparation for continously sampling.
///
/// @param[in] context The counter sampling context.
int hpc_gpu_mali_common_start_counters(const hpc_gpu_mali_context_t *context);

/// Stops sampling the common Mali GPU counters specified when creating
/// the context.
///
/// @param[in] context The counter sampling context.
int hpc_gpu_mali_common_stop_counters(const hpc_gpu_mali_context_t *context);

/// Samples the common Mali GPU counters specified when creating
/// the context.
///
/// @param[in]  context The counter sampling context.
/// @param[out] values  The pointer to the memory for receiving newly sampled
///                     values. Its element count should be greater than or
///                     equal to the number of counters specified when
///                     creating the `context`.
int hpc_gpu_mali_common_query_counters(const hpc_gpu_mali_context_t *context,
                                       uint64_t *values);

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

/// Common Mali GPU counters.
typedef enum hpc_gpu_mali_common_counter_e {
  HPC_GPU_MALI_COMMON_JOB_MANAGER_MESSAGES_SENT = 4u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_MESSAGES_RECEIVED = 5u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_GPU_ACTIVE = 6u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_IRQ_ACTIVE = 7u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_JOBS = 8u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_TASKS = 9u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_ACTIVE = 10u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_WAIT_READ = 12u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_WAIT_ISSUE = 13u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_WAIT_DEPEND = 14u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS0_WAIT_FINISH = 15u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_JOBS = 16u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_TASKS = 17u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_ACTIVE = 18u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_WAIT_READ = 20u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_WAIT_ISSUE = 21u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_WAIT_DEPEND = 22u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS1_WAIT_FINISH = 23u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_JOBS = 24u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_TASKS = 25u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_ACTIVE = 26u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_WAIT_READ = 28u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_WAIT_ISSUE = 29u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_WAIT_DEPEND = 30u,
  HPC_GPU_MALI_COMMON_JOB_MANAGER_JS2_WAIT_FINISH = 31u,
  HPC_GPU_MALI_COMMON_TILER_JOBS_PROCESSED = 259u,
  HPC_GPU_MALI_COMMON_TILER_TRIANGLES = 260u,
  HPC_GPU_MALI_COMMON_TILER_POINTS = 263u,
  HPC_GPU_MALI_COMMON_TILER_LINES = 264u,
  HPC_GPU_MALI_COMMON_TILER_FRONT_FACING = 265u,
  HPC_GPU_MALI_COMMON_TILER_BACK_FACING = 266u,
  HPC_GPU_MALI_COMMON_TILER_PRIM_VISIBLE = 267u,
  HPC_GPU_MALI_COMMON_TILER_PRIM_CULLED = 268u,
  HPC_GPU_MALI_COMMON_TILER_PRIM_CLIPPED = 269u,
  HPC_GPU_MALI_COMMON_SHADER_CORE_FRAG_ACTIVE = 516u,
  HPC_GPU_MALI_COMMON_SHADER_CORE_FRAG_QUADS_RAST = 526u,
  HPC_GPU_MALI_COMMON_SHADER_CORE_FRAG_QUADS_EZS_TEST = 527u,
  HPC_GPU_MALI_COMMON_SHADER_CORE_FRAG_TRANS_ELIM = 533u,
  HPC_GPU_MALI_COMMON_SHADER_CORE_COMPUTE_ACTIVE = 534u,
  HPC_GPU_MALI_COMMON_SHADER_CORE_COMPUTE_TASKS = 535u,
  HPC_GPU_MALI_COMMON_MEMORY_MMU_REQUESTS = 777u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_EXT_WRITE_BEATS = 798u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_EXT_READ_BEATS = 799u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_ANY_LOOKUP = 800u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_READ_LOOKUP = 801u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_WRITE_LOOKUP = 807u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_EXT_READ = 816u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_EXT_WRITE = 818u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_EXT_AR_STALL = 822u,
  HPC_GPU_MALI_COMMON_MEMORY_L2_EXT_W_STALL = 826u
} hpc_gpu_mali_common_counter_t;

//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//

#endif  // HPC_GPU_MALI_COMMON_H_
