#include "hpc/gpu/mali/context.h"

#include <stdint.h>
#include <string.h>
#include <unistd.h>  // For close

#include "hpc/gpu/base_utilities.h"
#include "hpc/gpu/mali/driver_ioctl.h"

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

hpc_gpu_mali_counter_layout_t hpc_gpu_mali_get_counter_layout(uint16_t gpu_id) {
  if ((gpu_id & 0xf00fu) == 0x9005u) return HPC_GPU_MALI_COUNTER_LAYOUT_TBOX;
  if ((gpu_id & 0xf00fu) == 0x9002u) return HPC_GPU_MALI_COUNTER_LAYOUT_TBOX;
  if ((gpu_id & 0xf00fu) == 0x9004u) return HPC_GPU_MALI_COUNTER_LAYOUT_TOTX;
  if ((gpu_id & 0xf00fu) == 0x9000u) return HPC_GPU_MALI_COUNTER_LAYOUT_TTRX;
  if ((gpu_id & 0xf00fu) == 0x9003u) return HPC_GPU_MALI_COUNTER_LAYOUT_TNAX;
  if ((gpu_id & 0xf00fu) == 0x9001u) return HPC_GPU_MALI_COUNTER_LAYOUT_TNAX;
  if ((gpu_id & 0xf00fu) == 0x7001u) return HPC_GPU_MALI_COUNTER_LAYOUT_TNOX;
  if ((gpu_id & 0xf00fu) == 0x7002u) return HPC_GPU_MALI_COUNTER_LAYOUT_TGOX;
  if ((gpu_id & 0xf00fu) == 0x7000u) return HPC_GPU_MALI_COUNTER_LAYOUT_TSIX;
  if ((gpu_id & 0xf00fu) == 0x7003u) return HPC_GPU_MALI_COUNTER_LAYOUT_TDVX;
  if ((gpu_id & 0xf00fu) == 0x6001u) return HPC_GPU_MALI_COUNTER_LAYOUT_THEX;
  if ((gpu_id & 0xf00fu) == 0x6000u) return HPC_GPU_MALI_COUNTER_LAYOUT_TMIX;
  if ((gpu_id & 0xffffu) == 0x0880u) return HPC_GPU_MALI_COUNTER_LAYOUT_T88X;
  if ((gpu_id & 0xffffu) == 0x0860u) return HPC_GPU_MALI_COUNTER_LAYOUT_T86X;
  if ((gpu_id & 0xffffu) == 0x0830u) return HPC_GPU_MALI_COUNTER_LAYOUT_T83X;
  if ((gpu_id & 0xffffu) == 0x0820u) return HPC_GPU_MALI_COUNTER_LAYOUT_T82X;
  return HPC_GPU_MALI_COUNTER_LAYOUT_UNKNOWN;
}

typedef enum mali_counter_category_e {
  MALI_COUNTER_CATEGORY_JOB_MANAGER = 0,
  MALI_COUNTER_CATEGORY_TILER = 1,
  MALI_COUNTER_CATEGORY_SHADER_CORE = 2,
  MALI_COUNTER_CATEGORY_MEMORY = 3,
} mali_counter_category_t;

static inline mali_counter_category_t mali_get_counter_category(
    uint32_t counter) {
  return counter >> 8u;
}

//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//

int hpc_gpu_mali_create_context(
    uint32_t num_counters, uint32_t *counters,
    convert_counter_fn convert_counter,
    const hpc_gpu_host_allocation_callbacks_t *allocator,
    hpc_gpu_mali_context_t **out_context) {
  int gpu_device = hpc_gpu_mali_ioctl_open_gpu_device();
  if (gpu_device < 0) return gpu_device;

  // First negotiate API version with the kernel driver. Feeding in 0.0 means to
  // accept whatever version the kernel driver is at, as it does not really
  // matter for us. But we still need to perform this step because the kernel
  // driver needs to initialize API version inside.
  uint16_t major_version = 0, minor_version = 0;
  int status = hpc_gpu_mali_ioctl_setup_api_version(gpu_device, &major_version,
                                                    &minor_version);
  if (status < 0) return status;

  // Then setup the kernel API context. This is also necessary for future
  // interactions with the kernel driver.
  status = hpc_gpu_mali_ioctl_setup_api_context(gpu_device);
  if (status < 0) return status;

  // Query device information to figure out which GPU product this is.
  hpc_gpu_mali_ioctl_gpu_device_info_t device_info;
  status = hpc_gpu_mali_ioctl_get_gpu_device_info(gpu_device, allocator,
                                                  &device_info);
  if (status < 0) return status;

  hpc_gpu_mali_counter_layout_t layout =
      hpc_gpu_mali_get_counter_layout((uint16_t)device_info.gpu_product_id);
  if (layout == HPC_GPU_MALI_COUNTER_LAYOUT_UNKNOWN) {
    return -HPC_GPU_ERROR_UNKNOWN_DEVICE;
  }

  // Now it's time to set up the counter reader.
  hpc_gpu_mali_ioctl_perfcounter_reader_t counter_reader;
  status =
      hpc_gpu_mali_ioctl_open_perfcounter_reader(gpu_device, &counter_reader);
  if (status < 0) return status;

  // Allocate memory for the context itself.
  hpc_gpu_mali_context_t *context =
      allocator->alloc(allocator->user_data, sizeof(hpc_gpu_mali_context_t));

  context->num_counters = num_counters;
  context->gpu_device = gpu_device;
  context->counter_reader = counter_reader.reader_fd;

  // Allocate memory for the embedded buffer containing counter categories and
  // indices.
  uint32_t *categories =
      allocator->alloc(allocator->user_data, num_counters * sizeof(uint32_t));
  uint32_t *indices =
      allocator->alloc(allocator->user_data, num_counters * sizeof(uint32_t));
  for (int i = 0; i < num_counters; ++i) {
    categories[i] = mali_get_counter_category(counters[i]);
    indices[i] = convert_counter(counters[i], layout);
  }
  context->counter_categories = categories;
  context->counter_indices = indices;

  // Allocate memory for the embedded sample buffer.
  context->query_buffer =
      allocator->alloc(allocator->user_data, counter_reader.single_buffer_size);
  memset(context->query_buffer, 0, counter_reader.single_buffer_size);

  *out_context = context;
  return 0;
}

int hpc_gpu_mali_destroy_context(
    hpc_gpu_mali_context_t *context,
    const hpc_gpu_host_allocation_callbacks_t *allocator) {
  int status = close(context->counter_reader);
  if (status < 0) return status;
  status = close(context->gpu_device);
  if (status < 0) return status;

  allocator->free(allocator->user_data, context->query_buffer);
  allocator->free(allocator->user_data, context->counter_indices);
  allocator->free(allocator->user_data, context);
  return 0;
}
