#ifndef HPC_GPU_MALI_PRODUCT_H_
#define HPC_GPU_MALI_PRODUCT_H_

#include <stdint.h>

typedef enum hpc_gpu_mali_counter_layout_e hpc_gpu_mali_counter_layout_t;

/// Returns the corresponding counter layout for the given GPU ID.
///
/// @param[in] gpu_id The GPU ID number reported by Mali kernel driver.
hpc_gpu_mali_counter_layout_t hpc_gpu_mali_get_layout(uint16_t gpu_id);

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

/// Mali GPU counter layout schemes.
typedef enum hpc_gpu_mali_counter_layout_e {
  HPC_GPU_MALI_COUNTER_LAYOUT_UNKNOWN,
  HPC_GPU_MALI_COUNTER_LAYOUT_T60X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T62X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T72X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T76X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T82X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T83X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T86X,
  HPC_GPU_MALI_COUNTER_LAYOUT_T88X,
  HPC_GPU_MALI_COUNTER_LAYOUT_THEX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TMIX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TDVX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TSIX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TNOX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TGOX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TTRX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TNAX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TOTX,
  HPC_GPU_MALI_COUNTER_LAYOUT_TBOX
} hpc_gpu_mali_counter_layout_t;

//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//

#endif  // HPC_GPU_MALI_PRODUCT_H_
