#ifndef HPC_GPU_ADRENO_A5XX_H_
#define HPC_GPU_ADRENO_A5XX_H_

#include <stdint.h>

#include "hpc/gpu/base_utilities.h"

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

// Forward declaration of the counter enum
typedef enum hpc_gpu_adreno_a5xx_counter_e hpc_gpu_adreno_a5xx_counter_t;

/// The context for A5XX Adreno GPU counters.
///
/// Common counters mean counters available to all known Adreno GPUs.
typedef struct hpc_gpu_adreno_context_t hpc_gpu_adreno_context_t;

/// Creates a context for A5XX Adreno GPU counters.
///
/// Creating the context means talking with the Adreno kernel GPU driver and
/// allocating resources for sampling the given counters.
///
/// @param[in]  num_counters The number of counters to sample later.
/// @param[in]  counters     The pointer to the list of counters to sample
///                          later.
/// @param[in]  allocator    The allocator used to allocate host memory for
///                          sampling counters later.
/// @param[out] out_context  The pointer to the object receiving the resultant
///                          context.
int hpc_gpu_adreno_a5xx_create_context(
    uint32_t num_counters, hpc_gpu_adreno_a5xx_counter_t *counters,
    const hpc_gpu_host_allocation_callbacks_t *allocator,
    hpc_gpu_adreno_context_t **out_context);

/// Destroys the context for A5XX Adreno GPU counters.
///
/// @param[in] context   The counter sampling context.
/// @param[in] allocator The allocator used to free allocated host memory.
int hpc_gpu_adreno_a5xx_destroy_context(
    hpc_gpu_adreno_context_t *context,
    const hpc_gpu_host_allocation_callbacks_t *allocator);

/// Starts sampling the A5XX Adreno GPU counters specified when creating
/// the context.
///
/// This activates the registered counters and reads their initial values in
/// preparation for continously sampling.
///
/// @param[in] context The counter sampling context.
int hpc_gpu_adreno_a5xx_start_counters(const hpc_gpu_adreno_context_t *context);

/// Stops sampling the A5XX Adreno GPU counters specified when creating
/// the context.
///
/// This deactivates the registered counters.
///
/// @param[in] context The counter sampling context.
int hpc_gpu_adreno_a5xx_stop_counters(const hpc_gpu_adreno_context_t *context);

/// Samples the A5XX Adreno GPU counters specified when creating
/// the context.
///
/// @param[in]  context The counter sampling context.
/// @param[out] values  The pointer to the memory for receiving newly sampled
///                     values. Its element count should be greater than or
///                     equal to the number of counters specified when
///                     creating the `context`.
int hpc_gpu_adreno_a5xx_query_counters(hpc_gpu_adreno_context_t *context,
                                       uint64_t *values);

//===-------------- BEGIN AUTOGENERATED REGION; DO NOT EDIT! --------------===//

/// Counter choices for Adreno A5XX series.
typedef enum hpc_gpu_adreno_a5xx_counter_e {
  /// Command Parser: always count
  HPC_GPU_ADRENO_A5XX_CP_ALWAYS_COUNT = 0,
  /// Command Parser: busy gfx core idle
  HPC_GPU_ADRENO_A5XX_CP_BUSY_GFX_CORE_IDLE = 1,
  /// Command Parser: busy cycles
  HPC_GPU_ADRENO_A5XX_CP_BUSY_CYCLES = 2,
  /// Command Parser: pfp idle
  HPC_GPU_ADRENO_A5XX_CP_PFP_IDLE = 3,
  /// Command Parser: pfp busy working
  HPC_GPU_ADRENO_A5XX_CP_PFP_BUSY_WORKING = 4,
  /// Command Parser: pfp stall cycles any
  HPC_GPU_ADRENO_A5XX_CP_PFP_STALL_CYCLES_ANY = 5,
  /// Command Parser: pfp starve cycles any
  HPC_GPU_ADRENO_A5XX_CP_PFP_STARVE_CYCLES_ANY = 6,
  /// Command Parser: pfp icache miss
  HPC_GPU_ADRENO_A5XX_CP_PFP_ICACHE_MISS = 7,
  /// Command Parser: pfp icache hit
  HPC_GPU_ADRENO_A5XX_CP_PFP_ICACHE_HIT = 8,
  /// Command Parser: pfp match pm4 pkt profile
  HPC_GPU_ADRENO_A5XX_CP_PFP_MATCH_PM4_PKT_PROFILE = 9,
  /// Command Parser: ME busy working
  HPC_GPU_ADRENO_A5XX_CP_ME_BUSY_WORKING = 10,
  /// Command Parser: ME idle
  HPC_GPU_ADRENO_A5XX_CP_ME_IDLE = 11,
  /// Command Parser: ME starve cycles any
  HPC_GPU_ADRENO_A5XX_CP_ME_STARVE_CYCLES_ANY = 12,
  /// Command Parser: ME fifo empty pfp idle
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_EMPTY_PFP_IDLE = 13,
  /// Command Parser: ME fifo empty pfp busy
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_EMPTY_PFP_BUSY = 14,
  /// Command Parser: ME fifo full ME busy
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_FULL_ME_BUSY = 15,
  /// Command Parser: ME fifo full ME non working
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_FULL_ME_NON_WORKING = 16,
  /// Command Parser: ME stall cycles any
  HPC_GPU_ADRENO_A5XX_CP_ME_STALL_CYCLES_ANY = 17,
  /// Command Parser: ME icache miss
  HPC_GPU_ADRENO_A5XX_CP_ME_ICACHE_MISS = 18,
  /// Command Parser: ME icache hit
  HPC_GPU_ADRENO_A5XX_CP_ME_ICACHE_HIT = 19,
  /// Command Parser: num preemptions
  HPC_GPU_ADRENO_A5XX_CP_NUM_PREEMPTIONS = 20,
  /// Command Parser: preemption reaction delay
  HPC_GPU_ADRENO_A5XX_CP_PREEMPTION_REACTION_DELAY = 21,
  /// Command Parser: preemption switch out time
  HPC_GPU_ADRENO_A5XX_CP_PREEMPTION_SWITCH_OUT_TIME = 22,
  /// Command Parser: preemption switch IN time
  HPC_GPU_ADRENO_A5XX_CP_PREEMPTION_SWITCH_IN_TIME = 23,
  /// Command Parser: dead draws IN bin render
  HPC_GPU_ADRENO_A5XX_CP_DEAD_DRAWS_IN_BIN_RENDER = 24,
  /// Command Parser: predicated draws killed
  HPC_GPU_ADRENO_A5XX_CP_PREDICATED_DRAWS_KILLED = 25,
  /// Command Parser: mode switch
  HPC_GPU_ADRENO_A5XX_CP_MODE_SWITCH = 26,
  /// Command Parser: zpass done
  HPC_GPU_ADRENO_A5XX_CP_ZPASS_DONE = 27,
  /// Command Parser: context done
  HPC_GPU_ADRENO_A5XX_CP_CONTEXT_DONE = 28,
  /// Command Parser: cache flush
  HPC_GPU_ADRENO_A5XX_CP_CACHE_FLUSH = 29,
  /// Command Parser: long preemptions
  HPC_GPU_ADRENO_A5XX_CP_LONG_PREEMPTIONS = 30,
  /// RBBM: always count
  HPC_GPU_ADRENO_A5XX_RBBM_ALWAYS_COUNT = 256,
  /// RBBM: always ON
  HPC_GPU_ADRENO_A5XX_RBBM_ALWAYS_ON = 257,
  /// RBBM: TSE busy
  HPC_GPU_ADRENO_A5XX_RBBM_TSE_BUSY = 258,
  /// RBBM: RAS busy
  HPC_GPU_ADRENO_A5XX_RBBM_RAS_BUSY = 259,
  /// RBBM: PC dcall busy
  HPC_GPU_ADRENO_A5XX_RBBM_PC_DCALL_BUSY = 260,
  /// RBBM: PC vsd busy
  HPC_GPU_ADRENO_A5XX_RBBM_PC_VSD_BUSY = 261,
  /// RBBM: status masked
  HPC_GPU_ADRENO_A5XX_RBBM_STATUS_MASKED = 262,
  /// RBBM: com busy
  HPC_GPU_ADRENO_A5XX_RBBM_COM_BUSY = 263,
  /// RBBM: dcom busy
  HPC_GPU_ADRENO_A5XX_RBBM_DCOM_BUSY = 264,
  /// RBBM: VBIF busy
  HPC_GPU_ADRENO_A5XX_RBBM_VBIF_BUSY = 265,
  /// RBBM: VSC busy
  HPC_GPU_ADRENO_A5XX_RBBM_VSC_BUSY = 266,
  /// RBBM: tess busy
  HPC_GPU_ADRENO_A5XX_RBBM_TESS_BUSY = 267,
  /// RBBM: UCHE busy
  HPC_GPU_ADRENO_A5XX_RBBM_UCHE_BUSY = 268,
  /// RBBM: HLSQ busy
  HPC_GPU_ADRENO_A5XX_RBBM_HLSQ_BUSY = 269,
  /// PC: busy cycles
  HPC_GPU_ADRENO_A5XX_PC_BUSY_CYCLES = 512,
  /// PC: working cycles
  HPC_GPU_ADRENO_A5XX_PC_WORKING_CYCLES = 513,
  /// PC: stall cycles VFD
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_VFD = 514,
  /// PC: stall cycles TSE
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_TSE = 515,
  /// PC: stall cycles VPC
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_VPC = 516,
  /// PC: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_UCHE = 517,
  /// PC: stall cycles tess
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_TESS = 518,
  /// PC: stall cycles TSE only
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_TSE_ONLY = 519,
  /// PC: stall cycles VPC only
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_VPC_ONLY = 520,
  /// PC: pass1 TF stall cycles
  HPC_GPU_ADRENO_A5XX_PC_PASS1_TF_STALL_CYCLES = 521,
  /// PC: starve cycles for index
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_INDEX = 522,
  /// PC: starve cycles for tess factor
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_TESS_FACTOR = 523,
  /// PC: starve cycles for viz stream
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_VIZ_STREAM = 524,
  /// PC: starve cycles for position
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_POSITION = 525,
  /// PC: starve cycles DI
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_DI = 526,
  /// PC: vis streams loaded
  HPC_GPU_ADRENO_A5XX_PC_VIS_STREAMS_LOADED = 527,
  /// PC: instances
  HPC_GPU_ADRENO_A5XX_PC_INSTANCES = 528,
  /// PC: VPC primitives
  HPC_GPU_ADRENO_A5XX_PC_VPC_PRIMITIVES = 529,
  /// PC: dead prim
  HPC_GPU_ADRENO_A5XX_PC_DEAD_PRIM = 530,
  /// PC: live prim
  HPC_GPU_ADRENO_A5XX_PC_LIVE_PRIM = 531,
  /// PC: vertex hits
  HPC_GPU_ADRENO_A5XX_PC_VERTEX_HITS = 532,
  /// PC: IA vertices
  HPC_GPU_ADRENO_A5XX_PC_IA_VERTICES = 533,
  /// PC: IA primitives
  HPC_GPU_ADRENO_A5XX_PC_IA_PRIMITIVES = 534,
  /// PC: GS primitives
  HPC_GPU_ADRENO_A5XX_PC_GS_PRIMITIVES = 535,
  /// PC: HS invocations
  HPC_GPU_ADRENO_A5XX_PC_HS_INVOCATIONS = 536,
  /// PC: DS invocations
  HPC_GPU_ADRENO_A5XX_PC_DS_INVOCATIONS = 537,
  /// PC: VS invocations
  HPC_GPU_ADRENO_A5XX_PC_VS_INVOCATIONS = 538,
  /// PC: GS invocations
  HPC_GPU_ADRENO_A5XX_PC_GS_INVOCATIONS = 539,
  /// PC: DS primitives
  HPC_GPU_ADRENO_A5XX_PC_DS_PRIMITIVES = 540,
  /// PC: VPC pos data transaction
  HPC_GPU_ADRENO_A5XX_PC_VPC_POS_DATA_TRANSACTION = 541,
  /// PC: 3D drawcalls
  HPC_GPU_ADRENO_A5XX_PC_3D_DRAWCALLS = 542,
  /// PC: 2D drawcalls
  HPC_GPU_ADRENO_A5XX_PC_2D_DRAWCALLS = 543,
  /// PC: non drawcall global events
  HPC_GPU_ADRENO_A5XX_PC_NON_DRAWCALL_GLOBAL_EVENTS = 544,
  /// PC: tess busy cycles
  HPC_GPU_ADRENO_A5XX_PC_TESS_BUSY_CYCLES = 545,
  /// PC: tess working cycles
  HPC_GPU_ADRENO_A5XX_PC_TESS_WORKING_CYCLES = 546,
  /// PC: tess stall cycles PC
  HPC_GPU_ADRENO_A5XX_PC_TESS_STALL_CYCLES_PC = 547,
  /// PC: tess starve cycles PC
  HPC_GPU_ADRENO_A5XX_PC_TESS_STARVE_CYCLES_PC = 548,
  /// VFD: busy cycles
  HPC_GPU_ADRENO_A5XX_VFD_BUSY_CYCLES = 768,
  /// VFD: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_UCHE = 769,
  /// VFD: stall cycles VPC alloc
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_VPC_ALLOC = 770,
  /// VFD: stall cycles miss VB
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_MISS_VB = 771,
  /// VFD: stall cycles miss Q
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_MISS_Q = 772,
  /// VFD: stall cycles SP info
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_SP_INFO = 773,
  /// VFD: stall cycles SP attr
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_SP_ATTR = 774,
  /// VFD: stall cycles vfdp VB
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_VFDP_VB = 775,
  /// VFD: stall cycles vfdp Q
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_VFDP_Q = 776,
  /// VFD: decoder packer stall
  HPC_GPU_ADRENO_A5XX_VFD_DECODER_PACKER_STALL = 777,
  /// VFD: starve cycles UCHE
  HPC_GPU_ADRENO_A5XX_VFD_STARVE_CYCLES_UCHE = 778,
  /// VFD: rbuffer full
  HPC_GPU_ADRENO_A5XX_VFD_RBUFFER_FULL = 779,
  /// VFD: attr info fifo full
  HPC_GPU_ADRENO_A5XX_VFD_ATTR_INFO_FIFO_FULL = 780,
  /// VFD: decoded attribute bytes
  HPC_GPU_ADRENO_A5XX_VFD_DECODED_ATTRIBUTE_BYTES = 781,
  /// VFD: num attributes
  HPC_GPU_ADRENO_A5XX_VFD_NUM_ATTRIBUTES = 782,
  /// VFD: instructions
  HPC_GPU_ADRENO_A5XX_VFD_INSTRUCTIONS = 783,
  /// VFD: upper shader fibers
  HPC_GPU_ADRENO_A5XX_VFD_UPPER_SHADER_FIBERS = 784,
  /// VFD: lower shader fibers
  HPC_GPU_ADRENO_A5XX_VFD_LOWER_SHADER_FIBERS = 785,
  /// VFD: mode 0 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_0_FIBERS = 786,
  /// VFD: mode 1 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_1_FIBERS = 787,
  /// VFD: mode 2 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_2_FIBERS = 788,
  /// VFD: mode 3 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_3_FIBERS = 789,
  /// VFD: mode 4 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_4_FIBERS = 790,
  /// VFD: total vertices
  HPC_GPU_ADRENO_A5XX_VFD_TOTAL_VERTICES = 791,
  /// VFD: num attr miss
  HPC_GPU_ADRENO_A5XX_VFD_NUM_ATTR_MISS = 792,
  /// VFD: 1 burst req
  HPC_GPU_ADRENO_A5XX_VFD_1_BURST_REQ = 793,
  /// VFD: vfdp stall cycles VFD
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STALL_CYCLES_VFD = 794,
  /// VFD: vfdp stall cycles VFD index
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STALL_CYCLES_VFD_INDEX = 795,
  /// VFD: vfdp stall cycles VFD prog
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STALL_CYCLES_VFD_PROG = 796,
  /// VFD: vfdp starve cycles PC
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STARVE_CYCLES_PC = 797,
  /// VFD: vfdp VS stage 32 waves
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_VS_STAGE_32_WAVES = 798,
  /// High Level SeQuencer: busy cycles
  HPC_GPU_ADRENO_A5XX_HLSQ_BUSY_CYCLES = 1024,
  /// High Level SeQuencer: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_HLSQ_STALL_CYCLES_UCHE = 1025,
  /// High Level SeQuencer: stall cycles SP state
  HPC_GPU_ADRENO_A5XX_HLSQ_STALL_CYCLES_SP_STATE = 1026,
  /// High Level SeQuencer: stall cycles SP FS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_STALL_CYCLES_SP_FS_STAGE = 1027,
  /// High Level SeQuencer: UCHE latency cycles
  HPC_GPU_ADRENO_A5XX_HLSQ_UCHE_LATENCY_CYCLES = 1028,
  /// High Level SeQuencer: UCHE latency count
  HPC_GPU_ADRENO_A5XX_HLSQ_UCHE_LATENCY_COUNT = 1029,
  /// High Level SeQuencer: FS stage 32 waves
  HPC_GPU_ADRENO_A5XX_HLSQ_FS_STAGE_32_WAVES = 1030,
  /// High Level SeQuencer: FS stage 64 waves
  HPC_GPU_ADRENO_A5XX_HLSQ_FS_STAGE_64_WAVES = 1031,
  /// High Level SeQuencer: quads
  HPC_GPU_ADRENO_A5XX_HLSQ_QUADS = 1032,
  /// High Level SeQuencer: SP state copy trans FS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_SP_STATE_COPY_TRANS_FS_STAGE = 1033,
  /// High Level SeQuencer: SP state copy trans VS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_SP_STATE_COPY_TRANS_VS_STAGE = 1034,
  /// High Level SeQuencer: TP state copy trans FS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_TP_STATE_COPY_TRANS_FS_STAGE = 1035,
  /// High Level SeQuencer: TP state copy trans VS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_TP_STATE_COPY_TRANS_VS_STAGE = 1036,
  /// High Level SeQuencer: CS invocations
  HPC_GPU_ADRENO_A5XX_HLSQ_CS_INVOCATIONS = 1037,
  /// High Level SeQuencer: compute drawcalls
  HPC_GPU_ADRENO_A5XX_HLSQ_COMPUTE_DRAWCALLS = 1038,
  /// VPC: busy cycles
  HPC_GPU_ADRENO_A5XX_VPC_BUSY_CYCLES = 1280,
  /// VPC: working cycles
  HPC_GPU_ADRENO_A5XX_VPC_WORKING_CYCLES = 1281,
  /// VPC: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_UCHE = 1282,
  /// VPC: stall cycles VFD wack
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_VFD_WACK = 1283,
  /// VPC: stall cycles HLSQ prim alloc
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_HLSQ_PRIM_ALLOC = 1284,
  /// VPC: stall cycles PC
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_PC = 1285,
  /// VPC: stall cycles SP LM
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_SP_LM = 1286,
  /// VPC: pos export stall cycles
  HPC_GPU_ADRENO_A5XX_VPC_POS_EXPORT_STALL_CYCLES = 1287,
  /// VPC: starve cycles SP
  HPC_GPU_ADRENO_A5XX_VPC_STARVE_CYCLES_SP = 1288,
  /// VPC: starve cycles LRZ
  HPC_GPU_ADRENO_A5XX_VPC_STARVE_CYCLES_LRZ = 1289,
  /// VPC: PC primitives
  HPC_GPU_ADRENO_A5XX_VPC_PC_PRIMITIVES = 1290,
  /// VPC: SP components
  HPC_GPU_ADRENO_A5XX_VPC_SP_COMPONENTS = 1291,
  /// VPC: SP LM primitives
  HPC_GPU_ADRENO_A5XX_VPC_SP_LM_PRIMITIVES = 1292,
  /// VPC: SP LM components
  HPC_GPU_ADRENO_A5XX_VPC_SP_LM_COMPONENTS = 1293,
  /// VPC: SP LM dwords
  HPC_GPU_ADRENO_A5XX_VPC_SP_LM_DWORDS = 1294,
  /// VPC: streamout components
  HPC_GPU_ADRENO_A5XX_VPC_STREAMOUT_COMPONENTS = 1295,
  /// VPC: grant phases
  HPC_GPU_ADRENO_A5XX_VPC_GRANT_PHASES = 1296,
  /// Triangle Setup Engine: busy cycles
  HPC_GPU_ADRENO_A5XX_TSE_BUSY_CYCLES = 1536,
  /// Triangle Setup Engine: clipping cycles
  HPC_GPU_ADRENO_A5XX_TSE_CLIPPING_CYCLES = 1537,
  /// Triangle Setup Engine: stall cycles RAS
  HPC_GPU_ADRENO_A5XX_TSE_STALL_CYCLES_RAS = 1538,
  /// Triangle Setup Engine: stall cycles LRZ baryplane
  HPC_GPU_ADRENO_A5XX_TSE_STALL_CYCLES_LRZ_BARYPLANE = 1539,
  /// Triangle Setup Engine: stall cycles LRZ zplane
  HPC_GPU_ADRENO_A5XX_TSE_STALL_CYCLES_LRZ_ZPLANE = 1540,
  /// Triangle Setup Engine: starve cycles PC
  HPC_GPU_ADRENO_A5XX_TSE_STARVE_CYCLES_PC = 1541,
  /// Triangle Setup Engine: input prim
  HPC_GPU_ADRENO_A5XX_TSE_INPUT_PRIM = 1542,
  /// Triangle Setup Engine: input null prim
  HPC_GPU_ADRENO_A5XX_TSE_INPUT_NULL_PRIM = 1543,
  /// Triangle Setup Engine: trival rej prim
  HPC_GPU_ADRENO_A5XX_TSE_TRIVAL_REJ_PRIM = 1544,
  /// Triangle Setup Engine: clipped prim
  HPC_GPU_ADRENO_A5XX_TSE_CLIPPED_PRIM = 1545,
  /// Triangle Setup Engine: zero area prim
  HPC_GPU_ADRENO_A5XX_TSE_ZERO_AREA_PRIM = 1546,
  /// Triangle Setup Engine: faceness culled prim
  HPC_GPU_ADRENO_A5XX_TSE_FACENESS_CULLED_PRIM = 1547,
  /// Triangle Setup Engine: zero pixel prim
  HPC_GPU_ADRENO_A5XX_TSE_ZERO_PIXEL_PRIM = 1548,
  /// Triangle Setup Engine: output null prim
  HPC_GPU_ADRENO_A5XX_TSE_OUTPUT_NULL_PRIM = 1549,
  /// Triangle Setup Engine: output visible prim
  HPC_GPU_ADRENO_A5XX_TSE_OUTPUT_VISIBLE_PRIM = 1550,
  /// Triangle Setup Engine: cinvocation
  HPC_GPU_ADRENO_A5XX_TSE_CINVOCATION = 1551,
  /// Triangle Setup Engine: cprimitives
  HPC_GPU_ADRENO_A5XX_TSE_CPRIMITIVES = 1552,
  /// Triangle Setup Engine: 2D input prim
  HPC_GPU_ADRENO_A5XX_TSE_2D_INPUT_PRIM = 1553,
  /// Triangle Setup Engine: 2D alive clcles
  HPC_GPU_ADRENO_A5XX_TSE_2D_ALIVE_CLCLES = 1554,
  /// RAS: busy cycles
  HPC_GPU_ADRENO_A5XX_RAS_BUSY_CYCLES = 1792,
  /// RAS: supertile active cycles
  HPC_GPU_ADRENO_A5XX_RAS_SUPERTILE_ACTIVE_CYCLES = 1793,
  /// RAS: stall cycles LRZ
  HPC_GPU_ADRENO_A5XX_RAS_STALL_CYCLES_LRZ = 1794,
  /// RAS: starve cycles TSE
  HPC_GPU_ADRENO_A5XX_RAS_STARVE_CYCLES_TSE = 1795,
  /// RAS: super tiles
  HPC_GPU_ADRENO_A5XX_RAS_SUPER_TILES = 1796,
  /// RAS: 8x4 tiles
  HPC_GPU_ADRENO_A5XX_RAS_8X4_TILES = 1797,
  /// RAS: maskgen active
  HPC_GPU_ADRENO_A5XX_RAS_MASKGEN_ACTIVE = 1798,
  /// RAS: fully covered super tiles
  HPC_GPU_ADRENO_A5XX_RAS_FULLY_COVERED_SUPER_TILES = 1799,
  /// RAS: fully covered 8x4 tiles
  HPC_GPU_ADRENO_A5XX_RAS_FULLY_COVERED_8X4_TILES = 1800,
  /// RAS: prim killed invisilbe
  HPC_GPU_ADRENO_A5XX_RAS_PRIM_KILLED_INVISILBE = 1801,
  /// Unified L2 Cache: busy cycles
  HPC_GPU_ADRENO_A5XX_UCHE_BUSY_CYCLES = 2048,
  /// Unified L2 Cache: stall cycles VBIF
  HPC_GPU_ADRENO_A5XX_UCHE_STALL_CYCLES_VBIF = 2049,
  /// Unified L2 Cache: VBIF latency cycles
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_LATENCY_CYCLES = 2050,
  /// Unified L2 Cache: VBIF latency samples
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_LATENCY_SAMPLES = 2051,
  /// Unified L2 Cache: VBIF read beats TP
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_TP = 2052,
  /// Unified L2 Cache: VBIF read beats VFD
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_VFD = 2053,
  /// Unified L2 Cache: VBIF read beats HLSQ
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_HLSQ = 2054,
  /// Unified L2 Cache: VBIF read beats LRZ
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_LRZ = 2055,
  /// Unified L2 Cache: VBIF read beats SP
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_SP = 2056,
  /// Unified L2 Cache: read requests TP
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_TP = 2057,
  /// Unified L2 Cache: read requests VFD
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_VFD = 2058,
  /// Unified L2 Cache: read requests HLSQ
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_HLSQ = 2059,
  /// Unified L2 Cache: read requests LRZ
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_LRZ = 2060,
  /// Unified L2 Cache: read requests SP
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_SP = 2061,
  /// Unified L2 Cache: write requests LRZ
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_LRZ = 2062,
  /// Unified L2 Cache: write requests SP
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_SP = 2063,
  /// Unified L2 Cache: write requests VPC
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_VPC = 2064,
  /// Unified L2 Cache: write requests VSC
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_VSC = 2065,
  /// Unified L2 Cache: evicts
  HPC_GPU_ADRENO_A5XX_UCHE_EVICTS = 2066,
  /// Unified L2 Cache: bank req0
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ0 = 2067,
  /// Unified L2 Cache: bank req1
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ1 = 2068,
  /// Unified L2 Cache: bank req2
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ2 = 2069,
  /// Unified L2 Cache: bank req3
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ3 = 2070,
  /// Unified L2 Cache: bank req4
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ4 = 2071,
  /// Unified L2 Cache: bank req5
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ5 = 2072,
  /// Unified L2 Cache: bank req6
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ6 = 2073,
  /// Unified L2 Cache: bank req7
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ7 = 2074,
  /// Unified L2 Cache: VBIF read beats ch0
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_CH0 = 2075,
  /// Unified L2 Cache: VBIF read beats ch1
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_CH1 = 2076,
  /// Unified L2 Cache: gmem read beats
  HPC_GPU_ADRENO_A5XX_UCHE_GMEM_READ_BEATS = 2077,
  /// Unified L2 Cache: flag count
  HPC_GPU_ADRENO_A5XX_UCHE_FLAG_COUNT = 2078,
  /// Texture Processor: busy cycles
  HPC_GPU_ADRENO_A5XX_TP_BUSY_CYCLES = 2304,
  /// Texture Processor: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_TP_STALL_CYCLES_UCHE = 2305,
  /// Texture Processor: latency cycles
  HPC_GPU_ADRENO_A5XX_TP_LATENCY_CYCLES = 2306,
  /// Texture Processor: latency trans
  HPC_GPU_ADRENO_A5XX_TP_LATENCY_TRANS = 2307,
  /// Texture Processor: flag cache request samples
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_REQUEST_SAMPLES = 2308,
  /// Texture Processor: flag cache request latency
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_REQUEST_LATENCY = 2309,
  /// Texture Processor: L1 cacheline requests
  HPC_GPU_ADRENO_A5XX_TP_L1_CACHELINE_REQUESTS = 2310,
  /// Texture Processor: L1 cacheline misses
  HPC_GPU_ADRENO_A5XX_TP_L1_CACHELINE_MISSES = 2311,
  /// Texture Processor: SP TP trans
  HPC_GPU_ADRENO_A5XX_TP_SP_TP_TRANS = 2312,
  /// Texture Processor: TP SP trans
  HPC_GPU_ADRENO_A5XX_TP_TP_SP_TRANS = 2313,
  /// Texture Processor: output pixels
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS = 2314,
  /// Texture Processor: filter workload 16bit
  HPC_GPU_ADRENO_A5XX_TP_FILTER_WORKLOAD_16BIT = 2315,
  /// Texture Processor: filter workload 32bit
  HPC_GPU_ADRENO_A5XX_TP_FILTER_WORKLOAD_32BIT = 2316,
  /// Texture Processor: quads received
  HPC_GPU_ADRENO_A5XX_TP_QUADS_RECEIVED = 2317,
  /// Texture Processor: quads offset
  HPC_GPU_ADRENO_A5XX_TP_QUADS_OFFSET = 2318,
  /// Texture Processor: quads shadow
  HPC_GPU_ADRENO_A5XX_TP_QUADS_SHADOW = 2319,
  /// Texture Processor: quads array
  HPC_GPU_ADRENO_A5XX_TP_QUADS_ARRAY = 2320,
  /// Texture Processor: quads gradient
  HPC_GPU_ADRENO_A5XX_TP_QUADS_GRADIENT = 2321,
  /// Texture Processor: quads 1D
  HPC_GPU_ADRENO_A5XX_TP_QUADS_1D = 2322,
  /// Texture Processor: quads 2D
  HPC_GPU_ADRENO_A5XX_TP_QUADS_2D = 2323,
  /// Texture Processor: quads buffer
  HPC_GPU_ADRENO_A5XX_TP_QUADS_BUFFER = 2324,
  /// Texture Processor: quads 3D
  HPC_GPU_ADRENO_A5XX_TP_QUADS_3D = 2325,
  /// Texture Processor: quads cube
  HPC_GPU_ADRENO_A5XX_TP_QUADS_CUBE = 2326,
  /// Texture Processor: state cache requests
  HPC_GPU_ADRENO_A5XX_TP_STATE_CACHE_REQUESTS = 2327,
  /// Texture Processor: state cache misses
  HPC_GPU_ADRENO_A5XX_TP_STATE_CACHE_MISSES = 2328,
  /// Texture Processor: divergent quads received
  HPC_GPU_ADRENO_A5XX_TP_DIVERGENT_QUADS_RECEIVED = 2329,
  /// Texture Processor: bindless state cache requests
  HPC_GPU_ADRENO_A5XX_TP_BINDLESS_STATE_CACHE_REQUESTS = 2330,
  /// Texture Processor: bindless state cache misses
  HPC_GPU_ADRENO_A5XX_TP_BINDLESS_STATE_CACHE_MISSES = 2331,
  /// Texture Processor: prt non resident events
  HPC_GPU_ADRENO_A5XX_TP_PRT_NON_RESIDENT_EVENTS = 2332,
  /// Texture Processor: output pixels point
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_POINT = 2333,
  /// Texture Processor: output pixels bilinear
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_BILINEAR = 2334,
  /// Texture Processor: output pixels mip
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_MIP = 2335,
  /// Texture Processor: output pixels aniso
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_ANISO = 2336,
  /// Texture Processor: output pixels zero lod
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_ZERO_LOD = 2337,
  /// Texture Processor: flag cache requests
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_REQUESTS = 2338,
  /// Texture Processor: flag cache misses
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_MISSES = 2339,
  /// Texture Processor: L1 5 L2 requests
  HPC_GPU_ADRENO_A5XX_TP_L1_5_L2_REQUESTS = 2340,
  /// Texture Processor: 2D output pixels
  HPC_GPU_ADRENO_A5XX_TP_2D_OUTPUT_PIXELS = 2341,
  /// Texture Processor: 2D output pixels point
  HPC_GPU_ADRENO_A5XX_TP_2D_OUTPUT_PIXELS_POINT = 2342,
  /// Texture Processor: 2D output pixels bilinear
  HPC_GPU_ADRENO_A5XX_TP_2D_OUTPUT_PIXELS_BILINEAR = 2343,
  /// Texture Processor: 2D filter workload 16bit
  HPC_GPU_ADRENO_A5XX_TP_2D_FILTER_WORKLOAD_16BIT = 2344,
  /// Texture Processor: 2D filter workload 32bit
  HPC_GPU_ADRENO_A5XX_TP_2D_FILTER_WORKLOAD_32BIT = 2345,
  /// Shader/Streaming Processor: busy cycles
  HPC_GPU_ADRENO_A5XX_SP_BUSY_CYCLES = 2560,
  /// Shader/Streaming Processor: ALU working cycles
  HPC_GPU_ADRENO_A5XX_SP_ALU_WORKING_CYCLES = 2561,
  /// Shader/Streaming Processor: EFU working cycles
  HPC_GPU_ADRENO_A5XX_SP_EFU_WORKING_CYCLES = 2562,
  /// Shader/Streaming Processor: stall cycles VPC
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_VPC = 2563,
  /// Shader/Streaming Processor: stall cycles TP
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_TP = 2564,
  /// Shader/Streaming Processor: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_UCHE = 2565,
  /// Shader/Streaming Processor: stall cycles RB
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_RB = 2566,
  /// Shader/Streaming Processor: scheduler non working
  HPC_GPU_ADRENO_A5XX_SP_SCHEDULER_NON_WORKING = 2567,
  /// Shader/Streaming Processor: wave contexts
  HPC_GPU_ADRENO_A5XX_SP_WAVE_CONTEXTS = 2568,
  /// Shader/Streaming Processor: wave context cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_CONTEXT_CYCLES = 2569,
  /// Shader/Streaming Processor: FS stage wave cycles
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_WAVE_CYCLES = 2570,
  /// Shader/Streaming Processor: FS stage wave samples
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_WAVE_SAMPLES = 2571,
  /// Shader/Streaming Processor: VS stage wave cycles
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_WAVE_CYCLES = 2572,
  /// Shader/Streaming Processor: VS stage wave samples
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_WAVE_SAMPLES = 2573,
  /// Shader/Streaming Processor: FS stage duration cycles
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_DURATION_CYCLES = 2574,
  /// Shader/Streaming Processor: VS stage duration cycles
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_DURATION_CYCLES = 2575,
  /// Shader/Streaming Processor: wave ctrl cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_CTRL_CYCLES = 2576,
  /// Shader/Streaming Processor: wave load cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_LOAD_CYCLES = 2577,
  /// Shader/Streaming Processor: wave emit cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_EMIT_CYCLES = 2578,
  /// Shader/Streaming Processor: wave nop cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_NOP_CYCLES = 2579,
  /// Shader/Streaming Processor: wave wait cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_WAIT_CYCLES = 2580,
  /// Shader/Streaming Processor: wave fetch cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_FETCH_CYCLES = 2581,
  /// Shader/Streaming Processor: wave idle cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_IDLE_CYCLES = 2582,
  /// Shader/Streaming Processor: wave end cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_END_CYCLES = 2583,
  /// Shader/Streaming Processor: wave long sync cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_LONG_SYNC_CYCLES = 2584,
  /// Shader/Streaming Processor: wave short sync cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_SHORT_SYNC_CYCLES = 2585,
  /// Shader/Streaming Processor: wave join cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_JOIN_CYCLES = 2586,
  /// Shader/Streaming Processor: LM load instructions
  HPC_GPU_ADRENO_A5XX_SP_LM_LOAD_INSTRUCTIONS = 2587,
  /// Shader/Streaming Processor: LM store instructions
  HPC_GPU_ADRENO_A5XX_SP_LM_STORE_INSTRUCTIONS = 2588,
  /// Shader/Streaming Processor: LM atomics
  HPC_GPU_ADRENO_A5XX_SP_LM_ATOMICS = 2589,
  /// Shader/Streaming Processor: GM load instructions
  HPC_GPU_ADRENO_A5XX_SP_GM_LOAD_INSTRUCTIONS = 2590,
  /// Shader/Streaming Processor: GM store instructions
  HPC_GPU_ADRENO_A5XX_SP_GM_STORE_INSTRUCTIONS = 2591,
  /// Shader/Streaming Processor: GM atomics
  HPC_GPU_ADRENO_A5XX_SP_GM_ATOMICS = 2592,
  /// Shader/Streaming Processor: VS stage tex instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_TEX_INSTRUCTIONS = 2593,
  /// Shader/Streaming Processor: VS stage cflow instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_CFLOW_INSTRUCTIONS = 2594,
  /// Shader/Streaming Processor: VS stage EFU instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_EFU_INSTRUCTIONS = 2595,
  /// Shader/Streaming Processor: VS stage full ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_FULL_ALU_INSTRUCTIONS = 2596,
  /// Shader/Streaming Processor: VS stage half ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_HALF_ALU_INSTRUCTIONS = 2597,
  /// Shader/Streaming Processor: FS stage tex instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_TEX_INSTRUCTIONS = 2598,
  /// Shader/Streaming Processor: FS stage cflow instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_CFLOW_INSTRUCTIONS = 2599,
  /// Shader/Streaming Processor: FS stage EFU instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_EFU_INSTRUCTIONS = 2600,
  /// Shader/Streaming Processor: FS stage full ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_FULL_ALU_INSTRUCTIONS = 2601,
  /// Shader/Streaming Processor: FS stage half ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_HALF_ALU_INSTRUCTIONS = 2602,
  /// Shader/Streaming Processor: FS stage bary instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_BARY_INSTRUCTIONS = 2603,
  /// Shader/Streaming Processor: VS instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_INSTRUCTIONS = 2604,
  /// Shader/Streaming Processor: FS instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_INSTRUCTIONS = 2605,
  /// Shader/Streaming Processor: addr lock count
  HPC_GPU_ADRENO_A5XX_SP_ADDR_LOCK_COUNT = 2606,
  /// Shader/Streaming Processor: UCHE read trans
  HPC_GPU_ADRENO_A5XX_SP_UCHE_READ_TRANS = 2607,
  /// Shader/Streaming Processor: UCHE write trans
  HPC_GPU_ADRENO_A5XX_SP_UCHE_WRITE_TRANS = 2608,
  /// Shader/Streaming Processor: export VPC trans
  HPC_GPU_ADRENO_A5XX_SP_EXPORT_VPC_TRANS = 2609,
  /// Shader/Streaming Processor: export RB trans
  HPC_GPU_ADRENO_A5XX_SP_EXPORT_RB_TRANS = 2610,
  /// Shader/Streaming Processor: pixels killed
  HPC_GPU_ADRENO_A5XX_SP_PIXELS_KILLED = 2611,
  /// Shader/Streaming Processor: icl1 requests
  HPC_GPU_ADRENO_A5XX_SP_ICL1_REQUESTS = 2612,
  /// Shader/Streaming Processor: icl1 misses
  HPC_GPU_ADRENO_A5XX_SP_ICL1_MISSES = 2613,
  /// Shader/Streaming Processor: icl0 requests
  HPC_GPU_ADRENO_A5XX_SP_ICL0_REQUESTS = 2614,
  /// Shader/Streaming Processor: icl0 misses
  HPC_GPU_ADRENO_A5XX_SP_ICL0_MISSES = 2615,
  /// Shader/Streaming Processor: HS instructions
  HPC_GPU_ADRENO_A5XX_SP_HS_INSTRUCTIONS = 2616,
  /// Shader/Streaming Processor: DS instructions
  HPC_GPU_ADRENO_A5XX_SP_DS_INSTRUCTIONS = 2617,
  /// Shader/Streaming Processor: GS instructions
  HPC_GPU_ADRENO_A5XX_SP_GS_INSTRUCTIONS = 2618,
  /// Shader/Streaming Processor: CS instructions
  HPC_GPU_ADRENO_A5XX_SP_CS_INSTRUCTIONS = 2619,
  /// Shader/Streaming Processor: GPR read
  HPC_GPU_ADRENO_A5XX_SP_GPR_READ = 2620,
  /// Shader/Streaming Processor: GPR write
  HPC_GPU_ADRENO_A5XX_SP_GPR_WRITE = 2621,
  /// Shader/Streaming Processor: LM ch0 requests
  HPC_GPU_ADRENO_A5XX_SP_LM_CH0_REQUESTS = 2622,
  /// Shader/Streaming Processor: LM ch1 requests
  HPC_GPU_ADRENO_A5XX_SP_LM_CH1_REQUESTS = 2623,
  /// Shader/Streaming Processor: LM bank conflicts
  HPC_GPU_ADRENO_A5XX_SP_LM_BANK_CONFLICTS = 2624,
  /// RB: busy cycles
  HPC_GPU_ADRENO_A5XX_RB_BUSY_CYCLES = 2816,
  /// RB: stall cycles CCU
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_CCU = 2817,
  /// RB: stall cycles HLSQ
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_HLSQ = 2818,
  /// RB: stall cycles fifo0 full
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_FIFO0_FULL = 2819,
  /// RB: stall cycles fifo1 full
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_FIFO1_FULL = 2820,
  /// RB: stall cycles fifo2 full
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_FIFO2_FULL = 2821,
  /// RB: starve cycles SP
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_SP = 2822,
  /// RB: starve cycles LRZ tile
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_LRZ_TILE = 2823,
  /// RB: starve cycles CCU
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_CCU = 2824,
  /// RB: starve cycles Z plane
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_Z_PLANE = 2825,
  /// RB: starve cycles bary plane
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_BARY_PLANE = 2826,
  /// RB: Z workload
  HPC_GPU_ADRENO_A5XX_RB_Z_WORKLOAD = 2827,
  /// RB: HLSQ active
  HPC_GPU_ADRENO_A5XX_RB_HLSQ_ACTIVE = 2828,
  /// RB: Z read
  HPC_GPU_ADRENO_A5XX_RB_Z_READ = 2829,
  /// RB: Z write
  HPC_GPU_ADRENO_A5XX_RB_Z_WRITE = 2830,
  /// RB: C read
  HPC_GPU_ADRENO_A5XX_RB_C_READ = 2831,
  /// RB: C write
  HPC_GPU_ADRENO_A5XX_RB_C_WRITE = 2832,
  /// RB: total pass
  HPC_GPU_ADRENO_A5XX_RB_TOTAL_PASS = 2833,
  /// RB: Z pass
  HPC_GPU_ADRENO_A5XX_RB_Z_PASS = 2834,
  /// RB: Z fail
  HPC_GPU_ADRENO_A5XX_RB_Z_FAIL = 2835,
  /// RB: S fail
  HPC_GPU_ADRENO_A5XX_RB_S_FAIL = 2836,
  /// RB: blended fxp components
  HPC_GPU_ADRENO_A5XX_RB_BLENDED_FXP_COMPONENTS = 2837,
  /// RB: blended fp16 components
  HPC_GPU_ADRENO_A5XX_RB_BLENDED_FP16_COMPONENTS = 2838,
  /// RB: reserved
  HPC_GPU_ADRENO_A5XX_RB_RESERVED = 2839,
  /// RB: 2D alive cycles
  HPC_GPU_ADRENO_A5XX_RB_2D_ALIVE_CYCLES = 2840,
  /// RB: 2D stall cycles a2d
  HPC_GPU_ADRENO_A5XX_RB_2D_STALL_CYCLES_A2D = 2841,
  /// RB: 2D starve cycles src
  HPC_GPU_ADRENO_A5XX_RB_2D_STARVE_CYCLES_SRC = 2842,
  /// RB: 2D starve cycles SP
  HPC_GPU_ADRENO_A5XX_RB_2D_STARVE_CYCLES_SP = 2843,
  /// RB: 2D starve cycles dst
  HPC_GPU_ADRENO_A5XX_RB_2D_STARVE_CYCLES_DST = 2844,
  /// RB: 2D valid pixels
  HPC_GPU_ADRENO_A5XX_RB_2D_VALID_PIXELS = 2845,
  /// VBIF: axi read requests ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_0 = 3328,
  /// VBIF: axi read requests ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_1 = 3329,
  /// VBIF: axi read requests ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_2 = 3330,
  /// VBIF: axi read requests ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_3 = 3331,
  /// VBIF: axi read requests ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_4 = 3332,
  /// VBIF: axi read requests ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_5 = 3333,
  /// VBIF: axi read requests ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_6 = 3334,
  /// VBIF: axi read requests ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_7 = 3335,
  /// VBIF: axi read requests ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_8 = 3336,
  /// VBIF: axi read requests ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_9 = 3337,
  /// VBIF: axi read requests ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_10 = 3338,
  /// VBIF: axi read requests ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_11 = 3339,
  /// VBIF: axi read requests ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_12 = 3340,
  /// VBIF: axi read requests ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_13 = 3341,
  /// VBIF: axi read requests ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_14 = 3342,
  /// VBIF: axi read requests ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_15 = 3343,
  /// VBIF: axi0 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_READ_REQUESTS_TOTAL = 3344,
  /// VBIF: axi1 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_READ_REQUESTS_TOTAL = 3345,
  /// VBIF: axi2 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_READ_REQUESTS_TOTAL = 3346,
  /// VBIF: axi3 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_READ_REQUESTS_TOTAL = 3347,
  /// VBIF: axi read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_TOTAL = 3348,
  /// VBIF: axi write requests ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_0 = 3349,
  /// VBIF: axi write requests ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_1 = 3350,
  /// VBIF: axi write requests ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_2 = 3351,
  /// VBIF: axi write requests ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_3 = 3352,
  /// VBIF: axi write requests ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_4 = 3353,
  /// VBIF: axi write requests ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_5 = 3354,
  /// VBIF: axi write requests ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_6 = 3355,
  /// VBIF: axi write requests ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_7 = 3356,
  /// VBIF: axi write requests ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_8 = 3357,
  /// VBIF: axi write requests ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_9 = 3358,
  /// VBIF: axi write requests ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_10 = 3359,
  /// VBIF: axi write requests ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_11 = 3360,
  /// VBIF: axi write requests ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_12 = 3361,
  /// VBIF: axi write requests ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_13 = 3362,
  /// VBIF: axi write requests ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_14 = 3363,
  /// VBIF: axi write requests ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_15 = 3364,
  /// VBIF: axi0 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_WRITE_REQUESTS_TOTAL = 3365,
  /// VBIF: axi1 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_WRITE_REQUESTS_TOTAL = 3366,
  /// VBIF: axi2 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_WRITE_REQUESTS_TOTAL = 3367,
  /// VBIF: axi3 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_WRITE_REQUESTS_TOTAL = 3368,
  /// VBIF: axi write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_TOTAL = 3369,
  /// VBIF: axi total requests
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_TOTAL_REQUESTS = 3370,
  /// VBIF: axi read data beats ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_0 = 3371,
  /// VBIF: axi read data beats ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_1 = 3372,
  /// VBIF: axi read data beats ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_2 = 3373,
  /// VBIF: axi read data beats ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_3 = 3374,
  /// VBIF: axi read data beats ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_4 = 3375,
  /// VBIF: axi read data beats ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_5 = 3376,
  /// VBIF: axi read data beats ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_6 = 3377,
  /// VBIF: axi read data beats ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_7 = 3378,
  /// VBIF: axi read data beats ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_8 = 3379,
  /// VBIF: axi read data beats ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_9 = 3380,
  /// VBIF: axi read data beats ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_10 = 3381,
  /// VBIF: axi read data beats ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_11 = 3382,
  /// VBIF: axi read data beats ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_12 = 3383,
  /// VBIF: axi read data beats ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_13 = 3384,
  /// VBIF: axi read data beats ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_14 = 3385,
  /// VBIF: axi read data beats ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_15 = 3386,
  /// VBIF: axi0 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_READ_DATA_BEATS_TOTAL = 3387,
  /// VBIF: axi1 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_READ_DATA_BEATS_TOTAL = 3388,
  /// VBIF: axi2 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_READ_DATA_BEATS_TOTAL = 3389,
  /// VBIF: axi3 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_READ_DATA_BEATS_TOTAL = 3390,
  /// VBIF: axi read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_TOTAL = 3391,
  /// VBIF: axi write data beats ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_0 = 3392,
  /// VBIF: axi write data beats ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_1 = 3393,
  /// VBIF: axi write data beats ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_2 = 3394,
  /// VBIF: axi write data beats ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_3 = 3395,
  /// VBIF: axi write data beats ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_4 = 3396,
  /// VBIF: axi write data beats ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_5 = 3397,
  /// VBIF: axi write data beats ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_6 = 3398,
  /// VBIF: axi write data beats ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_7 = 3399,
  /// VBIF: axi write data beats ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_8 = 3400,
  /// VBIF: axi write data beats ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_9 = 3401,
  /// VBIF: axi write data beats ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_10 = 3402,
  /// VBIF: axi write data beats ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_11 = 3403,
  /// VBIF: axi write data beats ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_12 = 3404,
  /// VBIF: axi write data beats ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_13 = 3405,
  /// VBIF: axi write data beats ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_14 = 3406,
  /// VBIF: axi write data beats ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_15 = 3407,
  /// VBIF: axi0 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_WRITE_DATA_BEATS_TOTAL = 3408,
  /// VBIF: axi1 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_WRITE_DATA_BEATS_TOTAL = 3409,
  /// VBIF: axi2 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_WRITE_DATA_BEATS_TOTAL = 3410,
  /// VBIF: axi3 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_WRITE_DATA_BEATS_TOTAL = 3411,
  /// VBIF: axi write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_TOTAL = 3412,
  /// VBIF: axi data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_DATA_BEATS_TOTAL = 3413,
  /// VSC: busy cycles
  HPC_GPU_ADRENO_A5XX_VSC_BUSY_CYCLES = 5888,
  /// VSC: working cycles
  HPC_GPU_ADRENO_A5XX_VSC_WORKING_CYCLES = 5889,
  /// VSC: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_VSC_STALL_CYCLES_UCHE = 5890,
  /// VSC: eot num
  HPC_GPU_ADRENO_A5XX_VSC_EOT_NUM = 5891,
  /// Cache and Compression Unit: busy cycles
  HPC_GPU_ADRENO_A5XX_CCU_BUSY_CYCLES = 6144,
  /// Cache and Compression Unit: stall cycles RB depth return
  HPC_GPU_ADRENO_A5XX_CCU_STALL_CYCLES_RB_DEPTH_RETURN = 6145,
  /// Cache and Compression Unit: stall cycles RB color return
  HPC_GPU_ADRENO_A5XX_CCU_STALL_CYCLES_RB_COLOR_RETURN = 6146,
  /// Cache and Compression Unit: starve cycles flag return
  HPC_GPU_ADRENO_A5XX_CCU_STARVE_CYCLES_FLAG_RETURN = 6147,
  /// Cache and Compression Unit: depth blocks
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_BLOCKS = 6148,
  /// Cache and Compression Unit: color blocks
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_BLOCKS = 6149,
  /// Cache and Compression Unit: depth block hit
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_BLOCK_HIT = 6150,
  /// Cache and Compression Unit: color block hit
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_BLOCK_HIT = 6151,
  /// Cache and Compression Unit: partial block read
  HPC_GPU_ADRENO_A5XX_CCU_PARTIAL_BLOCK_READ = 6152,
  /// Cache and Compression Unit: gmem read
  HPC_GPU_ADRENO_A5XX_CCU_GMEM_READ = 6153,
  /// Cache and Compression Unit: gmem write
  HPC_GPU_ADRENO_A5XX_CCU_GMEM_WRITE = 6154,
  /// Cache and Compression Unit: depth read flag0 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG0_COUNT = 6155,
  /// Cache and Compression Unit: depth read flag1 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG1_COUNT = 6156,
  /// Cache and Compression Unit: depth read flag2 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG2_COUNT = 6157,
  /// Cache and Compression Unit: depth read flag3 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG3_COUNT = 6158,
  /// Cache and Compression Unit: depth read flag4 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG4_COUNT = 6159,
  /// Cache and Compression Unit: color read flag0 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG0_COUNT = 6160,
  /// Cache and Compression Unit: color read flag1 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG1_COUNT = 6161,
  /// Cache and Compression Unit: color read flag2 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG2_COUNT = 6162,
  /// Cache and Compression Unit: color read flag3 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG3_COUNT = 6163,
  /// Cache and Compression Unit: color read flag4 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG4_COUNT = 6164,
  /// Cache and Compression Unit: 2D busy cycles
  HPC_GPU_ADRENO_A5XX_CCU_2D_BUSY_CYCLES = 6165,
  /// Cache and Compression Unit: 2D RD req
  HPC_GPU_ADRENO_A5XX_CCU_2D_RD_REQ = 6166,
  /// Cache and Compression Unit: 2D WR req
  HPC_GPU_ADRENO_A5XX_CCU_2D_WR_REQ = 6167,
  /// Cache and Compression Unit: 2D reorder starve cycles
  HPC_GPU_ADRENO_A5XX_CCU_2D_REORDER_STARVE_CYCLES = 6168,
  /// Cache and Compression Unit: 2D pixels
  HPC_GPU_ADRENO_A5XX_CCU_2D_PIXELS = 6169,
  /// Low Resolution Z: busy cycles
  HPC_GPU_ADRENO_A5XX_LRZ_BUSY_CYCLES = 6400,
  /// Low Resolution Z: starve cycles RAS
  HPC_GPU_ADRENO_A5XX_LRZ_STARVE_CYCLES_RAS = 6401,
  /// Low Resolution Z: stall cycles RB
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_RB = 6402,
  /// Low Resolution Z: stall cycles VSC
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_VSC = 6403,
  /// Low Resolution Z: stall cycles VPC
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_VPC = 6404,
  /// Low Resolution Z: stall cycles flag prefetch
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_FLAG_PREFETCH = 6405,
  /// Low Resolution Z: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_UCHE = 6406,
  /// Low Resolution Z: LRZ read
  HPC_GPU_ADRENO_A5XX_LRZ_LRZ_READ = 6407,
  /// Low Resolution Z: LRZ write
  HPC_GPU_ADRENO_A5XX_LRZ_LRZ_WRITE = 6408,
  /// Low Resolution Z: read latency
  HPC_GPU_ADRENO_A5XX_LRZ_READ_LATENCY = 6409,
  /// Low Resolution Z: merge cache updating
  HPC_GPU_ADRENO_A5XX_LRZ_MERGE_CACHE_UPDATING = 6410,
  /// Low Resolution Z: prim killed BY maskgen
  HPC_GPU_ADRENO_A5XX_LRZ_PRIM_KILLED_BY_MASKGEN = 6411,
  /// Low Resolution Z: prim killed BY LRZ
  HPC_GPU_ADRENO_A5XX_LRZ_PRIM_KILLED_BY_LRZ = 6412,
  /// Low Resolution Z: visible prim after LRZ
  HPC_GPU_ADRENO_A5XX_LRZ_VISIBLE_PRIM_AFTER_LRZ = 6413,
  /// Low Resolution Z: full 8x8 tiles
  HPC_GPU_ADRENO_A5XX_LRZ_FULL_8X8_TILES = 6414,
  /// Low Resolution Z: partial 8x8 tiles
  HPC_GPU_ADRENO_A5XX_LRZ_PARTIAL_8X8_TILES = 6415,
  /// Low Resolution Z: tile killed
  HPC_GPU_ADRENO_A5XX_LRZ_TILE_KILLED = 6416,
  /// Low Resolution Z: total pixel
  HPC_GPU_ADRENO_A5XX_LRZ_TOTAL_PIXEL = 6417,
  /// Low Resolution Z: visible pixel after LRZ
  HPC_GPU_ADRENO_A5XX_LRZ_VISIBLE_PIXEL_AFTER_LRZ = 6418,
  /// CMP: cmpdecmp stall cycles VBIF
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_STALL_CYCLES_VBIF = 6656,
  /// CMP: cmpdecmp VBIF latency cycles
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_LATENCY_CYCLES = 6657,
  /// CMP: cmpdecmp VBIF latency samples
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_LATENCY_SAMPLES = 6658,
  /// CMP: cmpdecmp VBIF read data CCU
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_READ_DATA_CCU = 6659,
  /// CMP: cmpdecmp VBIF write data CCU
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_WRITE_DATA_CCU = 6660,
  /// CMP: cmpdecmp VBIF read request
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_READ_REQUEST = 6661,
  /// CMP: cmpdecmp VBIF write request
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_WRITE_REQUEST = 6662,
  /// CMP: cmpdecmp VBIF read data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_READ_DATA = 6663,
  /// CMP: cmpdecmp VBIF write data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_WRITE_DATA = 6664,
  /// CMP: cmpdecmp flag fetch cycles
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_FLAG_FETCH_CYCLES = 6665,
  /// CMP: cmpdecmp flag fetch samples
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_FLAG_FETCH_SAMPLES = 6666,
  /// CMP: cmpdecmp depth write flag1 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG1_COUNT = 6667,
  /// CMP: cmpdecmp depth write flag2 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG2_COUNT = 6668,
  /// CMP: cmpdecmp depth write flag3 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG3_COUNT = 6669,
  /// CMP: cmpdecmp depth write flag4 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG4_COUNT = 6670,
  /// CMP: cmpdecmp color write flag1 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG1_COUNT = 6671,
  /// CMP: cmpdecmp color write flag2 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG2_COUNT = 6672,
  /// CMP: cmpdecmp color write flag3 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG3_COUNT = 6673,
  /// CMP: cmpdecmp color write flag4 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG4_COUNT = 6674,
  /// CMP: cmpdecmp 2D stall cycles VBIF req
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_REQ = 6675,
  /// CMP: cmpdecmp 2D stall cycles VBIF WR
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_WR = 6676,
  /// CMP: cmpdecmp 2D stall cycles VBIF return
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_RETURN = 6677,
  /// CMP: cmpdecmp 2D RD data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_RD_DATA = 6678,
  /// CMP: cmpdecmp 2D WR data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_WR_DATA = 6679,
} hpc_gpu_adreno_a5xx_counter_t;

//===--------------- END AUTOGENERATED REGION; DO NOT EDIT! ---------------===//

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  // HPC_GPU_ADRENO_A5XX_H_
