// AUTOGENERATED; DO NOT EDIT!

#ifndef HPC_GPU_ADRENO_A5XX_H_
#define HPC_GPU_ADRENO_A5XX_H_

typedef enum hpc_gpu_adreno_a5xx_perfcounter_e {
  // Cache and Compression Unit: busy cycles
  HPC_GPU_ADRENO_A5XX_CCU_BUSY_CYCLES = 0,
  // Cache and Compression Unit: stall cycles RB depth return
  HPC_GPU_ADRENO_A5XX_CCU_STALL_CYCLES_RB_DEPTH_RETURN = 1,
  // Cache and Compression Unit: stall cycles RB color return
  HPC_GPU_ADRENO_A5XX_CCU_STALL_CYCLES_RB_COLOR_RETURN = 2,
  // Cache and Compression Unit: starve cycles flag return
  HPC_GPU_ADRENO_A5XX_CCU_STARVE_CYCLES_FLAG_RETURN = 3,
  // Cache and Compression Unit: depth blocks
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_BLOCKS = 4,
  // Cache and Compression Unit: color blocks
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_BLOCKS = 5,
  // Cache and Compression Unit: depth block hit
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_BLOCK_HIT = 6,
  // Cache and Compression Unit: color block hit
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_BLOCK_HIT = 7,
  // Cache and Compression Unit: partial block read
  HPC_GPU_ADRENO_A5XX_CCU_PARTIAL_BLOCK_READ = 8,
  // Cache and Compression Unit: gmem read
  HPC_GPU_ADRENO_A5XX_CCU_GMEM_READ = 9,
  // Cache and Compression Unit: gmem write
  HPC_GPU_ADRENO_A5XX_CCU_GMEM_WRITE = 10,
  // Cache and Compression Unit: depth read flag0 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG0_COUNT = 11,
  // Cache and Compression Unit: depth read flag1 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG1_COUNT = 12,
  // Cache and Compression Unit: depth read flag2 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG2_COUNT = 13,
  // Cache and Compression Unit: depth read flag3 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG3_COUNT = 14,
  // Cache and Compression Unit: depth read flag4 count
  HPC_GPU_ADRENO_A5XX_CCU_DEPTH_READ_FLAG4_COUNT = 15,
  // Cache and Compression Unit: color read flag0 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG0_COUNT = 16,
  // Cache and Compression Unit: color read flag1 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG1_COUNT = 17,
  // Cache and Compression Unit: color read flag2 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG2_COUNT = 18,
  // Cache and Compression Unit: color read flag3 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG3_COUNT = 19,
  // Cache and Compression Unit: color read flag4 count
  HPC_GPU_ADRENO_A5XX_CCU_COLOR_READ_FLAG4_COUNT = 20,
  // Cache and Compression Unit: 2D busy cycles
  HPC_GPU_ADRENO_A5XX_CCU_2D_BUSY_CYCLES = 21,
  // Cache and Compression Unit: 2D RD req
  HPC_GPU_ADRENO_A5XX_CCU_2D_RD_REQ = 22,
  // Cache and Compression Unit: 2D WR req
  HPC_GPU_ADRENO_A5XX_CCU_2D_WR_REQ = 23,
  // Cache and Compression Unit: 2D reorder starve cycles
  HPC_GPU_ADRENO_A5XX_CCU_2D_REORDER_STARVE_CYCLES = 24,
  // Cache and Compression Unit: 2D pixels
  HPC_GPU_ADRENO_A5XX_CCU_2D_PIXELS = 25,
  // CMP: cmpdecmp stall cycles VBIF
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_STALL_CYCLES_VBIF = 256,
  // CMP: cmpdecmp VBIF latency cycles
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_LATENCY_CYCLES = 257,
  // CMP: cmpdecmp VBIF latency samples
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_LATENCY_SAMPLES = 258,
  // CMP: cmpdecmp VBIF read data CCU
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_READ_DATA_CCU = 259,
  // CMP: cmpdecmp VBIF write data CCU
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_WRITE_DATA_CCU = 260,
  // CMP: cmpdecmp VBIF read request
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_READ_REQUEST = 261,
  // CMP: cmpdecmp VBIF write request
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_WRITE_REQUEST = 262,
  // CMP: cmpdecmp VBIF read data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_READ_DATA = 263,
  // CMP: cmpdecmp VBIF write data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_VBIF_WRITE_DATA = 264,
  // CMP: cmpdecmp flag fetch cycles
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_FLAG_FETCH_CYCLES = 265,
  // CMP: cmpdecmp flag fetch samples
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_FLAG_FETCH_SAMPLES = 266,
  // CMP: cmpdecmp depth write flag1 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG1_COUNT = 267,
  // CMP: cmpdecmp depth write flag2 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG2_COUNT = 268,
  // CMP: cmpdecmp depth write flag3 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG3_COUNT = 269,
  // CMP: cmpdecmp depth write flag4 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG4_COUNT = 270,
  // CMP: cmpdecmp color write flag1 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG1_COUNT = 271,
  // CMP: cmpdecmp color write flag2 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG2_COUNT = 272,
  // CMP: cmpdecmp color write flag3 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG3_COUNT = 273,
  // CMP: cmpdecmp color write flag4 count
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_COLOR_WRITE_FLAG4_COUNT = 274,
  // CMP: cmpdecmp 2D stall cycles VBIF req
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_REQ = 275,
  // CMP: cmpdecmp 2D stall cycles VBIF WR
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_WR = 276,
  // CMP: cmpdecmp 2D stall cycles VBIF return
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_RETURN = 277,
  // CMP: cmpdecmp 2D RD data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_RD_DATA = 278,
  // CMP: cmpdecmp 2D WR data
  HPC_GPU_ADRENO_A5XX_CMP_CMPDECMP_2D_WR_DATA = 279,
  // Command Parser: always count
  HPC_GPU_ADRENO_A5XX_CP_ALWAYS_COUNT = 512,
  // Command Parser: busy gfx core idle
  HPC_GPU_ADRENO_A5XX_CP_BUSY_GFX_CORE_IDLE = 513,
  // Command Parser: busy cycles
  HPC_GPU_ADRENO_A5XX_CP_BUSY_CYCLES = 514,
  // Command Parser: pfp idle
  HPC_GPU_ADRENO_A5XX_CP_PFP_IDLE = 515,
  // Command Parser: pfp busy working
  HPC_GPU_ADRENO_A5XX_CP_PFP_BUSY_WORKING = 516,
  // Command Parser: pfp stall cycles any
  HPC_GPU_ADRENO_A5XX_CP_PFP_STALL_CYCLES_ANY = 517,
  // Command Parser: pfp starve cycles any
  HPC_GPU_ADRENO_A5XX_CP_PFP_STARVE_CYCLES_ANY = 518,
  // Command Parser: pfp icache miss
  HPC_GPU_ADRENO_A5XX_CP_PFP_ICACHE_MISS = 519,
  // Command Parser: pfp icache hit
  HPC_GPU_ADRENO_A5XX_CP_PFP_ICACHE_HIT = 520,
  // Command Parser: pfp match pm4 pkt profile
  HPC_GPU_ADRENO_A5XX_CP_PFP_MATCH_PM4_PKT_PROFILE = 521,
  // Command Parser: ME busy working
  HPC_GPU_ADRENO_A5XX_CP_ME_BUSY_WORKING = 522,
  // Command Parser: ME idle
  HPC_GPU_ADRENO_A5XX_CP_ME_IDLE = 523,
  // Command Parser: ME starve cycles any
  HPC_GPU_ADRENO_A5XX_CP_ME_STARVE_CYCLES_ANY = 524,
  // Command Parser: ME fifo empty pfp idle
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_EMPTY_PFP_IDLE = 525,
  // Command Parser: ME fifo empty pfp busy
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_EMPTY_PFP_BUSY = 526,
  // Command Parser: ME fifo full ME busy
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_FULL_ME_BUSY = 527,
  // Command Parser: ME fifo full ME non working
  HPC_GPU_ADRENO_A5XX_CP_ME_FIFO_FULL_ME_NON_WORKING = 528,
  // Command Parser: ME stall cycles any
  HPC_GPU_ADRENO_A5XX_CP_ME_STALL_CYCLES_ANY = 529,
  // Command Parser: ME icache miss
  HPC_GPU_ADRENO_A5XX_CP_ME_ICACHE_MISS = 530,
  // Command Parser: ME icache hit
  HPC_GPU_ADRENO_A5XX_CP_ME_ICACHE_HIT = 531,
  // Command Parser: num preemptions
  HPC_GPU_ADRENO_A5XX_CP_NUM_PREEMPTIONS = 532,
  // Command Parser: preemption reaction delay
  HPC_GPU_ADRENO_A5XX_CP_PREEMPTION_REACTION_DELAY = 533,
  // Command Parser: preemption switch out time
  HPC_GPU_ADRENO_A5XX_CP_PREEMPTION_SWITCH_OUT_TIME = 534,
  // Command Parser: preemption switch IN time
  HPC_GPU_ADRENO_A5XX_CP_PREEMPTION_SWITCH_IN_TIME = 535,
  // Command Parser: dead draws IN bin render
  HPC_GPU_ADRENO_A5XX_CP_DEAD_DRAWS_IN_BIN_RENDER = 536,
  // Command Parser: predicated draws killed
  HPC_GPU_ADRENO_A5XX_CP_PREDICATED_DRAWS_KILLED = 537,
  // Command Parser: mode switch
  HPC_GPU_ADRENO_A5XX_CP_MODE_SWITCH = 538,
  // Command Parser: zpass done
  HPC_GPU_ADRENO_A5XX_CP_ZPASS_DONE = 539,
  // Command Parser: context done
  HPC_GPU_ADRENO_A5XX_CP_CONTEXT_DONE = 540,
  // Command Parser: cache flush
  HPC_GPU_ADRENO_A5XX_CP_CACHE_FLUSH = 541,
  // Command Parser: long preemptions
  HPC_GPU_ADRENO_A5XX_CP_LONG_PREEMPTIONS = 542,
  // High Level SeQuencer: busy cycles
  HPC_GPU_ADRENO_A5XX_HLSQ_BUSY_CYCLES = 768,
  // High Level SeQuencer: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_HLSQ_STALL_CYCLES_UCHE = 769,
  // High Level SeQuencer: stall cycles SP state
  HPC_GPU_ADRENO_A5XX_HLSQ_STALL_CYCLES_SP_STATE = 770,
  // High Level SeQuencer: stall cycles SP FS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_STALL_CYCLES_SP_FS_STAGE = 771,
  // High Level SeQuencer: UCHE latency cycles
  HPC_GPU_ADRENO_A5XX_HLSQ_UCHE_LATENCY_CYCLES = 772,
  // High Level SeQuencer: UCHE latency count
  HPC_GPU_ADRENO_A5XX_HLSQ_UCHE_LATENCY_COUNT = 773,
  // High Level SeQuencer: FS stage 32 waves
  HPC_GPU_ADRENO_A5XX_HLSQ_FS_STAGE_32_WAVES = 774,
  // High Level SeQuencer: FS stage 64 waves
  HPC_GPU_ADRENO_A5XX_HLSQ_FS_STAGE_64_WAVES = 775,
  // High Level SeQuencer: quads
  HPC_GPU_ADRENO_A5XX_HLSQ_QUADS = 776,
  // High Level SeQuencer: SP state copy trans FS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_SP_STATE_COPY_TRANS_FS_STAGE = 777,
  // High Level SeQuencer: SP state copy trans VS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_SP_STATE_COPY_TRANS_VS_STAGE = 778,
  // High Level SeQuencer: TP state copy trans FS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_TP_STATE_COPY_TRANS_FS_STAGE = 779,
  // High Level SeQuencer: TP state copy trans VS stage
  HPC_GPU_ADRENO_A5XX_HLSQ_TP_STATE_COPY_TRANS_VS_STAGE = 780,
  // High Level SeQuencer: CS invocations
  HPC_GPU_ADRENO_A5XX_HLSQ_CS_INVOCATIONS = 781,
  // High Level SeQuencer: compute drawcalls
  HPC_GPU_ADRENO_A5XX_HLSQ_COMPUTE_DRAWCALLS = 782,
  // Low Resolution Z: busy cycles
  HPC_GPU_ADRENO_A5XX_LRZ_BUSY_CYCLES = 1024,
  // Low Resolution Z: starve cycles RAS
  HPC_GPU_ADRENO_A5XX_LRZ_STARVE_CYCLES_RAS = 1025,
  // Low Resolution Z: stall cycles RB
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_RB = 1026,
  // Low Resolution Z: stall cycles VSC
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_VSC = 1027,
  // Low Resolution Z: stall cycles VPC
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_VPC = 1028,
  // Low Resolution Z: stall cycles flag prefetch
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_FLAG_PREFETCH = 1029,
  // Low Resolution Z: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_LRZ_STALL_CYCLES_UCHE = 1030,
  // Low Resolution Z: LRZ read
  HPC_GPU_ADRENO_A5XX_LRZ_LRZ_READ = 1031,
  // Low Resolution Z: LRZ write
  HPC_GPU_ADRENO_A5XX_LRZ_LRZ_WRITE = 1032,
  // Low Resolution Z: read latency
  HPC_GPU_ADRENO_A5XX_LRZ_READ_LATENCY = 1033,
  // Low Resolution Z: merge cache updating
  HPC_GPU_ADRENO_A5XX_LRZ_MERGE_CACHE_UPDATING = 1034,
  // Low Resolution Z: prim killed BY maskgen
  HPC_GPU_ADRENO_A5XX_LRZ_PRIM_KILLED_BY_MASKGEN = 1035,
  // Low Resolution Z: prim killed BY LRZ
  HPC_GPU_ADRENO_A5XX_LRZ_PRIM_KILLED_BY_LRZ = 1036,
  // Low Resolution Z: visible prim after LRZ
  HPC_GPU_ADRENO_A5XX_LRZ_VISIBLE_PRIM_AFTER_LRZ = 1037,
  // Low Resolution Z: full 8x8 tiles
  HPC_GPU_ADRENO_A5XX_LRZ_FULL_8X8_TILES = 1038,
  // Low Resolution Z: partial 8x8 tiles
  HPC_GPU_ADRENO_A5XX_LRZ_PARTIAL_8X8_TILES = 1039,
  // Low Resolution Z: tile killed
  HPC_GPU_ADRENO_A5XX_LRZ_TILE_KILLED = 1040,
  // Low Resolution Z: total pixel
  HPC_GPU_ADRENO_A5XX_LRZ_TOTAL_PIXEL = 1041,
  // Low Resolution Z: visible pixel after LRZ
  HPC_GPU_ADRENO_A5XX_LRZ_VISIBLE_PIXEL_AFTER_LRZ = 1042,
  // PC: busy cycles
  HPC_GPU_ADRENO_A5XX_PC_BUSY_CYCLES = 1280,
  // PC: working cycles
  HPC_GPU_ADRENO_A5XX_PC_WORKING_CYCLES = 1281,
  // PC: stall cycles VFD
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_VFD = 1282,
  // PC: stall cycles TSE
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_TSE = 1283,
  // PC: stall cycles VPC
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_VPC = 1284,
  // PC: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_UCHE = 1285,
  // PC: stall cycles tess
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_TESS = 1286,
  // PC: stall cycles TSE only
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_TSE_ONLY = 1287,
  // PC: stall cycles VPC only
  HPC_GPU_ADRENO_A5XX_PC_STALL_CYCLES_VPC_ONLY = 1288,
  // PC: pass1 TF stall cycles
  HPC_GPU_ADRENO_A5XX_PC_PASS1_TF_STALL_CYCLES = 1289,
  // PC: starve cycles for index
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_INDEX = 1290,
  // PC: starve cycles for tess factor
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_TESS_FACTOR = 1291,
  // PC: starve cycles for viz stream
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_VIZ_STREAM = 1292,
  // PC: starve cycles for position
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_FOR_POSITION = 1293,
  // PC: starve cycles DI
  HPC_GPU_ADRENO_A5XX_PC_STARVE_CYCLES_DI = 1294,
  // PC: vis streams loaded
  HPC_GPU_ADRENO_A5XX_PC_VIS_STREAMS_LOADED = 1295,
  // PC: instances
  HPC_GPU_ADRENO_A5XX_PC_INSTANCES = 1296,
  // PC: VPC primitives
  HPC_GPU_ADRENO_A5XX_PC_VPC_PRIMITIVES = 1297,
  // PC: dead prim
  HPC_GPU_ADRENO_A5XX_PC_DEAD_PRIM = 1298,
  // PC: live prim
  HPC_GPU_ADRENO_A5XX_PC_LIVE_PRIM = 1299,
  // PC: vertex hits
  HPC_GPU_ADRENO_A5XX_PC_VERTEX_HITS = 1300,
  // PC: IA vertices
  HPC_GPU_ADRENO_A5XX_PC_IA_VERTICES = 1301,
  // PC: IA primitives
  HPC_GPU_ADRENO_A5XX_PC_IA_PRIMITIVES = 1302,
  // PC: GS primitives
  HPC_GPU_ADRENO_A5XX_PC_GS_PRIMITIVES = 1303,
  // PC: HS invocations
  HPC_GPU_ADRENO_A5XX_PC_HS_INVOCATIONS = 1304,
  // PC: DS invocations
  HPC_GPU_ADRENO_A5XX_PC_DS_INVOCATIONS = 1305,
  // PC: VS invocations
  HPC_GPU_ADRENO_A5XX_PC_VS_INVOCATIONS = 1306,
  // PC: GS invocations
  HPC_GPU_ADRENO_A5XX_PC_GS_INVOCATIONS = 1307,
  // PC: DS primitives
  HPC_GPU_ADRENO_A5XX_PC_DS_PRIMITIVES = 1308,
  // PC: VPC pos data transaction
  HPC_GPU_ADRENO_A5XX_PC_VPC_POS_DATA_TRANSACTION = 1309,
  // PC: 3D drawcalls
  HPC_GPU_ADRENO_A5XX_PC_3D_DRAWCALLS = 1310,
  // PC: 2D drawcalls
  HPC_GPU_ADRENO_A5XX_PC_2D_DRAWCALLS = 1311,
  // PC: non drawcall global events
  HPC_GPU_ADRENO_A5XX_PC_NON_DRAWCALL_GLOBAL_EVENTS = 1312,
  // PC: tess busy cycles
  HPC_GPU_ADRENO_A5XX_PC_TESS_BUSY_CYCLES = 1313,
  // PC: tess working cycles
  HPC_GPU_ADRENO_A5XX_PC_TESS_WORKING_CYCLES = 1314,
  // PC: tess stall cycles PC
  HPC_GPU_ADRENO_A5XX_PC_TESS_STALL_CYCLES_PC = 1315,
  // PC: tess starve cycles PC
  HPC_GPU_ADRENO_A5XX_PC_TESS_STARVE_CYCLES_PC = 1316,
  // RAS: busy cycles
  HPC_GPU_ADRENO_A5XX_RAS_BUSY_CYCLES = 1536,
  // RAS: supertile active cycles
  HPC_GPU_ADRENO_A5XX_RAS_SUPERTILE_ACTIVE_CYCLES = 1537,
  // RAS: stall cycles LRZ
  HPC_GPU_ADRENO_A5XX_RAS_STALL_CYCLES_LRZ = 1538,
  // RAS: starve cycles TSE
  HPC_GPU_ADRENO_A5XX_RAS_STARVE_CYCLES_TSE = 1539,
  // RAS: super tiles
  HPC_GPU_ADRENO_A5XX_RAS_SUPER_TILES = 1540,
  // RAS: 8x4 tiles
  HPC_GPU_ADRENO_A5XX_RAS_8X4_TILES = 1541,
  // RAS: maskgen active
  HPC_GPU_ADRENO_A5XX_RAS_MASKGEN_ACTIVE = 1542,
  // RAS: fully covered super tiles
  HPC_GPU_ADRENO_A5XX_RAS_FULLY_COVERED_SUPER_TILES = 1543,
  // RAS: fully covered 8x4 tiles
  HPC_GPU_ADRENO_A5XX_RAS_FULLY_COVERED_8X4_TILES = 1544,
  // RAS: prim killed invisilbe
  HPC_GPU_ADRENO_A5XX_RAS_PRIM_KILLED_INVISILBE = 1545,
  // RB: busy cycles
  HPC_GPU_ADRENO_A5XX_RB_BUSY_CYCLES = 1792,
  // RB: stall cycles CCU
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_CCU = 1793,
  // RB: stall cycles HLSQ
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_HLSQ = 1794,
  // RB: stall cycles fifo0 full
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_FIFO0_FULL = 1795,
  // RB: stall cycles fifo1 full
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_FIFO1_FULL = 1796,
  // RB: stall cycles fifo2 full
  HPC_GPU_ADRENO_A5XX_RB_STALL_CYCLES_FIFO2_FULL = 1797,
  // RB: starve cycles SP
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_SP = 1798,
  // RB: starve cycles LRZ tile
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_LRZ_TILE = 1799,
  // RB: starve cycles CCU
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_CCU = 1800,
  // RB: starve cycles Z plane
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_Z_PLANE = 1801,
  // RB: starve cycles bary plane
  HPC_GPU_ADRENO_A5XX_RB_STARVE_CYCLES_BARY_PLANE = 1802,
  // RB: Z workload
  HPC_GPU_ADRENO_A5XX_RB_Z_WORKLOAD = 1803,
  // RB: HLSQ active
  HPC_GPU_ADRENO_A5XX_RB_HLSQ_ACTIVE = 1804,
  // RB: Z read
  HPC_GPU_ADRENO_A5XX_RB_Z_READ = 1805,
  // RB: Z write
  HPC_GPU_ADRENO_A5XX_RB_Z_WRITE = 1806,
  // RB: C read
  HPC_GPU_ADRENO_A5XX_RB_C_READ = 1807,
  // RB: C write
  HPC_GPU_ADRENO_A5XX_RB_C_WRITE = 1808,
  // RB: total pass
  HPC_GPU_ADRENO_A5XX_RB_TOTAL_PASS = 1809,
  // RB: Z pass
  HPC_GPU_ADRENO_A5XX_RB_Z_PASS = 1810,
  // RB: Z fail
  HPC_GPU_ADRENO_A5XX_RB_Z_FAIL = 1811,
  // RB: S fail
  HPC_GPU_ADRENO_A5XX_RB_S_FAIL = 1812,
  // RB: blended fxp components
  HPC_GPU_ADRENO_A5XX_RB_BLENDED_FXP_COMPONENTS = 1813,
  // RB: blended fp16 components
  HPC_GPU_ADRENO_A5XX_RB_BLENDED_FP16_COMPONENTS = 1814,
  // RB: reserved
  HPC_GPU_ADRENO_A5XX_RB_RESERVED = 1815,
  // RB: 2D alive cycles
  HPC_GPU_ADRENO_A5XX_RB_2D_ALIVE_CYCLES = 1816,
  // RB: 2D stall cycles a2d
  HPC_GPU_ADRENO_A5XX_RB_2D_STALL_CYCLES_A2D = 1817,
  // RB: 2D starve cycles src
  HPC_GPU_ADRENO_A5XX_RB_2D_STARVE_CYCLES_SRC = 1818,
  // RB: 2D starve cycles SP
  HPC_GPU_ADRENO_A5XX_RB_2D_STARVE_CYCLES_SP = 1819,
  // RB: 2D starve cycles dst
  HPC_GPU_ADRENO_A5XX_RB_2D_STARVE_CYCLES_DST = 1820,
  // RB: 2D valid pixels
  HPC_GPU_ADRENO_A5XX_RB_2D_VALID_PIXELS = 1821,
  // RBBM: always count
  HPC_GPU_ADRENO_A5XX_RBBM_ALWAYS_COUNT = 2048,
  // RBBM: always ON
  HPC_GPU_ADRENO_A5XX_RBBM_ALWAYS_ON = 2049,
  // RBBM: TSE busy
  HPC_GPU_ADRENO_A5XX_RBBM_TSE_BUSY = 2050,
  // RBBM: RAS busy
  HPC_GPU_ADRENO_A5XX_RBBM_RAS_BUSY = 2051,
  // RBBM: PC dcall busy
  HPC_GPU_ADRENO_A5XX_RBBM_PC_DCALL_BUSY = 2052,
  // RBBM: PC vsd busy
  HPC_GPU_ADRENO_A5XX_RBBM_PC_VSD_BUSY = 2053,
  // RBBM: status masked
  HPC_GPU_ADRENO_A5XX_RBBM_STATUS_MASKED = 2054,
  // RBBM: com busy
  HPC_GPU_ADRENO_A5XX_RBBM_COM_BUSY = 2055,
  // RBBM: dcom busy
  HPC_GPU_ADRENO_A5XX_RBBM_DCOM_BUSY = 2056,
  // RBBM: VBIF busy
  HPC_GPU_ADRENO_A5XX_RBBM_VBIF_BUSY = 2057,
  // RBBM: VSC busy
  HPC_GPU_ADRENO_A5XX_RBBM_VSC_BUSY = 2058,
  // RBBM: tess busy
  HPC_GPU_ADRENO_A5XX_RBBM_TESS_BUSY = 2059,
  // RBBM: UCHE busy
  HPC_GPU_ADRENO_A5XX_RBBM_UCHE_BUSY = 2060,
  // RBBM: HLSQ busy
  HPC_GPU_ADRENO_A5XX_RBBM_HLSQ_BUSY = 2061,
  // RB_SAMPLES: total samples
  HPC_GPU_ADRENO_A5XX_RB_SAMPLES_TOTAL_SAMPLES = 2304,
  // RB_SAMPLES: zpass samples
  HPC_GPU_ADRENO_A5XX_RB_SAMPLES_ZPASS_SAMPLES = 2305,
  // RB_SAMPLES: zfail samples
  HPC_GPU_ADRENO_A5XX_RB_SAMPLES_ZFAIL_SAMPLES = 2306,
  // RB_SAMPLES: sfail samples
  HPC_GPU_ADRENO_A5XX_RB_SAMPLES_SFAIL_SAMPLES = 2307,
  // Shader/Streaming Processor: busy cycles
  HPC_GPU_ADRENO_A5XX_SP_BUSY_CYCLES = 2560,
  // Shader/Streaming Processor: ALU working cycles
  HPC_GPU_ADRENO_A5XX_SP_ALU_WORKING_CYCLES = 2561,
  // Shader/Streaming Processor: EFU working cycles
  HPC_GPU_ADRENO_A5XX_SP_EFU_WORKING_CYCLES = 2562,
  // Shader/Streaming Processor: stall cycles VPC
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_VPC = 2563,
  // Shader/Streaming Processor: stall cycles TP
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_TP = 2564,
  // Shader/Streaming Processor: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_UCHE = 2565,
  // Shader/Streaming Processor: stall cycles RB
  HPC_GPU_ADRENO_A5XX_SP_STALL_CYCLES_RB = 2566,
  // Shader/Streaming Processor: scheduler non working
  HPC_GPU_ADRENO_A5XX_SP_SCHEDULER_NON_WORKING = 2567,
  // Shader/Streaming Processor: wave contexts
  HPC_GPU_ADRENO_A5XX_SP_WAVE_CONTEXTS = 2568,
  // Shader/Streaming Processor: wave context cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_CONTEXT_CYCLES = 2569,
  // Shader/Streaming Processor: FS stage wave cycles
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_WAVE_CYCLES = 2570,
  // Shader/Streaming Processor: FS stage wave samples
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_WAVE_SAMPLES = 2571,
  // Shader/Streaming Processor: VS stage wave cycles
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_WAVE_CYCLES = 2572,
  // Shader/Streaming Processor: VS stage wave samples
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_WAVE_SAMPLES = 2573,
  // Shader/Streaming Processor: FS stage duration cycles
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_DURATION_CYCLES = 2574,
  // Shader/Streaming Processor: VS stage duration cycles
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_DURATION_CYCLES = 2575,
  // Shader/Streaming Processor: wave ctrl cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_CTRL_CYCLES = 2576,
  // Shader/Streaming Processor: wave load cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_LOAD_CYCLES = 2577,
  // Shader/Streaming Processor: wave emit cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_EMIT_CYCLES = 2578,
  // Shader/Streaming Processor: wave nop cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_NOP_CYCLES = 2579,
  // Shader/Streaming Processor: wave wait cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_WAIT_CYCLES = 2580,
  // Shader/Streaming Processor: wave fetch cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_FETCH_CYCLES = 2581,
  // Shader/Streaming Processor: wave idle cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_IDLE_CYCLES = 2582,
  // Shader/Streaming Processor: wave end cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_END_CYCLES = 2583,
  // Shader/Streaming Processor: wave long sync cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_LONG_SYNC_CYCLES = 2584,
  // Shader/Streaming Processor: wave short sync cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_SHORT_SYNC_CYCLES = 2585,
  // Shader/Streaming Processor: wave join cycles
  HPC_GPU_ADRENO_A5XX_SP_WAVE_JOIN_CYCLES = 2586,
  // Shader/Streaming Processor: LM load instructions
  HPC_GPU_ADRENO_A5XX_SP_LM_LOAD_INSTRUCTIONS = 2587,
  // Shader/Streaming Processor: LM store instructions
  HPC_GPU_ADRENO_A5XX_SP_LM_STORE_INSTRUCTIONS = 2588,
  // Shader/Streaming Processor: LM atomics
  HPC_GPU_ADRENO_A5XX_SP_LM_ATOMICS = 2589,
  // Shader/Streaming Processor: GM load instructions
  HPC_GPU_ADRENO_A5XX_SP_GM_LOAD_INSTRUCTIONS = 2590,
  // Shader/Streaming Processor: GM store instructions
  HPC_GPU_ADRENO_A5XX_SP_GM_STORE_INSTRUCTIONS = 2591,
  // Shader/Streaming Processor: GM atomics
  HPC_GPU_ADRENO_A5XX_SP_GM_ATOMICS = 2592,
  // Shader/Streaming Processor: VS stage tex instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_TEX_INSTRUCTIONS = 2593,
  // Shader/Streaming Processor: VS stage cflow instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_CFLOW_INSTRUCTIONS = 2594,
  // Shader/Streaming Processor: VS stage EFU instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_EFU_INSTRUCTIONS = 2595,
  // Shader/Streaming Processor: VS stage full ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_FULL_ALU_INSTRUCTIONS = 2596,
  // Shader/Streaming Processor: VS stage half ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_STAGE_HALF_ALU_INSTRUCTIONS = 2597,
  // Shader/Streaming Processor: FS stage tex instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_TEX_INSTRUCTIONS = 2598,
  // Shader/Streaming Processor: FS stage cflow instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_CFLOW_INSTRUCTIONS = 2599,
  // Shader/Streaming Processor: FS stage EFU instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_EFU_INSTRUCTIONS = 2600,
  // Shader/Streaming Processor: FS stage full ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_FULL_ALU_INSTRUCTIONS = 2601,
  // Shader/Streaming Processor: FS stage half ALU instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_HALF_ALU_INSTRUCTIONS = 2602,
  // Shader/Streaming Processor: FS stage bary instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_STAGE_BARY_INSTRUCTIONS = 2603,
  // Shader/Streaming Processor: VS instructions
  HPC_GPU_ADRENO_A5XX_SP_VS_INSTRUCTIONS = 2604,
  // Shader/Streaming Processor: FS instructions
  HPC_GPU_ADRENO_A5XX_SP_FS_INSTRUCTIONS = 2605,
  // Shader/Streaming Processor: addr lock count
  HPC_GPU_ADRENO_A5XX_SP_ADDR_LOCK_COUNT = 2606,
  // Shader/Streaming Processor: UCHE read trans
  HPC_GPU_ADRENO_A5XX_SP_UCHE_READ_TRANS = 2607,
  // Shader/Streaming Processor: UCHE write trans
  HPC_GPU_ADRENO_A5XX_SP_UCHE_WRITE_TRANS = 2608,
  // Shader/Streaming Processor: export VPC trans
  HPC_GPU_ADRENO_A5XX_SP_EXPORT_VPC_TRANS = 2609,
  // Shader/Streaming Processor: export RB trans
  HPC_GPU_ADRENO_A5XX_SP_EXPORT_RB_TRANS = 2610,
  // Shader/Streaming Processor: pixels killed
  HPC_GPU_ADRENO_A5XX_SP_PIXELS_KILLED = 2611,
  // Shader/Streaming Processor: icl1 requests
  HPC_GPU_ADRENO_A5XX_SP_ICL1_REQUESTS = 2612,
  // Shader/Streaming Processor: icl1 misses
  HPC_GPU_ADRENO_A5XX_SP_ICL1_MISSES = 2613,
  // Shader/Streaming Processor: icl0 requests
  HPC_GPU_ADRENO_A5XX_SP_ICL0_REQUESTS = 2614,
  // Shader/Streaming Processor: icl0 misses
  HPC_GPU_ADRENO_A5XX_SP_ICL0_MISSES = 2615,
  // Shader/Streaming Processor: HS instructions
  HPC_GPU_ADRENO_A5XX_SP_HS_INSTRUCTIONS = 2616,
  // Shader/Streaming Processor: DS instructions
  HPC_GPU_ADRENO_A5XX_SP_DS_INSTRUCTIONS = 2617,
  // Shader/Streaming Processor: GS instructions
  HPC_GPU_ADRENO_A5XX_SP_GS_INSTRUCTIONS = 2618,
  // Shader/Streaming Processor: CS instructions
  HPC_GPU_ADRENO_A5XX_SP_CS_INSTRUCTIONS = 2619,
  // Shader/Streaming Processor: GPR read
  HPC_GPU_ADRENO_A5XX_SP_GPR_READ = 2620,
  // Shader/Streaming Processor: GPR write
  HPC_GPU_ADRENO_A5XX_SP_GPR_WRITE = 2621,
  // Shader/Streaming Processor: LM ch0 requests
  HPC_GPU_ADRENO_A5XX_SP_LM_CH0_REQUESTS = 2622,
  // Shader/Streaming Processor: LM ch1 requests
  HPC_GPU_ADRENO_A5XX_SP_LM_CH1_REQUESTS = 2623,
  // Shader/Streaming Processor: LM bank conflicts
  HPC_GPU_ADRENO_A5XX_SP_LM_BANK_CONFLICTS = 2624,
  // Texture Processor: busy cycles
  HPC_GPU_ADRENO_A5XX_TP_BUSY_CYCLES = 2816,
  // Texture Processor: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_TP_STALL_CYCLES_UCHE = 2817,
  // Texture Processor: latency cycles
  HPC_GPU_ADRENO_A5XX_TP_LATENCY_CYCLES = 2818,
  // Texture Processor: latency trans
  HPC_GPU_ADRENO_A5XX_TP_LATENCY_TRANS = 2819,
  // Texture Processor: flag cache request samples
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_REQUEST_SAMPLES = 2820,
  // Texture Processor: flag cache request latency
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_REQUEST_LATENCY = 2821,
  // Texture Processor: L1 cacheline requests
  HPC_GPU_ADRENO_A5XX_TP_L1_CACHELINE_REQUESTS = 2822,
  // Texture Processor: L1 cacheline misses
  HPC_GPU_ADRENO_A5XX_TP_L1_CACHELINE_MISSES = 2823,
  // Texture Processor: SP TP trans
  HPC_GPU_ADRENO_A5XX_TP_SP_TP_TRANS = 2824,
  // Texture Processor: TP SP trans
  HPC_GPU_ADRENO_A5XX_TP_TP_SP_TRANS = 2825,
  // Texture Processor: output pixels
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS = 2826,
  // Texture Processor: filter workload 16bit
  HPC_GPU_ADRENO_A5XX_TP_FILTER_WORKLOAD_16BIT = 2827,
  // Texture Processor: filter workload 32bit
  HPC_GPU_ADRENO_A5XX_TP_FILTER_WORKLOAD_32BIT = 2828,
  // Texture Processor: quads received
  HPC_GPU_ADRENO_A5XX_TP_QUADS_RECEIVED = 2829,
  // Texture Processor: quads offset
  HPC_GPU_ADRENO_A5XX_TP_QUADS_OFFSET = 2830,
  // Texture Processor: quads shadow
  HPC_GPU_ADRENO_A5XX_TP_QUADS_SHADOW = 2831,
  // Texture Processor: quads array
  HPC_GPU_ADRENO_A5XX_TP_QUADS_ARRAY = 2832,
  // Texture Processor: quads gradient
  HPC_GPU_ADRENO_A5XX_TP_QUADS_GRADIENT = 2833,
  // Texture Processor: quads 1D
  HPC_GPU_ADRENO_A5XX_TP_QUADS_1D = 2834,
  // Texture Processor: quads 2D
  HPC_GPU_ADRENO_A5XX_TP_QUADS_2D = 2835,
  // Texture Processor: quads buffer
  HPC_GPU_ADRENO_A5XX_TP_QUADS_BUFFER = 2836,
  // Texture Processor: quads 3D
  HPC_GPU_ADRENO_A5XX_TP_QUADS_3D = 2837,
  // Texture Processor: quads cube
  HPC_GPU_ADRENO_A5XX_TP_QUADS_CUBE = 2838,
  // Texture Processor: state cache requests
  HPC_GPU_ADRENO_A5XX_TP_STATE_CACHE_REQUESTS = 2839,
  // Texture Processor: state cache misses
  HPC_GPU_ADRENO_A5XX_TP_STATE_CACHE_MISSES = 2840,
  // Texture Processor: divergent quads received
  HPC_GPU_ADRENO_A5XX_TP_DIVERGENT_QUADS_RECEIVED = 2841,
  // Texture Processor: bindless state cache requests
  HPC_GPU_ADRENO_A5XX_TP_BINDLESS_STATE_CACHE_REQUESTS = 2842,
  // Texture Processor: bindless state cache misses
  HPC_GPU_ADRENO_A5XX_TP_BINDLESS_STATE_CACHE_MISSES = 2843,
  // Texture Processor: prt non resident events
  HPC_GPU_ADRENO_A5XX_TP_PRT_NON_RESIDENT_EVENTS = 2844,
  // Texture Processor: output pixels point
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_POINT = 2845,
  // Texture Processor: output pixels bilinear
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_BILINEAR = 2846,
  // Texture Processor: output pixels mip
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_MIP = 2847,
  // Texture Processor: output pixels aniso
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_ANISO = 2848,
  // Texture Processor: output pixels zero lod
  HPC_GPU_ADRENO_A5XX_TP_OUTPUT_PIXELS_ZERO_LOD = 2849,
  // Texture Processor: flag cache requests
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_REQUESTS = 2850,
  // Texture Processor: flag cache misses
  HPC_GPU_ADRENO_A5XX_TP_FLAG_CACHE_MISSES = 2851,
  // Texture Processor: L1 5 L2 requests
  HPC_GPU_ADRENO_A5XX_TP_L1_5_L2_REQUESTS = 2852,
  // Texture Processor: 2D output pixels
  HPC_GPU_ADRENO_A5XX_TP_2D_OUTPUT_PIXELS = 2853,
  // Texture Processor: 2D output pixels point
  HPC_GPU_ADRENO_A5XX_TP_2D_OUTPUT_PIXELS_POINT = 2854,
  // Texture Processor: 2D output pixels bilinear
  HPC_GPU_ADRENO_A5XX_TP_2D_OUTPUT_PIXELS_BILINEAR = 2855,
  // Texture Processor: 2D filter workload 16bit
  HPC_GPU_ADRENO_A5XX_TP_2D_FILTER_WORKLOAD_16BIT = 2856,
  // Texture Processor: 2D filter workload 32bit
  HPC_GPU_ADRENO_A5XX_TP_2D_FILTER_WORKLOAD_32BIT = 2857,
  // Triangle Setup Engine: busy cycles
  HPC_GPU_ADRENO_A5XX_TSE_BUSY_CYCLES = 3072,
  // Triangle Setup Engine: clipping cycles
  HPC_GPU_ADRENO_A5XX_TSE_CLIPPING_CYCLES = 3073,
  // Triangle Setup Engine: stall cycles RAS
  HPC_GPU_ADRENO_A5XX_TSE_STALL_CYCLES_RAS = 3074,
  // Triangle Setup Engine: stall cycles LRZ baryplane
  HPC_GPU_ADRENO_A5XX_TSE_STALL_CYCLES_LRZ_BARYPLANE = 3075,
  // Triangle Setup Engine: stall cycles LRZ zplane
  HPC_GPU_ADRENO_A5XX_TSE_STALL_CYCLES_LRZ_ZPLANE = 3076,
  // Triangle Setup Engine: starve cycles PC
  HPC_GPU_ADRENO_A5XX_TSE_STARVE_CYCLES_PC = 3077,
  // Triangle Setup Engine: input prim
  HPC_GPU_ADRENO_A5XX_TSE_INPUT_PRIM = 3078,
  // Triangle Setup Engine: input null prim
  HPC_GPU_ADRENO_A5XX_TSE_INPUT_NULL_PRIM = 3079,
  // Triangle Setup Engine: trival rej prim
  HPC_GPU_ADRENO_A5XX_TSE_TRIVAL_REJ_PRIM = 3080,
  // Triangle Setup Engine: clipped prim
  HPC_GPU_ADRENO_A5XX_TSE_CLIPPED_PRIM = 3081,
  // Triangle Setup Engine: zero area prim
  HPC_GPU_ADRENO_A5XX_TSE_ZERO_AREA_PRIM = 3082,
  // Triangle Setup Engine: faceness culled prim
  HPC_GPU_ADRENO_A5XX_TSE_FACENESS_CULLED_PRIM = 3083,
  // Triangle Setup Engine: zero pixel prim
  HPC_GPU_ADRENO_A5XX_TSE_ZERO_PIXEL_PRIM = 3084,
  // Triangle Setup Engine: output null prim
  HPC_GPU_ADRENO_A5XX_TSE_OUTPUT_NULL_PRIM = 3085,
  // Triangle Setup Engine: output visible prim
  HPC_GPU_ADRENO_A5XX_TSE_OUTPUT_VISIBLE_PRIM = 3086,
  // Triangle Setup Engine: cinvocation
  HPC_GPU_ADRENO_A5XX_TSE_CINVOCATION = 3087,
  // Triangle Setup Engine: cprimitives
  HPC_GPU_ADRENO_A5XX_TSE_CPRIMITIVES = 3088,
  // Triangle Setup Engine: 2D input prim
  HPC_GPU_ADRENO_A5XX_TSE_2D_INPUT_PRIM = 3089,
  // Triangle Setup Engine: 2D alive clcles
  HPC_GPU_ADRENO_A5XX_TSE_2D_ALIVE_CLCLES = 3090,
  // Unified L2 Cache: busy cycles
  HPC_GPU_ADRENO_A5XX_UCHE_BUSY_CYCLES = 3328,
  // Unified L2 Cache: stall cycles VBIF
  HPC_GPU_ADRENO_A5XX_UCHE_STALL_CYCLES_VBIF = 3329,
  // Unified L2 Cache: VBIF latency cycles
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_LATENCY_CYCLES = 3330,
  // Unified L2 Cache: VBIF latency samples
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_LATENCY_SAMPLES = 3331,
  // Unified L2 Cache: VBIF read beats TP
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_TP = 3332,
  // Unified L2 Cache: VBIF read beats VFD
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_VFD = 3333,
  // Unified L2 Cache: VBIF read beats HLSQ
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_HLSQ = 3334,
  // Unified L2 Cache: VBIF read beats LRZ
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_LRZ = 3335,
  // Unified L2 Cache: VBIF read beats SP
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_SP = 3336,
  // Unified L2 Cache: read requests TP
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_TP = 3337,
  // Unified L2 Cache: read requests VFD
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_VFD = 3338,
  // Unified L2 Cache: read requests HLSQ
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_HLSQ = 3339,
  // Unified L2 Cache: read requests LRZ
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_LRZ = 3340,
  // Unified L2 Cache: read requests SP
  HPC_GPU_ADRENO_A5XX_UCHE_READ_REQUESTS_SP = 3341,
  // Unified L2 Cache: write requests LRZ
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_LRZ = 3342,
  // Unified L2 Cache: write requests SP
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_SP = 3343,
  // Unified L2 Cache: write requests VPC
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_VPC = 3344,
  // Unified L2 Cache: write requests VSC
  HPC_GPU_ADRENO_A5XX_UCHE_WRITE_REQUESTS_VSC = 3345,
  // Unified L2 Cache: evicts
  HPC_GPU_ADRENO_A5XX_UCHE_EVICTS = 3346,
  // Unified L2 Cache: bank req0
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ0 = 3347,
  // Unified L2 Cache: bank req1
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ1 = 3348,
  // Unified L2 Cache: bank req2
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ2 = 3349,
  // Unified L2 Cache: bank req3
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ3 = 3350,
  // Unified L2 Cache: bank req4
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ4 = 3351,
  // Unified L2 Cache: bank req5
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ5 = 3352,
  // Unified L2 Cache: bank req6
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ6 = 3353,
  // Unified L2 Cache: bank req7
  HPC_GPU_ADRENO_A5XX_UCHE_BANK_REQ7 = 3354,
  // Unified L2 Cache: VBIF read beats ch0
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_CH0 = 3355,
  // Unified L2 Cache: VBIF read beats ch1
  HPC_GPU_ADRENO_A5XX_UCHE_VBIF_READ_BEATS_CH1 = 3356,
  // Unified L2 Cache: gmem read beats
  HPC_GPU_ADRENO_A5XX_UCHE_GMEM_READ_BEATS = 3357,
  // Unified L2 Cache: flag count
  HPC_GPU_ADRENO_A5XX_UCHE_FLAG_COUNT = 3358,
  // VBIF: axi read requests ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_0 = 3584,
  // VBIF: axi read requests ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_1 = 3585,
  // VBIF: axi read requests ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_2 = 3586,
  // VBIF: axi read requests ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_3 = 3587,
  // VBIF: axi read requests ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_4 = 3588,
  // VBIF: axi read requests ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_5 = 3589,
  // VBIF: axi read requests ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_6 = 3590,
  // VBIF: axi read requests ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_7 = 3591,
  // VBIF: axi read requests ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_8 = 3592,
  // VBIF: axi read requests ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_9 = 3593,
  // VBIF: axi read requests ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_10 = 3594,
  // VBIF: axi read requests ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_11 = 3595,
  // VBIF: axi read requests ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_12 = 3596,
  // VBIF: axi read requests ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_13 = 3597,
  // VBIF: axi read requests ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_14 = 3598,
  // VBIF: axi read requests ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_ID_15 = 3599,
  // VBIF: axi0 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_READ_REQUESTS_TOTAL = 3600,
  // VBIF: axi1 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_READ_REQUESTS_TOTAL = 3601,
  // VBIF: axi2 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_READ_REQUESTS_TOTAL = 3602,
  // VBIF: axi3 read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_READ_REQUESTS_TOTAL = 3603,
  // VBIF: axi read requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_REQUESTS_TOTAL = 3604,
  // VBIF: axi write requests ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_0 = 3605,
  // VBIF: axi write requests ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_1 = 3606,
  // VBIF: axi write requests ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_2 = 3607,
  // VBIF: axi write requests ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_3 = 3608,
  // VBIF: axi write requests ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_4 = 3609,
  // VBIF: axi write requests ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_5 = 3610,
  // VBIF: axi write requests ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_6 = 3611,
  // VBIF: axi write requests ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_7 = 3612,
  // VBIF: axi write requests ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_8 = 3613,
  // VBIF: axi write requests ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_9 = 3614,
  // VBIF: axi write requests ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_10 = 3615,
  // VBIF: axi write requests ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_11 = 3616,
  // VBIF: axi write requests ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_12 = 3617,
  // VBIF: axi write requests ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_13 = 3618,
  // VBIF: axi write requests ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_14 = 3619,
  // VBIF: axi write requests ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_ID_15 = 3620,
  // VBIF: axi0 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_WRITE_REQUESTS_TOTAL = 3621,
  // VBIF: axi1 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_WRITE_REQUESTS_TOTAL = 3622,
  // VBIF: axi2 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_WRITE_REQUESTS_TOTAL = 3623,
  // VBIF: axi3 write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_WRITE_REQUESTS_TOTAL = 3624,
  // VBIF: axi write requests total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_REQUESTS_TOTAL = 3625,
  // VBIF: axi total requests
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_TOTAL_REQUESTS = 3626,
  // VBIF: axi read data beats ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_0 = 3627,
  // VBIF: axi read data beats ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_1 = 3628,
  // VBIF: axi read data beats ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_2 = 3629,
  // VBIF: axi read data beats ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_3 = 3630,
  // VBIF: axi read data beats ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_4 = 3631,
  // VBIF: axi read data beats ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_5 = 3632,
  // VBIF: axi read data beats ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_6 = 3633,
  // VBIF: axi read data beats ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_7 = 3634,
  // VBIF: axi read data beats ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_8 = 3635,
  // VBIF: axi read data beats ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_9 = 3636,
  // VBIF: axi read data beats ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_10 = 3637,
  // VBIF: axi read data beats ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_11 = 3638,
  // VBIF: axi read data beats ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_12 = 3639,
  // VBIF: axi read data beats ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_13 = 3640,
  // VBIF: axi read data beats ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_14 = 3641,
  // VBIF: axi read data beats ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_ID_15 = 3642,
  // VBIF: axi0 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_READ_DATA_BEATS_TOTAL = 3643,
  // VBIF: axi1 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_READ_DATA_BEATS_TOTAL = 3644,
  // VBIF: axi2 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_READ_DATA_BEATS_TOTAL = 3645,
  // VBIF: axi3 read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_READ_DATA_BEATS_TOTAL = 3646,
  // VBIF: axi read data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_READ_DATA_BEATS_TOTAL = 3647,
  // VBIF: axi write data beats ID 0
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_0 = 3648,
  // VBIF: axi write data beats ID 1
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_1 = 3649,
  // VBIF: axi write data beats ID 2
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_2 = 3650,
  // VBIF: axi write data beats ID 3
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_3 = 3651,
  // VBIF: axi write data beats ID 4
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_4 = 3652,
  // VBIF: axi write data beats ID 5
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_5 = 3653,
  // VBIF: axi write data beats ID 6
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_6 = 3654,
  // VBIF: axi write data beats ID 7
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_7 = 3655,
  // VBIF: axi write data beats ID 8
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_8 = 3656,
  // VBIF: axi write data beats ID 9
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_9 = 3657,
  // VBIF: axi write data beats ID 10
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_10 = 3658,
  // VBIF: axi write data beats ID 11
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_11 = 3659,
  // VBIF: axi write data beats ID 12
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_12 = 3660,
  // VBIF: axi write data beats ID 13
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_13 = 3661,
  // VBIF: axi write data beats ID 14
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_14 = 3662,
  // VBIF: axi write data beats ID 15
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_ID_15 = 3663,
  // VBIF: axi0 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI0_WRITE_DATA_BEATS_TOTAL = 3664,
  // VBIF: axi1 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI1_WRITE_DATA_BEATS_TOTAL = 3665,
  // VBIF: axi2 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI2_WRITE_DATA_BEATS_TOTAL = 3666,
  // VBIF: axi3 write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI3_WRITE_DATA_BEATS_TOTAL = 3667,
  // VBIF: axi write data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_WRITE_DATA_BEATS_TOTAL = 3668,
  // VBIF: axi data beats total
  HPC_GPU_ADRENO_A5XX_VBIF_AXI_DATA_BEATS_TOTAL = 3669,
  // VFD: busy cycles
  HPC_GPU_ADRENO_A5XX_VFD_BUSY_CYCLES = 3840,
  // VFD: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_UCHE = 3841,
  // VFD: stall cycles VPC alloc
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_VPC_ALLOC = 3842,
  // VFD: stall cycles miss VB
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_MISS_VB = 3843,
  // VFD: stall cycles miss Q
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_MISS_Q = 3844,
  // VFD: stall cycles SP info
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_SP_INFO = 3845,
  // VFD: stall cycles SP attr
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_SP_ATTR = 3846,
  // VFD: stall cycles vfdp VB
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_VFDP_VB = 3847,
  // VFD: stall cycles vfdp Q
  HPC_GPU_ADRENO_A5XX_VFD_STALL_CYCLES_VFDP_Q = 3848,
  // VFD: decoder packer stall
  HPC_GPU_ADRENO_A5XX_VFD_DECODER_PACKER_STALL = 3849,
  // VFD: starve cycles UCHE
  HPC_GPU_ADRENO_A5XX_VFD_STARVE_CYCLES_UCHE = 3850,
  // VFD: rbuffer full
  HPC_GPU_ADRENO_A5XX_VFD_RBUFFER_FULL = 3851,
  // VFD: attr info fifo full
  HPC_GPU_ADRENO_A5XX_VFD_ATTR_INFO_FIFO_FULL = 3852,
  // VFD: decoded attribute bytes
  HPC_GPU_ADRENO_A5XX_VFD_DECODED_ATTRIBUTE_BYTES = 3853,
  // VFD: num attributes
  HPC_GPU_ADRENO_A5XX_VFD_NUM_ATTRIBUTES = 3854,
  // VFD: instructions
  HPC_GPU_ADRENO_A5XX_VFD_INSTRUCTIONS = 3855,
  // VFD: upper shader fibers
  HPC_GPU_ADRENO_A5XX_VFD_UPPER_SHADER_FIBERS = 3856,
  // VFD: lower shader fibers
  HPC_GPU_ADRENO_A5XX_VFD_LOWER_SHADER_FIBERS = 3857,
  // VFD: mode 0 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_0_FIBERS = 3858,
  // VFD: mode 1 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_1_FIBERS = 3859,
  // VFD: mode 2 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_2_FIBERS = 3860,
  // VFD: mode 3 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_3_FIBERS = 3861,
  // VFD: mode 4 fibers
  HPC_GPU_ADRENO_A5XX_VFD_MODE_4_FIBERS = 3862,
  // VFD: total vertices
  HPC_GPU_ADRENO_A5XX_VFD_TOTAL_VERTICES = 3863,
  // VFD: num attr miss
  HPC_GPU_ADRENO_A5XX_VFD_NUM_ATTR_MISS = 3864,
  // VFD: 1 burst req
  HPC_GPU_ADRENO_A5XX_VFD_1_BURST_REQ = 3865,
  // VFD: vfdp stall cycles VFD
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STALL_CYCLES_VFD = 3866,
  // VFD: vfdp stall cycles VFD index
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STALL_CYCLES_VFD_INDEX = 3867,
  // VFD: vfdp stall cycles VFD prog
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STALL_CYCLES_VFD_PROG = 3868,
  // VFD: vfdp starve cycles PC
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_STARVE_CYCLES_PC = 3869,
  // VFD: vfdp VS stage 32 waves
  HPC_GPU_ADRENO_A5XX_VFD_VFDP_VS_STAGE_32_WAVES = 3870,
  // VPC: busy cycles
  HPC_GPU_ADRENO_A5XX_VPC_BUSY_CYCLES = 4096,
  // VPC: working cycles
  HPC_GPU_ADRENO_A5XX_VPC_WORKING_CYCLES = 4097,
  // VPC: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_UCHE = 4098,
  // VPC: stall cycles VFD wack
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_VFD_WACK = 4099,
  // VPC: stall cycles HLSQ prim alloc
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_HLSQ_PRIM_ALLOC = 4100,
  // VPC: stall cycles PC
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_PC = 4101,
  // VPC: stall cycles SP LM
  HPC_GPU_ADRENO_A5XX_VPC_STALL_CYCLES_SP_LM = 4102,
  // VPC: pos export stall cycles
  HPC_GPU_ADRENO_A5XX_VPC_POS_EXPORT_STALL_CYCLES = 4103,
  // VPC: starve cycles SP
  HPC_GPU_ADRENO_A5XX_VPC_STARVE_CYCLES_SP = 4104,
  // VPC: starve cycles LRZ
  HPC_GPU_ADRENO_A5XX_VPC_STARVE_CYCLES_LRZ = 4105,
  // VPC: PC primitives
  HPC_GPU_ADRENO_A5XX_VPC_PC_PRIMITIVES = 4106,
  // VPC: SP components
  HPC_GPU_ADRENO_A5XX_VPC_SP_COMPONENTS = 4107,
  // VPC: SP LM primitives
  HPC_GPU_ADRENO_A5XX_VPC_SP_LM_PRIMITIVES = 4108,
  // VPC: SP LM components
  HPC_GPU_ADRENO_A5XX_VPC_SP_LM_COMPONENTS = 4109,
  // VPC: SP LM dwords
  HPC_GPU_ADRENO_A5XX_VPC_SP_LM_DWORDS = 4110,
  // VPC: streamout components
  HPC_GPU_ADRENO_A5XX_VPC_STREAMOUT_COMPONENTS = 4111,
  // VPC: grant phases
  HPC_GPU_ADRENO_A5XX_VPC_GRANT_PHASES = 4112,
  // VSC: busy cycles
  HPC_GPU_ADRENO_A5XX_VSC_BUSY_CYCLES = 4352,
  // VSC: working cycles
  HPC_GPU_ADRENO_A5XX_VSC_WORKING_CYCLES = 4353,
  // VSC: stall cycles UCHE
  HPC_GPU_ADRENO_A5XX_VSC_STALL_CYCLES_UCHE = 4354,
  // VSC: eot num
  HPC_GPU_ADRENO_A5XX_VSC_EOT_NUM = 4355,
} hpc_gpu_adreno_a5xx_perfcounter_t;

#endif  // HPC_GPU_ADRENO_A5XX_H_
