// AUTOGENERATED; DO NOT EDIT!

#ifndef HPC_GPU_ADRENO_A6XX_H_
#define HPC_GPU_ADRENO_A6XX_H_

typedef enum hpc_gpu_adreno_a6xx_perfcounter_e {
  // Cache and Compression Unit: busy cycles
  HPC_GPU_ADRENO_A6XX_CCU_BUSY_CYCLES = 0,
  // Cache and Compression Unit: stall cycles RB depth return
  HPC_GPU_ADRENO_A6XX_CCU_STALL_CYCLES_RB_DEPTH_RETURN = 1,
  // Cache and Compression Unit: stall cycles RB color return
  HPC_GPU_ADRENO_A6XX_CCU_STALL_CYCLES_RB_COLOR_RETURN = 2,
  // Cache and Compression Unit: starve cycles flag return
  HPC_GPU_ADRENO_A6XX_CCU_STARVE_CYCLES_FLAG_RETURN = 3,
  // Cache and Compression Unit: depth blocks
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_BLOCKS = 4,
  // Cache and Compression Unit: color blocks
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_BLOCKS = 5,
  // Cache and Compression Unit: depth block hit
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_BLOCK_HIT = 6,
  // Cache and Compression Unit: color block hit
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_BLOCK_HIT = 7,
  // Cache and Compression Unit: partial block read
  HPC_GPU_ADRENO_A6XX_CCU_PARTIAL_BLOCK_READ = 8,
  // Cache and Compression Unit: gmem read
  HPC_GPU_ADRENO_A6XX_CCU_GMEM_READ = 9,
  // Cache and Compression Unit: gmem write
  HPC_GPU_ADRENO_A6XX_CCU_GMEM_WRITE = 10,
  // Cache and Compression Unit: depth read flag0 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG0_COUNT = 11,
  // Cache and Compression Unit: depth read flag1 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG1_COUNT = 12,
  // Cache and Compression Unit: depth read flag2 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG2_COUNT = 13,
  // Cache and Compression Unit: depth read flag3 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG3_COUNT = 14,
  // Cache and Compression Unit: depth read flag4 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG4_COUNT = 15,
  // Cache and Compression Unit: depth read flag5 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG5_COUNT = 16,
  // Cache and Compression Unit: depth read flag6 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG6_COUNT = 17,
  // Cache and Compression Unit: depth read flag8 count
  HPC_GPU_ADRENO_A6XX_CCU_DEPTH_READ_FLAG8_COUNT = 18,
  // Cache and Compression Unit: color read flag0 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG0_COUNT = 19,
  // Cache and Compression Unit: color read flag1 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG1_COUNT = 20,
  // Cache and Compression Unit: color read flag2 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG2_COUNT = 21,
  // Cache and Compression Unit: color read flag3 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG3_COUNT = 22,
  // Cache and Compression Unit: color read flag4 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG4_COUNT = 23,
  // Cache and Compression Unit: color read flag5 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG5_COUNT = 24,
  // Cache and Compression Unit: color read flag6 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG6_COUNT = 25,
  // Cache and Compression Unit: color read flag8 count
  HPC_GPU_ADRENO_A6XX_CCU_COLOR_READ_FLAG8_COUNT = 26,
  // Cache and Compression Unit: 2D RD req
  HPC_GPU_ADRENO_A6XX_CCU_2D_RD_REQ = 27,
  // Cache and Compression Unit: 2D WR req
  HPC_GPU_ADRENO_A6XX_CCU_2D_WR_REQ = 28,
  // CMP: cmpdecmp stall cycles arb
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_STALL_CYCLES_ARB = 256,
  // CMP: cmpdecmp vbif latency cycles
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_LATENCY_CYCLES = 257,
  // CMP: cmpdecmp vbif latency samples
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_LATENCY_SAMPLES = 258,
  // CMP: cmpdecmp vbif read data CCU
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_READ_DATA_CCU = 259,
  // CMP: cmpdecmp vbif write data CCU
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_WRITE_DATA_CCU = 260,
  // CMP: cmpdecmp vbif read request
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_READ_REQUEST = 261,
  // CMP: cmpdecmp vbif write request
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_WRITE_REQUEST = 262,
  // CMP: cmpdecmp vbif read data
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_READ_DATA = 263,
  // CMP: cmpdecmp vbif write data
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_WRITE_DATA = 264,
  // CMP: cmpdecmp flag fetch cycles
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_FLAG_FETCH_CYCLES = 265,
  // CMP: cmpdecmp flag fetch samples
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_FLAG_FETCH_SAMPLES = 266,
  // CMP: cmpdecmp depth write flag1 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG1_COUNT = 267,
  // CMP: cmpdecmp depth write flag2 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG2_COUNT = 268,
  // CMP: cmpdecmp depth write flag3 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG3_COUNT = 269,
  // CMP: cmpdecmp depth write flag4 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG4_COUNT = 270,
  // CMP: cmpdecmp depth write flag5 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG5_COUNT = 271,
  // CMP: cmpdecmp depth write flag6 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG6_COUNT = 272,
  // CMP: cmpdecmp depth write flag8 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG8_COUNT = 273,
  // CMP: cmpdecmp color write flag1 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG1_COUNT = 274,
  // CMP: cmpdecmp color write flag2 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG2_COUNT = 275,
  // CMP: cmpdecmp color write flag3 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG3_COUNT = 276,
  // CMP: cmpdecmp color write flag4 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG4_COUNT = 277,
  // CMP: cmpdecmp color write flag5 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG5_COUNT = 278,
  // CMP: cmpdecmp color write flag6 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG6_COUNT = 279,
  // CMP: cmpdecmp color write flag8 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG8_COUNT = 280,
  // CMP: cmpdecmp 2D stall cycles vbif req
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_REQ = 281,
  // CMP: cmpdecmp 2D stall cycles vbif WR
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_WR = 282,
  // CMP: cmpdecmp 2D stall cycles vbif return
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_STALL_CYCLES_VBIF_RETURN = 283,
  // CMP: cmpdecmp 2D RD data
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_RD_DATA = 284,
  // CMP: cmpdecmp 2D WR data
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_WR_DATA = 285,
  // CMP: cmpdecmp vbif read data UCHE ch0
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_READ_DATA_UCHE_CH0 = 286,
  // CMP: cmpdecmp vbif read data UCHE ch1
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_READ_DATA_UCHE_CH1 = 287,
  // CMP: cmpdecmp 2D output trans
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_OUTPUT_TRANS = 288,
  // CMP: cmpdecmp vbif write data UCHE
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_VBIF_WRITE_DATA_UCHE = 289,
  // CMP: cmpdecmp depth write flag0 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_DEPTH_WRITE_FLAG0_COUNT = 290,
  // CMP: cmpdecmp color write flag0 count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAG0_COUNT = 291,
  // CMP: cmpdecmp color write flagalpha count
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_COLOR_WRITE_FLAGALPHA_COUNT = 292,
  // CMP: cmpdecmp 2D busy cycles
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_BUSY_CYCLES = 293,
  // CMP: cmpdecmp 2D reorder starve cycles
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_REORDER_STARVE_CYCLES = 294,
  // CMP: cmpdecmp 2D pixels
  HPC_GPU_ADRENO_A6XX_CMP_CMPDECMP_2D_PIXELS = 295,
  // Command Parser: always count
  HPC_GPU_ADRENO_A6XX_CP_ALWAYS_COUNT = 512,
  // Command Parser: busy gfx core idle
  HPC_GPU_ADRENO_A6XX_CP_BUSY_GFX_CORE_IDLE = 513,
  // Command Parser: busy cycles
  HPC_GPU_ADRENO_A6XX_CP_BUSY_CYCLES = 514,
  // Command Parser: num preemptions
  HPC_GPU_ADRENO_A6XX_CP_NUM_PREEMPTIONS = 515,
  // Command Parser: preemption reaction delay
  HPC_GPU_ADRENO_A6XX_CP_PREEMPTION_REACTION_DELAY = 516,
  // Command Parser: preemption switch out time
  HPC_GPU_ADRENO_A6XX_CP_PREEMPTION_SWITCH_OUT_TIME = 517,
  // Command Parser: preemption switch IN time
  HPC_GPU_ADRENO_A6XX_CP_PREEMPTION_SWITCH_IN_TIME = 518,
  // Command Parser: dead draws IN bin render
  HPC_GPU_ADRENO_A6XX_CP_DEAD_DRAWS_IN_BIN_RENDER = 519,
  // Command Parser: predicated draws killed
  HPC_GPU_ADRENO_A6XX_CP_PREDICATED_DRAWS_KILLED = 520,
  // Command Parser: mode switch
  HPC_GPU_ADRENO_A6XX_CP_MODE_SWITCH = 521,
  // Command Parser: zpass done
  HPC_GPU_ADRENO_A6XX_CP_ZPASS_DONE = 522,
  // Command Parser: context done
  HPC_GPU_ADRENO_A6XX_CP_CONTEXT_DONE = 523,
  // Command Parser: cache flush
  HPC_GPU_ADRENO_A6XX_CP_CACHE_FLUSH = 524,
  // Command Parser: long preemptions
  HPC_GPU_ADRENO_A6XX_CP_LONG_PREEMPTIONS = 525,
  // Command Parser: sqe I cache starve
  HPC_GPU_ADRENO_A6XX_CP_SQE_I_CACHE_STARVE = 526,
  // Command Parser: sqe idle
  HPC_GPU_ADRENO_A6XX_CP_SQE_IDLE = 527,
  // Command Parser: sqe pm4 starve RB IB
  HPC_GPU_ADRENO_A6XX_CP_SQE_PM4_STARVE_RB_IB = 528,
  // Command Parser: sqe pm4 starve sds
  HPC_GPU_ADRENO_A6XX_CP_SQE_PM4_STARVE_SDS = 529,
  // Command Parser: sqe mrb starve
  HPC_GPU_ADRENO_A6XX_CP_SQE_MRB_STARVE = 530,
  // Command Parser: sqe rrb starve
  HPC_GPU_ADRENO_A6XX_CP_SQE_RRB_STARVE = 531,
  // Command Parser: sqe vsd starve
  HPC_GPU_ADRENO_A6XX_CP_SQE_VSD_STARVE = 532,
  // Command Parser: vsd decode starve
  HPC_GPU_ADRENO_A6XX_CP_VSD_DECODE_STARVE = 533,
  // Command Parser: sqe pipe out stall
  HPC_GPU_ADRENO_A6XX_CP_SQE_PIPE_OUT_STALL = 534,
  // Command Parser: sqe sync stall
  HPC_GPU_ADRENO_A6XX_CP_SQE_SYNC_STALL = 535,
  // Command Parser: sqe pm4 wfi stall
  HPC_GPU_ADRENO_A6XX_CP_SQE_PM4_WFI_STALL = 536,
  // Command Parser: sqe sys wfi stall
  HPC_GPU_ADRENO_A6XX_CP_SQE_SYS_WFI_STALL = 537,
  // Command Parser: sqe T4 exec
  HPC_GPU_ADRENO_A6XX_CP_SQE_T4_EXEC = 538,
  // Command Parser: sqe load state exec
  HPC_GPU_ADRENO_A6XX_CP_SQE_LOAD_STATE_EXEC = 539,
  // Command Parser: sqe save sds state
  HPC_GPU_ADRENO_A6XX_CP_SQE_SAVE_SDS_STATE = 540,
  // Command Parser: sqe draw exec
  HPC_GPU_ADRENO_A6XX_CP_SQE_DRAW_EXEC = 541,
  // Command Parser: sqe ctxt reg bunch exec
  HPC_GPU_ADRENO_A6XX_CP_SQE_CTXT_REG_BUNCH_EXEC = 542,
  // Command Parser: sqe exec profiled
  HPC_GPU_ADRENO_A6XX_CP_SQE_EXEC_PROFILED = 543,
  // Command Parser: memory pool empty
  HPC_GPU_ADRENO_A6XX_CP_MEMORY_POOL_EMPTY = 544,
  // Command Parser: memory pool sync stall
  HPC_GPU_ADRENO_A6XX_CP_MEMORY_POOL_SYNC_STALL = 545,
  // Command Parser: memory pool above thresh
  HPC_GPU_ADRENO_A6XX_CP_MEMORY_POOL_ABOVE_THRESH = 546,
  // Command Parser: ahb WR stall pre draws
  HPC_GPU_ADRENO_A6XX_CP_AHB_WR_STALL_PRE_DRAWS = 547,
  // Command Parser: ahb stall sqe gmu
  HPC_GPU_ADRENO_A6XX_CP_AHB_STALL_SQE_GMU = 548,
  // Command Parser: ahb stall sqe WR other
  HPC_GPU_ADRENO_A6XX_CP_AHB_STALL_SQE_WR_OTHER = 549,
  // Command Parser: ahb stall sqe RD other
  HPC_GPU_ADRENO_A6XX_CP_AHB_STALL_SQE_RD_OTHER = 550,
  // Command Parser: cluster0 empty
  HPC_GPU_ADRENO_A6XX_CP_CLUSTER0_EMPTY = 551,
  // Command Parser: cluster1 empty
  HPC_GPU_ADRENO_A6XX_CP_CLUSTER1_EMPTY = 552,
  // Command Parser: cluster2 empty
  HPC_GPU_ADRENO_A6XX_CP_CLUSTER2_EMPTY = 553,
  // Command Parser: cluster3 empty
  HPC_GPU_ADRENO_A6XX_CP_CLUSTER3_EMPTY = 554,
  // Command Parser: cluster4 empty
  HPC_GPU_ADRENO_A6XX_CP_CLUSTER4_EMPTY = 555,
  // Command Parser: cluster5 empty
  HPC_GPU_ADRENO_A6XX_CP_CLUSTER5_EMPTY = 556,
  // Command Parser: pm4 data
  HPC_GPU_ADRENO_A6XX_CP_PM4_DATA = 557,
  // Command Parser: pm4 headers
  HPC_GPU_ADRENO_A6XX_CP_PM4_HEADERS = 558,
  // Command Parser: vbif read beats
  HPC_GPU_ADRENO_A6XX_CP_VBIF_READ_BEATS = 559,
  // Command Parser: vbif write beats
  HPC_GPU_ADRENO_A6XX_CP_VBIF_WRITE_BEATS = 560,
  // Command Parser: sqe instr counter
  HPC_GPU_ADRENO_A6XX_CP_SQE_INSTR_COUNTER = 561,
  // High Level SeQuencer: busy cycles
  HPC_GPU_ADRENO_A6XX_HLSQ_BUSY_CYCLES = 768,
  // High Level SeQuencer: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_HLSQ_STALL_CYCLES_UCHE = 769,
  // High Level SeQuencer: stall cycles SP state
  HPC_GPU_ADRENO_A6XX_HLSQ_STALL_CYCLES_SP_STATE = 770,
  // High Level SeQuencer: stall cycles SP FS stage
  HPC_GPU_ADRENO_A6XX_HLSQ_STALL_CYCLES_SP_FS_STAGE = 771,
  // High Level SeQuencer: UCHE latency cycles
  HPC_GPU_ADRENO_A6XX_HLSQ_UCHE_LATENCY_CYCLES = 772,
  // High Level SeQuencer: UCHE latency count
  HPC_GPU_ADRENO_A6XX_HLSQ_UCHE_LATENCY_COUNT = 773,
  // High Level SeQuencer: FS stage 1X waves
  HPC_GPU_ADRENO_A6XX_HLSQ_FS_STAGE_1X_WAVES = 774,
  // High Level SeQuencer: FS stage 2X waves
  HPC_GPU_ADRENO_A6XX_HLSQ_FS_STAGE_2X_WAVES = 775,
  // High Level SeQuencer: quads
  HPC_GPU_ADRENO_A6XX_HLSQ_QUADS = 776,
  // High Level SeQuencer: CS invocations
  HPC_GPU_ADRENO_A6XX_HLSQ_CS_INVOCATIONS = 777,
  // High Level SeQuencer: compute drawcalls
  HPC_GPU_ADRENO_A6XX_HLSQ_COMPUTE_DRAWCALLS = 778,
  // High Level SeQuencer: FS data wait programming
  HPC_GPU_ADRENO_A6XX_HLSQ_FS_DATA_WAIT_PROGRAMMING = 779,
  // High Level SeQuencer: dual FS prog active
  HPC_GPU_ADRENO_A6XX_HLSQ_DUAL_FS_PROG_ACTIVE = 780,
  // High Level SeQuencer: dual VS prog active
  HPC_GPU_ADRENO_A6XX_HLSQ_DUAL_VS_PROG_ACTIVE = 781,
  // High Level SeQuencer: FS batch count zero
  HPC_GPU_ADRENO_A6XX_HLSQ_FS_BATCH_COUNT_ZERO = 782,
  // High Level SeQuencer: VS batch count zero
  HPC_GPU_ADRENO_A6XX_HLSQ_VS_BATCH_COUNT_ZERO = 783,
  // High Level SeQuencer: wave pending NO quad
  HPC_GPU_ADRENO_A6XX_HLSQ_WAVE_PENDING_NO_QUAD = 784,
  // High Level SeQuencer: wave pending NO prim base
  HPC_GPU_ADRENO_A6XX_HLSQ_WAVE_PENDING_NO_PRIM_BASE = 785,
  // High Level SeQuencer: stall cycles VPC
  HPC_GPU_ADRENO_A6XX_HLSQ_STALL_CYCLES_VPC = 786,
  // High Level SeQuencer: pixels
  HPC_GPU_ADRENO_A6XX_HLSQ_PIXELS = 787,
  // High Level SeQuencer: draw mode switch vsfs sync
  HPC_GPU_ADRENO_A6XX_HLSQ_DRAW_MODE_SWITCH_VSFS_SYNC = 788,
  // Low Resolution Z: busy cycles
  HPC_GPU_ADRENO_A6XX_LRZ_BUSY_CYCLES = 1024,
  // Low Resolution Z: starve cycles RAS
  HPC_GPU_ADRENO_A6XX_LRZ_STARVE_CYCLES_RAS = 1025,
  // Low Resolution Z: stall cycles RB
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_RB = 1026,
  // Low Resolution Z: stall cycles VSC
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_VSC = 1027,
  // Low Resolution Z: stall cycles VPC
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_VPC = 1028,
  // Low Resolution Z: stall cycles flag prefetch
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_FLAG_PREFETCH = 1029,
  // Low Resolution Z: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_UCHE = 1030,
  // Low Resolution Z: LRZ read
  HPC_GPU_ADRENO_A6XX_LRZ_LRZ_READ = 1031,
  // Low Resolution Z: LRZ write
  HPC_GPU_ADRENO_A6XX_LRZ_LRZ_WRITE = 1032,
  // Low Resolution Z: read latency
  HPC_GPU_ADRENO_A6XX_LRZ_READ_LATENCY = 1033,
  // Low Resolution Z: merge cache updating
  HPC_GPU_ADRENO_A6XX_LRZ_MERGE_CACHE_UPDATING = 1034,
  // Low Resolution Z: prim killed BY maskgen
  HPC_GPU_ADRENO_A6XX_LRZ_PRIM_KILLED_BY_MASKGEN = 1035,
  // Low Resolution Z: prim killed BY LRZ
  HPC_GPU_ADRENO_A6XX_LRZ_PRIM_KILLED_BY_LRZ = 1036,
  // Low Resolution Z: visible prim after LRZ
  HPC_GPU_ADRENO_A6XX_LRZ_VISIBLE_PRIM_AFTER_LRZ = 1037,
  // Low Resolution Z: full 8x8 tiles
  HPC_GPU_ADRENO_A6XX_LRZ_FULL_8X8_TILES = 1038,
  // Low Resolution Z: partial 8x8 tiles
  HPC_GPU_ADRENO_A6XX_LRZ_PARTIAL_8X8_TILES = 1039,
  // Low Resolution Z: tile killed
  HPC_GPU_ADRENO_A6XX_LRZ_TILE_KILLED = 1040,
  // Low Resolution Z: total pixel
  HPC_GPU_ADRENO_A6XX_LRZ_TOTAL_PIXEL = 1041,
  // Low Resolution Z: visible pixel after LRZ
  HPC_GPU_ADRENO_A6XX_LRZ_VISIBLE_PIXEL_AFTER_LRZ = 1042,
  // Low Resolution Z: fully covered tiles
  HPC_GPU_ADRENO_A6XX_LRZ_FULLY_COVERED_TILES = 1043,
  // Low Resolution Z: partial covered tiles
  HPC_GPU_ADRENO_A6XX_LRZ_PARTIAL_COVERED_TILES = 1044,
  // Low Resolution Z: feedback accept
  HPC_GPU_ADRENO_A6XX_LRZ_FEEDBACK_ACCEPT = 1045,
  // Low Resolution Z: feedback discard
  HPC_GPU_ADRENO_A6XX_LRZ_FEEDBACK_DISCARD = 1046,
  // Low Resolution Z: feedback stall
  HPC_GPU_ADRENO_A6XX_LRZ_FEEDBACK_STALL = 1047,
  // Low Resolution Z: stall cycles RB zplane
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_RB_ZPLANE = 1048,
  // Low Resolution Z: stall cycles RB bplane
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_RB_BPLANE = 1049,
  // Low Resolution Z: stall cycles VC
  HPC_GPU_ADRENO_A6XX_LRZ_STALL_CYCLES_VC = 1050,
  // Low Resolution Z: RAS mask trans
  HPC_GPU_ADRENO_A6XX_LRZ_RAS_MASK_TRANS = 1051,
  // PC: busy cycles
  HPC_GPU_ADRENO_A6XX_PC_BUSY_CYCLES = 1280,
  // PC: working cycles
  HPC_GPU_ADRENO_A6XX_PC_WORKING_CYCLES = 1281,
  // PC: stall cycles VFD
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_VFD = 1282,
  // PC: stall cycles TSE
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_TSE = 1283,
  // PC: stall cycles VPC
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_VPC = 1284,
  // PC: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_UCHE = 1285,
  // PC: stall cycles tess
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_TESS = 1286,
  // PC: stall cycles TSE only
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_TSE_ONLY = 1287,
  // PC: stall cycles VPC only
  HPC_GPU_ADRENO_A6XX_PC_STALL_CYCLES_VPC_ONLY = 1288,
  // PC: pass1 TF stall cycles
  HPC_GPU_ADRENO_A6XX_PC_PASS1_TF_STALL_CYCLES = 1289,
  // PC: starve cycles for index
  HPC_GPU_ADRENO_A6XX_PC_STARVE_CYCLES_FOR_INDEX = 1290,
  // PC: starve cycles for tess factor
  HPC_GPU_ADRENO_A6XX_PC_STARVE_CYCLES_FOR_TESS_FACTOR = 1291,
  // PC: starve cycles for viz stream
  HPC_GPU_ADRENO_A6XX_PC_STARVE_CYCLES_FOR_VIZ_STREAM = 1292,
  // PC: starve cycles for position
  HPC_GPU_ADRENO_A6XX_PC_STARVE_CYCLES_FOR_POSITION = 1293,
  // PC: starve cycles DI
  HPC_GPU_ADRENO_A6XX_PC_STARVE_CYCLES_DI = 1294,
  // PC: vis streams loaded
  HPC_GPU_ADRENO_A6XX_PC_VIS_STREAMS_LOADED = 1295,
  // PC: instances
  HPC_GPU_ADRENO_A6XX_PC_INSTANCES = 1296,
  // PC: VPC primitives
  HPC_GPU_ADRENO_A6XX_PC_VPC_PRIMITIVES = 1297,
  // PC: dead prim
  HPC_GPU_ADRENO_A6XX_PC_DEAD_PRIM = 1298,
  // PC: live prim
  HPC_GPU_ADRENO_A6XX_PC_LIVE_PRIM = 1299,
  // PC: vertex hits
  HPC_GPU_ADRENO_A6XX_PC_VERTEX_HITS = 1300,
  // PC: IA vertices
  HPC_GPU_ADRENO_A6XX_PC_IA_VERTICES = 1301,
  // PC: IA primitives
  HPC_GPU_ADRENO_A6XX_PC_IA_PRIMITIVES = 1302,
  // PC: GS primitives
  HPC_GPU_ADRENO_A6XX_PC_GS_PRIMITIVES = 1303,
  // PC: HS invocations
  HPC_GPU_ADRENO_A6XX_PC_HS_INVOCATIONS = 1304,
  // PC: DS invocations
  HPC_GPU_ADRENO_A6XX_PC_DS_INVOCATIONS = 1305,
  // PC: VS invocations
  HPC_GPU_ADRENO_A6XX_PC_VS_INVOCATIONS = 1306,
  // PC: GS invocations
  HPC_GPU_ADRENO_A6XX_PC_GS_INVOCATIONS = 1307,
  // PC: DS primitives
  HPC_GPU_ADRENO_A6XX_PC_DS_PRIMITIVES = 1308,
  // PC: VPC pos data transaction
  HPC_GPU_ADRENO_A6XX_PC_VPC_POS_DATA_TRANSACTION = 1309,
  // PC: 3D drawcalls
  HPC_GPU_ADRENO_A6XX_PC_3D_DRAWCALLS = 1310,
  // PC: 2D drawcalls
  HPC_GPU_ADRENO_A6XX_PC_2D_DRAWCALLS = 1311,
  // PC: non drawcall global events
  HPC_GPU_ADRENO_A6XX_PC_NON_DRAWCALL_GLOBAL_EVENTS = 1312,
  // PC: tess busy cycles
  HPC_GPU_ADRENO_A6XX_PC_TESS_BUSY_CYCLES = 1313,
  // PC: tess working cycles
  HPC_GPU_ADRENO_A6XX_PC_TESS_WORKING_CYCLES = 1314,
  // PC: tess stall cycles PC
  HPC_GPU_ADRENO_A6XX_PC_TESS_STALL_CYCLES_PC = 1315,
  // PC: tess starve cycles PC
  HPC_GPU_ADRENO_A6XX_PC_TESS_STARVE_CYCLES_PC = 1316,
  // PC: TSE transaction
  HPC_GPU_ADRENO_A6XX_PC_TSE_TRANSACTION = 1317,
  // PC: TSE vertex
  HPC_GPU_ADRENO_A6XX_PC_TSE_VERTEX = 1318,
  // PC: tess PC UV trans
  HPC_GPU_ADRENO_A6XX_PC_TESS_PC_UV_TRANS = 1319,
  // PC: tess PC UV patches
  HPC_GPU_ADRENO_A6XX_PC_TESS_PC_UV_PATCHES = 1320,
  // PC: tess factor trans
  HPC_GPU_ADRENO_A6XX_PC_TESS_FACTOR_TRANS = 1321,
  // RAS: busy cycles
  HPC_GPU_ADRENO_A6XX_RAS_BUSY_CYCLES = 1536,
  // RAS: supertile active cycles
  HPC_GPU_ADRENO_A6XX_RAS_SUPERTILE_ACTIVE_CYCLES = 1537,
  // RAS: stall cycles LRZ
  HPC_GPU_ADRENO_A6XX_RAS_STALL_CYCLES_LRZ = 1538,
  // RAS: starve cycles TSE
  HPC_GPU_ADRENO_A6XX_RAS_STARVE_CYCLES_TSE = 1539,
  // RAS: super tiles
  HPC_GPU_ADRENO_A6XX_RAS_SUPER_TILES = 1540,
  // RAS: 8x4 tiles
  HPC_GPU_ADRENO_A6XX_RAS_8X4_TILES = 1541,
  // RAS: maskgen active
  HPC_GPU_ADRENO_A6XX_RAS_MASKGEN_ACTIVE = 1542,
  // RAS: fully covered super tiles
  HPC_GPU_ADRENO_A6XX_RAS_FULLY_COVERED_SUPER_TILES = 1543,
  // RAS: fully covered 8x4 tiles
  HPC_GPU_ADRENO_A6XX_RAS_FULLY_COVERED_8X4_TILES = 1544,
  // RAS: prim killed invisilbe
  HPC_GPU_ADRENO_A6XX_RAS_PRIM_KILLED_INVISILBE = 1545,
  // RAS: supertile gen active cycles
  HPC_GPU_ADRENO_A6XX_RAS_SUPERTILE_GEN_ACTIVE_CYCLES = 1546,
  // RAS: LRZ intf working cycles
  HPC_GPU_ADRENO_A6XX_RAS_LRZ_INTF_WORKING_CYCLES = 1547,
  // RAS: blocks
  HPC_GPU_ADRENO_A6XX_RAS_BLOCKS = 1548,
  // RB: busy cycles
  HPC_GPU_ADRENO_A6XX_RB_BUSY_CYCLES = 1792,
  // RB: stall cycles HLSQ
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_HLSQ = 1793,
  // RB: stall cycles fifo0 full
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_FIFO0_FULL = 1794,
  // RB: stall cycles fifo1 full
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_FIFO1_FULL = 1795,
  // RB: stall cycles fifo2 full
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_FIFO2_FULL = 1796,
  // RB: starve cycles SP
  HPC_GPU_ADRENO_A6XX_RB_STARVE_CYCLES_SP = 1797,
  // RB: starve cycles LRZ tile
  HPC_GPU_ADRENO_A6XX_RB_STARVE_CYCLES_LRZ_TILE = 1798,
  // RB: starve cycles CCU
  HPC_GPU_ADRENO_A6XX_RB_STARVE_CYCLES_CCU = 1799,
  // RB: starve cycles Z plane
  HPC_GPU_ADRENO_A6XX_RB_STARVE_CYCLES_Z_PLANE = 1800,
  // RB: starve cycles bary plane
  HPC_GPU_ADRENO_A6XX_RB_STARVE_CYCLES_BARY_PLANE = 1801,
  // RB: Z workload
  HPC_GPU_ADRENO_A6XX_RB_Z_WORKLOAD = 1802,
  // RB: HLSQ active
  HPC_GPU_ADRENO_A6XX_RB_HLSQ_ACTIVE = 1803,
  // RB: Z read
  HPC_GPU_ADRENO_A6XX_RB_Z_READ = 1804,
  // RB: Z write
  HPC_GPU_ADRENO_A6XX_RB_Z_WRITE = 1805,
  // RB: C read
  HPC_GPU_ADRENO_A6XX_RB_C_READ = 1806,
  // RB: C write
  HPC_GPU_ADRENO_A6XX_RB_C_WRITE = 1807,
  // RB: total pass
  HPC_GPU_ADRENO_A6XX_RB_TOTAL_PASS = 1808,
  // RB: Z pass
  HPC_GPU_ADRENO_A6XX_RB_Z_PASS = 1809,
  // RB: Z fail
  HPC_GPU_ADRENO_A6XX_RB_Z_FAIL = 1810,
  // RB: S fail
  HPC_GPU_ADRENO_A6XX_RB_S_FAIL = 1811,
  // RB: blended fxp components
  HPC_GPU_ADRENO_A6XX_RB_BLENDED_FXP_COMPONENTS = 1812,
  // RB: blended fp16 components
  HPC_GPU_ADRENO_A6XX_RB_BLENDED_FP16_COMPONENTS = 1813,
  // RB: PS invocations
  HPC_GPU_ADRENO_A6XX_RB_PS_INVOCATIONS = 1814,
  // RB: 2D alive cycles
  HPC_GPU_ADRENO_A6XX_RB_2D_ALIVE_CYCLES = 1815,
  // RB: 2D stall cycles a2d
  HPC_GPU_ADRENO_A6XX_RB_2D_STALL_CYCLES_A2D = 1816,
  // RB: 2D starve cycles src
  HPC_GPU_ADRENO_A6XX_RB_2D_STARVE_CYCLES_SRC = 1817,
  // RB: 2D starve cycles SP
  HPC_GPU_ADRENO_A6XX_RB_2D_STARVE_CYCLES_SP = 1818,
  // RB: 2D starve cycles dst
  HPC_GPU_ADRENO_A6XX_RB_2D_STARVE_CYCLES_DST = 1819,
  // RB: 2D valid pixels
  HPC_GPU_ADRENO_A6XX_RB_2D_VALID_PIXELS = 1820,
  // RB: 3D pixels
  HPC_GPU_ADRENO_A6XX_RB_3D_PIXELS = 1821,
  // RB: blender working cycles
  HPC_GPU_ADRENO_A6XX_RB_BLENDER_WORKING_CYCLES = 1822,
  // RB: zproc working cycles
  HPC_GPU_ADRENO_A6XX_RB_ZPROC_WORKING_CYCLES = 1823,
  // RB: cproc working cycles
  HPC_GPU_ADRENO_A6XX_RB_CPROC_WORKING_CYCLES = 1824,
  // RB: sampler working cycles
  HPC_GPU_ADRENO_A6XX_RB_SAMPLER_WORKING_CYCLES = 1825,
  // RB: stall cycles CCU color read
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_CCU_COLOR_READ = 1826,
  // RB: stall cycles CCU color write
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_CCU_COLOR_WRITE = 1827,
  // RB: stall cycles CCU depth read
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_CCU_DEPTH_READ = 1828,
  // RB: stall cycles CCU depth write
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_CCU_DEPTH_WRITE = 1829,
  // RB: stall cycles VPC
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_VPC = 1830,
  // RB: 2D input trans
  HPC_GPU_ADRENO_A6XX_RB_2D_INPUT_TRANS = 1831,
  // RB: 2D output RB dst trans
  HPC_GPU_ADRENO_A6XX_RB_2D_OUTPUT_RB_DST_TRANS = 1832,
  // RB: 2D output RB src trans
  HPC_GPU_ADRENO_A6XX_RB_2D_OUTPUT_RB_SRC_TRANS = 1833,
  // RB: blended fp32 components
  HPC_GPU_ADRENO_A6XX_RB_BLENDED_FP32_COMPONENTS = 1834,
  // RB: color pix tiles
  HPC_GPU_ADRENO_A6XX_RB_COLOR_PIX_TILES = 1835,
  // RB: stall cycles CCU
  HPC_GPU_ADRENO_A6XX_RB_STALL_CYCLES_CCU = 1836,
  // RB: early Z arb3 grant
  HPC_GPU_ADRENO_A6XX_RB_EARLY_Z_ARB3_GRANT = 1837,
  // RB: late Z arb3 grant
  HPC_GPU_ADRENO_A6XX_RB_LATE_Z_ARB3_GRANT = 1838,
  // RB: early Z skip grant
  HPC_GPU_ADRENO_A6XX_RB_EARLY_Z_SKIP_GRANT = 1839,
  // RBBM: always count
  HPC_GPU_ADRENO_A6XX_RBBM_ALWAYS_COUNT = 2048,
  // RBBM: always ON
  HPC_GPU_ADRENO_A6XX_RBBM_ALWAYS_ON = 2049,
  // RBBM: TSE busy
  HPC_GPU_ADRENO_A6XX_RBBM_TSE_BUSY = 2050,
  // RBBM: RAS busy
  HPC_GPU_ADRENO_A6XX_RBBM_RAS_BUSY = 2051,
  // RBBM: PC dcall busy
  HPC_GPU_ADRENO_A6XX_RBBM_PC_DCALL_BUSY = 2052,
  // RBBM: PC vsd busy
  HPC_GPU_ADRENO_A6XX_RBBM_PC_VSD_BUSY = 2053,
  // RBBM: status masked
  HPC_GPU_ADRENO_A6XX_RBBM_STATUS_MASKED = 2054,
  // RBBM: com busy
  HPC_GPU_ADRENO_A6XX_RBBM_COM_BUSY = 2055,
  // RBBM: dcom busy
  HPC_GPU_ADRENO_A6XX_RBBM_DCOM_BUSY = 2056,
  // RBBM: vbif busy
  HPC_GPU_ADRENO_A6XX_RBBM_VBIF_BUSY = 2057,
  // RBBM: VSC busy
  HPC_GPU_ADRENO_A6XX_RBBM_VSC_BUSY = 2058,
  // RBBM: tess busy
  HPC_GPU_ADRENO_A6XX_RBBM_TESS_BUSY = 2059,
  // RBBM: UCHE busy
  HPC_GPU_ADRENO_A6XX_RBBM_UCHE_BUSY = 2060,
  // RBBM: HLSQ busy
  HPC_GPU_ADRENO_A6XX_RBBM_HLSQ_BUSY = 2061,
  // Shader/Streaming Processor: busy cycles
  HPC_GPU_ADRENO_A6XX_SP_BUSY_CYCLES = 2304,
  // Shader/Streaming Processor: ALU working cycles
  HPC_GPU_ADRENO_A6XX_SP_ALU_WORKING_CYCLES = 2305,
  // Shader/Streaming Processor: EFU working cycles
  HPC_GPU_ADRENO_A6XX_SP_EFU_WORKING_CYCLES = 2306,
  // Shader/Streaming Processor: stall cycles VPC
  HPC_GPU_ADRENO_A6XX_SP_STALL_CYCLES_VPC = 2307,
  // Shader/Streaming Processor: stall cycles TP
  HPC_GPU_ADRENO_A6XX_SP_STALL_CYCLES_TP = 2308,
  // Shader/Streaming Processor: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_SP_STALL_CYCLES_UCHE = 2309,
  // Shader/Streaming Processor: stall cycles RB
  HPC_GPU_ADRENO_A6XX_SP_STALL_CYCLES_RB = 2310,
  // Shader/Streaming Processor: non execution cycles
  HPC_GPU_ADRENO_A6XX_SP_NON_EXECUTION_CYCLES = 2311,
  // Shader/Streaming Processor: wave contexts
  HPC_GPU_ADRENO_A6XX_SP_WAVE_CONTEXTS = 2312,
  // Shader/Streaming Processor: wave context cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_CONTEXT_CYCLES = 2313,
  // Shader/Streaming Processor: FS stage wave cycles
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_WAVE_CYCLES = 2314,
  // Shader/Streaming Processor: FS stage wave samples
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_WAVE_SAMPLES = 2315,
  // Shader/Streaming Processor: VS stage wave cycles
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_WAVE_CYCLES = 2316,
  // Shader/Streaming Processor: VS stage wave samples
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_WAVE_SAMPLES = 2317,
  // Shader/Streaming Processor: FS stage duration cycles
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_DURATION_CYCLES = 2318,
  // Shader/Streaming Processor: VS stage duration cycles
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_DURATION_CYCLES = 2319,
  // Shader/Streaming Processor: wave ctrl cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_CTRL_CYCLES = 2320,
  // Shader/Streaming Processor: wave load cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_LOAD_CYCLES = 2321,
  // Shader/Streaming Processor: wave emit cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_EMIT_CYCLES = 2322,
  // Shader/Streaming Processor: wave nop cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_NOP_CYCLES = 2323,
  // Shader/Streaming Processor: wave wait cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_WAIT_CYCLES = 2324,
  // Shader/Streaming Processor: wave fetch cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_FETCH_CYCLES = 2325,
  // Shader/Streaming Processor: wave idle cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_IDLE_CYCLES = 2326,
  // Shader/Streaming Processor: wave end cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_END_CYCLES = 2327,
  // Shader/Streaming Processor: wave long sync cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_LONG_SYNC_CYCLES = 2328,
  // Shader/Streaming Processor: wave short sync cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_SHORT_SYNC_CYCLES = 2329,
  // Shader/Streaming Processor: wave join cycles
  HPC_GPU_ADRENO_A6XX_SP_WAVE_JOIN_CYCLES = 2330,
  // Shader/Streaming Processor: LM load instructions
  HPC_GPU_ADRENO_A6XX_SP_LM_LOAD_INSTRUCTIONS = 2331,
  // Shader/Streaming Processor: LM store instructions
  HPC_GPU_ADRENO_A6XX_SP_LM_STORE_INSTRUCTIONS = 2332,
  // Shader/Streaming Processor: LM atomics
  HPC_GPU_ADRENO_A6XX_SP_LM_ATOMICS = 2333,
  // Shader/Streaming Processor: GM load instructions
  HPC_GPU_ADRENO_A6XX_SP_GM_LOAD_INSTRUCTIONS = 2334,
  // Shader/Streaming Processor: GM store instructions
  HPC_GPU_ADRENO_A6XX_SP_GM_STORE_INSTRUCTIONS = 2335,
  // Shader/Streaming Processor: GM atomics
  HPC_GPU_ADRENO_A6XX_SP_GM_ATOMICS = 2336,
  // Shader/Streaming Processor: VS stage tex instructions
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_TEX_INSTRUCTIONS = 2337,
  // Shader/Streaming Processor: VS stage EFU instructions
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_EFU_INSTRUCTIONS = 2338,
  // Shader/Streaming Processor: VS stage full ALU instructions
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_FULL_ALU_INSTRUCTIONS = 2339,
  // Shader/Streaming Processor: VS stage half ALU instructions
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_HALF_ALU_INSTRUCTIONS = 2340,
  // Shader/Streaming Processor: FS stage tex instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_TEX_INSTRUCTIONS = 2341,
  // Shader/Streaming Processor: FS stage cflow instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_CFLOW_INSTRUCTIONS = 2342,
  // Shader/Streaming Processor: FS stage EFU instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_EFU_INSTRUCTIONS = 2343,
  // Shader/Streaming Processor: FS stage full ALU instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_FULL_ALU_INSTRUCTIONS = 2344,
  // Shader/Streaming Processor: FS stage half ALU instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_HALF_ALU_INSTRUCTIONS = 2345,
  // Shader/Streaming Processor: FS stage bary instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_BARY_INSTRUCTIONS = 2346,
  // Shader/Streaming Processor: VS instructions
  HPC_GPU_ADRENO_A6XX_SP_VS_INSTRUCTIONS = 2347,
  // Shader/Streaming Processor: FS instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_INSTRUCTIONS = 2348,
  // Shader/Streaming Processor: addr lock count
  HPC_GPU_ADRENO_A6XX_SP_ADDR_LOCK_COUNT = 2349,
  // Shader/Streaming Processor: UCHE read trans
  HPC_GPU_ADRENO_A6XX_SP_UCHE_READ_TRANS = 2350,
  // Shader/Streaming Processor: UCHE write trans
  HPC_GPU_ADRENO_A6XX_SP_UCHE_WRITE_TRANS = 2351,
  // Shader/Streaming Processor: export VPC trans
  HPC_GPU_ADRENO_A6XX_SP_EXPORT_VPC_TRANS = 2352,
  // Shader/Streaming Processor: export RB trans
  HPC_GPU_ADRENO_A6XX_SP_EXPORT_RB_TRANS = 2353,
  // Shader/Streaming Processor: pixels killed
  HPC_GPU_ADRENO_A6XX_SP_PIXELS_KILLED = 2354,
  // Shader/Streaming Processor: icl1 requests
  HPC_GPU_ADRENO_A6XX_SP_ICL1_REQUESTS = 2355,
  // Shader/Streaming Processor: icl1 misses
  HPC_GPU_ADRENO_A6XX_SP_ICL1_MISSES = 2356,
  // Shader/Streaming Processor: HS instructions
  HPC_GPU_ADRENO_A6XX_SP_HS_INSTRUCTIONS = 2357,
  // Shader/Streaming Processor: DS instructions
  HPC_GPU_ADRENO_A6XX_SP_DS_INSTRUCTIONS = 2358,
  // Shader/Streaming Processor: GS instructions
  HPC_GPU_ADRENO_A6XX_SP_GS_INSTRUCTIONS = 2359,
  // Shader/Streaming Processor: CS instructions
  HPC_GPU_ADRENO_A6XX_SP_CS_INSTRUCTIONS = 2360,
  // Shader/Streaming Processor: GPR read
  HPC_GPU_ADRENO_A6XX_SP_GPR_READ = 2361,
  // Shader/Streaming Processor: GPR write
  HPC_GPU_ADRENO_A6XX_SP_GPR_WRITE = 2362,
  // Shader/Streaming Processor: FS stage half EFU instructions
  HPC_GPU_ADRENO_A6XX_SP_FS_STAGE_HALF_EFU_INSTRUCTIONS = 2363,
  // Shader/Streaming Processor: VS stage half EFU instructions
  HPC_GPU_ADRENO_A6XX_SP_VS_STAGE_HALF_EFU_INSTRUCTIONS = 2364,
  // Shader/Streaming Processor: LM bank conflicts
  HPC_GPU_ADRENO_A6XX_SP_LM_BANK_CONFLICTS = 2365,
  // Shader/Streaming Processor: tex control working cycles
  HPC_GPU_ADRENO_A6XX_SP_TEX_CONTROL_WORKING_CYCLES = 2366,
  // Shader/Streaming Processor: load control working cycles
  HPC_GPU_ADRENO_A6XX_SP_LOAD_CONTROL_WORKING_CYCLES = 2367,
  // Shader/Streaming Processor: flow control working cycles
  HPC_GPU_ADRENO_A6XX_SP_FLOW_CONTROL_WORKING_CYCLES = 2368,
  // Shader/Streaming Processor: LM working cycles
  HPC_GPU_ADRENO_A6XX_SP_LM_WORKING_CYCLES = 2369,
  // Shader/Streaming Processor: dispatcher working cycles
  HPC_GPU_ADRENO_A6XX_SP_DISPATCHER_WORKING_CYCLES = 2370,
  // Shader/Streaming Processor: sequencer working cycles
  HPC_GPU_ADRENO_A6XX_SP_SEQUENCER_WORKING_CYCLES = 2371,
  // Shader/Streaming Processor: low efficiency starved BY TP
  HPC_GPU_ADRENO_A6XX_SP_LOW_EFFICIENCY_STARVED_BY_TP = 2372,
  // Shader/Streaming Processor: starve cycles HLSQ
  HPC_GPU_ADRENO_A6XX_SP_STARVE_CYCLES_HLSQ = 2373,
  // Shader/Streaming Processor: non execution LS cycles
  HPC_GPU_ADRENO_A6XX_SP_NON_EXECUTION_LS_CYCLES = 2374,
  // Shader/Streaming Processor: working EU
  HPC_GPU_ADRENO_A6XX_SP_WORKING_EU = 2375,
  // Shader/Streaming Processor: any EU working
  HPC_GPU_ADRENO_A6XX_SP_ANY_EU_WORKING = 2376,
  // Shader/Streaming Processor: working EU FS stage
  HPC_GPU_ADRENO_A6XX_SP_WORKING_EU_FS_STAGE = 2377,
  // Shader/Streaming Processor: any EU working FS stage
  HPC_GPU_ADRENO_A6XX_SP_ANY_EU_WORKING_FS_STAGE = 2378,
  // Shader/Streaming Processor: working EU VS stage
  HPC_GPU_ADRENO_A6XX_SP_WORKING_EU_VS_STAGE = 2379,
  // Shader/Streaming Processor: any EU working VS stage
  HPC_GPU_ADRENO_A6XX_SP_ANY_EU_WORKING_VS_STAGE = 2380,
  // Shader/Streaming Processor: working EU CS stage
  HPC_GPU_ADRENO_A6XX_SP_WORKING_EU_CS_STAGE = 2381,
  // Shader/Streaming Processor: any EU working CS stage
  HPC_GPU_ADRENO_A6XX_SP_ANY_EU_WORKING_CS_STAGE = 2382,
  // Shader/Streaming Processor: GPR read prefetch
  HPC_GPU_ADRENO_A6XX_SP_GPR_READ_PREFETCH = 2383,
  // Shader/Streaming Processor: GPR read conflict
  HPC_GPU_ADRENO_A6XX_SP_GPR_READ_CONFLICT = 2384,
  // Shader/Streaming Processor: GPR write conflict
  HPC_GPU_ADRENO_A6XX_SP_GPR_WRITE_CONFLICT = 2385,
  // Shader/Streaming Processor: GM load latency cycles
  HPC_GPU_ADRENO_A6XX_SP_GM_LOAD_LATENCY_CYCLES = 2386,
  // Shader/Streaming Processor: GM load latency samples
  HPC_GPU_ADRENO_A6XX_SP_GM_LOAD_LATENCY_SAMPLES = 2387,
  // Shader/Streaming Processor: executable waves
  HPC_GPU_ADRENO_A6XX_SP_EXECUTABLE_WAVES = 2388,
  // Texture Processor: busy cycles
  HPC_GPU_ADRENO_A6XX_TP_BUSY_CYCLES = 2560,
  // Texture Processor: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_TP_STALL_CYCLES_UCHE = 2561,
  // Texture Processor: latency cycles
  HPC_GPU_ADRENO_A6XX_TP_LATENCY_CYCLES = 2562,
  // Texture Processor: latency trans
  HPC_GPU_ADRENO_A6XX_TP_LATENCY_TRANS = 2563,
  // Texture Processor: flag cache request samples
  HPC_GPU_ADRENO_A6XX_TP_FLAG_CACHE_REQUEST_SAMPLES = 2564,
  // Texture Processor: flag cache request latency
  HPC_GPU_ADRENO_A6XX_TP_FLAG_CACHE_REQUEST_LATENCY = 2565,
  // Texture Processor: L1 cacheline requests
  HPC_GPU_ADRENO_A6XX_TP_L1_CACHELINE_REQUESTS = 2566,
  // Texture Processor: L1 cacheline misses
  HPC_GPU_ADRENO_A6XX_TP_L1_CACHELINE_MISSES = 2567,
  // Texture Processor: SP TP trans
  HPC_GPU_ADRENO_A6XX_TP_SP_TP_TRANS = 2568,
  // Texture Processor: TP SP trans
  HPC_GPU_ADRENO_A6XX_TP_TP_SP_TRANS = 2569,
  // Texture Processor: output pixels
  HPC_GPU_ADRENO_A6XX_TP_OUTPUT_PIXELS = 2570,
  // Texture Processor: filter workload 16bit
  HPC_GPU_ADRENO_A6XX_TP_FILTER_WORKLOAD_16BIT = 2571,
  // Texture Processor: filter workload 32bit
  HPC_GPU_ADRENO_A6XX_TP_FILTER_WORKLOAD_32BIT = 2572,
  // Texture Processor: quads received
  HPC_GPU_ADRENO_A6XX_TP_QUADS_RECEIVED = 2573,
  // Texture Processor: quads offset
  HPC_GPU_ADRENO_A6XX_TP_QUADS_OFFSET = 2574,
  // Texture Processor: quads shadow
  HPC_GPU_ADRENO_A6XX_TP_QUADS_SHADOW = 2575,
  // Texture Processor: quads array
  HPC_GPU_ADRENO_A6XX_TP_QUADS_ARRAY = 2576,
  // Texture Processor: quads gradient
  HPC_GPU_ADRENO_A6XX_TP_QUADS_GRADIENT = 2577,
  // Texture Processor: quads 1D
  HPC_GPU_ADRENO_A6XX_TP_QUADS_1D = 2578,
  // Texture Processor: quads 2D
  HPC_GPU_ADRENO_A6XX_TP_QUADS_2D = 2579,
  // Texture Processor: quads buffer
  HPC_GPU_ADRENO_A6XX_TP_QUADS_BUFFER = 2580,
  // Texture Processor: quads 3D
  HPC_GPU_ADRENO_A6XX_TP_QUADS_3D = 2581,
  // Texture Processor: quads cube
  HPC_GPU_ADRENO_A6XX_TP_QUADS_CUBE = 2582,
  // Texture Processor: divergent quads received
  HPC_GPU_ADRENO_A6XX_TP_DIVERGENT_QUADS_RECEIVED = 2583,
  // Texture Processor: prt non resident events
  HPC_GPU_ADRENO_A6XX_TP_PRT_NON_RESIDENT_EVENTS = 2584,
  // Texture Processor: output pixels point
  HPC_GPU_ADRENO_A6XX_TP_OUTPUT_PIXELS_POINT = 2585,
  // Texture Processor: output pixels bilinear
  HPC_GPU_ADRENO_A6XX_TP_OUTPUT_PIXELS_BILINEAR = 2586,
  // Texture Processor: output pixels mip
  HPC_GPU_ADRENO_A6XX_TP_OUTPUT_PIXELS_MIP = 2587,
  // Texture Processor: output pixels aniso
  HPC_GPU_ADRENO_A6XX_TP_OUTPUT_PIXELS_ANISO = 2588,
  // Texture Processor: output pixels zero lod
  HPC_GPU_ADRENO_A6XX_TP_OUTPUT_PIXELS_ZERO_LOD = 2589,
  // Texture Processor: flag cache requests
  HPC_GPU_ADRENO_A6XX_TP_FLAG_CACHE_REQUESTS = 2590,
  // Texture Processor: flag cache misses
  HPC_GPU_ADRENO_A6XX_TP_FLAG_CACHE_MISSES = 2591,
  // Texture Processor: L1 5 L2 requests
  HPC_GPU_ADRENO_A6XX_TP_L1_5_L2_REQUESTS = 2592,
  // Texture Processor: 2D output pixels
  HPC_GPU_ADRENO_A6XX_TP_2D_OUTPUT_PIXELS = 2593,
  // Texture Processor: 2D output pixels point
  HPC_GPU_ADRENO_A6XX_TP_2D_OUTPUT_PIXELS_POINT = 2594,
  // Texture Processor: 2D output pixels bilinear
  HPC_GPU_ADRENO_A6XX_TP_2D_OUTPUT_PIXELS_BILINEAR = 2595,
  // Texture Processor: 2D filter workload 16bit
  HPC_GPU_ADRENO_A6XX_TP_2D_FILTER_WORKLOAD_16BIT = 2596,
  // Texture Processor: 2D filter workload 32bit
  HPC_GPU_ADRENO_A6XX_TP_2D_FILTER_WORKLOAD_32BIT = 2597,
  // Texture Processor: tpa2tpc trans
  HPC_GPU_ADRENO_A6XX_TP_TPA2TPC_TRANS = 2598,
  // Texture Processor: L1 misses astc 1tile
  HPC_GPU_ADRENO_A6XX_TP_L1_MISSES_ASTC_1TILE = 2599,
  // Texture Processor: L1 misses astc 2tile
  HPC_GPU_ADRENO_A6XX_TP_L1_MISSES_ASTC_2TILE = 2600,
  // Texture Processor: L1 misses astc 4tile
  HPC_GPU_ADRENO_A6XX_TP_L1_MISSES_ASTC_4TILE = 2601,
  // Texture Processor: L1 5 L2 compress reqs
  HPC_GPU_ADRENO_A6XX_TP_L1_5_L2_COMPRESS_REQS = 2602,
  // Texture Processor: L1 5 L2 compress miss
  HPC_GPU_ADRENO_A6XX_TP_L1_5_L2_COMPRESS_MISS = 2603,
  // Texture Processor: L1 bank conflict
  HPC_GPU_ADRENO_A6XX_TP_L1_BANK_CONFLICT = 2604,
  // Texture Processor: L1 5 miss latency cycles
  HPC_GPU_ADRENO_A6XX_TP_L1_5_MISS_LATENCY_CYCLES = 2605,
  // Texture Processor: L1 5 miss latency trans
  HPC_GPU_ADRENO_A6XX_TP_L1_5_MISS_LATENCY_TRANS = 2606,
  // Texture Processor: quads constant multiplied
  HPC_GPU_ADRENO_A6XX_TP_QUADS_CONSTANT_MULTIPLIED = 2607,
  // Texture Processor: frontend working cycles
  HPC_GPU_ADRENO_A6XX_TP_FRONTEND_WORKING_CYCLES = 2608,
  // Texture Processor: L1 tag working cycles
  HPC_GPU_ADRENO_A6XX_TP_L1_TAG_WORKING_CYCLES = 2609,
  // Texture Processor: L1 data write working cycles
  HPC_GPU_ADRENO_A6XX_TP_L1_DATA_WRITE_WORKING_CYCLES = 2610,
  // Texture Processor: pre L1 decom working cycles
  HPC_GPU_ADRENO_A6XX_TP_PRE_L1_DECOM_WORKING_CYCLES = 2611,
  // Texture Processor: backend working cycles
  HPC_GPU_ADRENO_A6XX_TP_BACKEND_WORKING_CYCLES = 2612,
  // Texture Processor: flag cache working cycles
  HPC_GPU_ADRENO_A6XX_TP_FLAG_CACHE_WORKING_CYCLES = 2613,
  // Texture Processor: L1 5 cache working cycles
  HPC_GPU_ADRENO_A6XX_TP_L1_5_CACHE_WORKING_CYCLES = 2614,
  // Texture Processor: starve cycles SP
  HPC_GPU_ADRENO_A6XX_TP_STARVE_CYCLES_SP = 2615,
  // Texture Processor: starve cycles UCHE
  HPC_GPU_ADRENO_A6XX_TP_STARVE_CYCLES_UCHE = 2616,
  // Triangle Setup Engine: busy cycles
  HPC_GPU_ADRENO_A6XX_TSE_BUSY_CYCLES = 2816,
  // Triangle Setup Engine: clipping cycles
  HPC_GPU_ADRENO_A6XX_TSE_CLIPPING_CYCLES = 2817,
  // Triangle Setup Engine: stall cycles RAS
  HPC_GPU_ADRENO_A6XX_TSE_STALL_CYCLES_RAS = 2818,
  // Triangle Setup Engine: stall cycles LRZ baryplane
  HPC_GPU_ADRENO_A6XX_TSE_STALL_CYCLES_LRZ_BARYPLANE = 2819,
  // Triangle Setup Engine: stall cycles LRZ zplane
  HPC_GPU_ADRENO_A6XX_TSE_STALL_CYCLES_LRZ_ZPLANE = 2820,
  // Triangle Setup Engine: starve cycles PC
  HPC_GPU_ADRENO_A6XX_TSE_STARVE_CYCLES_PC = 2821,
  // Triangle Setup Engine: input prim
  HPC_GPU_ADRENO_A6XX_TSE_INPUT_PRIM = 2822,
  // Triangle Setup Engine: input null prim
  HPC_GPU_ADRENO_A6XX_TSE_INPUT_NULL_PRIM = 2823,
  // Triangle Setup Engine: trival rej prim
  HPC_GPU_ADRENO_A6XX_TSE_TRIVAL_REJ_PRIM = 2824,
  // Triangle Setup Engine: clipped prim
  HPC_GPU_ADRENO_A6XX_TSE_CLIPPED_PRIM = 2825,
  // Triangle Setup Engine: zero area prim
  HPC_GPU_ADRENO_A6XX_TSE_ZERO_AREA_PRIM = 2826,
  // Triangle Setup Engine: faceness culled prim
  HPC_GPU_ADRENO_A6XX_TSE_FACENESS_CULLED_PRIM = 2827,
  // Triangle Setup Engine: zero pixel prim
  HPC_GPU_ADRENO_A6XX_TSE_ZERO_PIXEL_PRIM = 2828,
  // Triangle Setup Engine: output null prim
  HPC_GPU_ADRENO_A6XX_TSE_OUTPUT_NULL_PRIM = 2829,
  // Triangle Setup Engine: output visible prim
  HPC_GPU_ADRENO_A6XX_TSE_OUTPUT_VISIBLE_PRIM = 2830,
  // Triangle Setup Engine: cinvocation
  HPC_GPU_ADRENO_A6XX_TSE_CINVOCATION = 2831,
  // Triangle Setup Engine: cprimitives
  HPC_GPU_ADRENO_A6XX_TSE_CPRIMITIVES = 2832,
  // Triangle Setup Engine: 2D input prim
  HPC_GPU_ADRENO_A6XX_TSE_2D_INPUT_PRIM = 2833,
  // Triangle Setup Engine: 2D alive cycles
  HPC_GPU_ADRENO_A6XX_TSE_2D_ALIVE_CYCLES = 2834,
  // Triangle Setup Engine: clip planes
  HPC_GPU_ADRENO_A6XX_TSE_CLIP_PLANES = 2835,
  // Unified L2 Cache: busy cycles
  HPC_GPU_ADRENO_A6XX_UCHE_BUSY_CYCLES = 3072,
  // Unified L2 Cache: stall cycles arbiter
  HPC_GPU_ADRENO_A6XX_UCHE_STALL_CYCLES_ARBITER = 3073,
  // Unified L2 Cache: vbif latency cycles
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_LATENCY_CYCLES = 3074,
  // Unified L2 Cache: vbif latency samples
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_LATENCY_SAMPLES = 3075,
  // Unified L2 Cache: vbif read beats TP
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_TP = 3076,
  // Unified L2 Cache: vbif read beats VFD
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_VFD = 3077,
  // Unified L2 Cache: vbif read beats HLSQ
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_HLSQ = 3078,
  // Unified L2 Cache: vbif read beats LRZ
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_LRZ = 3079,
  // Unified L2 Cache: vbif read beats SP
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_SP = 3080,
  // Unified L2 Cache: read requests TP
  HPC_GPU_ADRENO_A6XX_UCHE_READ_REQUESTS_TP = 3081,
  // Unified L2 Cache: read requests VFD
  HPC_GPU_ADRENO_A6XX_UCHE_READ_REQUESTS_VFD = 3082,
  // Unified L2 Cache: read requests HLSQ
  HPC_GPU_ADRENO_A6XX_UCHE_READ_REQUESTS_HLSQ = 3083,
  // Unified L2 Cache: read requests LRZ
  HPC_GPU_ADRENO_A6XX_UCHE_READ_REQUESTS_LRZ = 3084,
  // Unified L2 Cache: read requests SP
  HPC_GPU_ADRENO_A6XX_UCHE_READ_REQUESTS_SP = 3085,
  // Unified L2 Cache: write requests LRZ
  HPC_GPU_ADRENO_A6XX_UCHE_WRITE_REQUESTS_LRZ = 3086,
  // Unified L2 Cache: write requests SP
  HPC_GPU_ADRENO_A6XX_UCHE_WRITE_REQUESTS_SP = 3087,
  // Unified L2 Cache: write requests VPC
  HPC_GPU_ADRENO_A6XX_UCHE_WRITE_REQUESTS_VPC = 3088,
  // Unified L2 Cache: write requests VSC
  HPC_GPU_ADRENO_A6XX_UCHE_WRITE_REQUESTS_VSC = 3089,
  // Unified L2 Cache: evicts
  HPC_GPU_ADRENO_A6XX_UCHE_EVICTS = 3090,
  // Unified L2 Cache: bank req0
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ0 = 3091,
  // Unified L2 Cache: bank req1
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ1 = 3092,
  // Unified L2 Cache: bank req2
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ2 = 3093,
  // Unified L2 Cache: bank req3
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ3 = 3094,
  // Unified L2 Cache: bank req4
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ4 = 3095,
  // Unified L2 Cache: bank req5
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ5 = 3096,
  // Unified L2 Cache: bank req6
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ6 = 3097,
  // Unified L2 Cache: bank req7
  HPC_GPU_ADRENO_A6XX_UCHE_BANK_REQ7 = 3098,
  // Unified L2 Cache: vbif read beats ch0
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_CH0 = 3099,
  // Unified L2 Cache: vbif read beats ch1
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_CH1 = 3100,
  // Unified L2 Cache: gmem read beats
  HPC_GPU_ADRENO_A6XX_UCHE_GMEM_READ_BEATS = 3101,
  // Unified L2 Cache: tph ref full
  HPC_GPU_ADRENO_A6XX_UCHE_TPH_REF_FULL = 3102,
  // Unified L2 Cache: tph victim full
  HPC_GPU_ADRENO_A6XX_UCHE_TPH_VICTIM_FULL = 3103,
  // Unified L2 Cache: tph ext full
  HPC_GPU_ADRENO_A6XX_UCHE_TPH_EXT_FULL = 3104,
  // Unified L2 Cache: vbif stall write data
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_STALL_WRITE_DATA = 3105,
  // Unified L2 Cache: dcmp latency samples
  HPC_GPU_ADRENO_A6XX_UCHE_DCMP_LATENCY_SAMPLES = 3106,
  // Unified L2 Cache: dcmp latency cycles
  HPC_GPU_ADRENO_A6XX_UCHE_DCMP_LATENCY_CYCLES = 3107,
  // Unified L2 Cache: vbif read beats PC
  HPC_GPU_ADRENO_A6XX_UCHE_VBIF_READ_BEATS_PC = 3108,
  // Unified L2 Cache: read requests PC
  HPC_GPU_ADRENO_A6XX_UCHE_READ_REQUESTS_PC = 3109,
  // Unified L2 Cache: ram read req
  HPC_GPU_ADRENO_A6XX_UCHE_RAM_READ_REQ = 3110,
  // Unified L2 Cache: ram write req
  HPC_GPU_ADRENO_A6XX_UCHE_RAM_WRITE_REQ = 3111,
  // VFD: busy cycles
  HPC_GPU_ADRENO_A6XX_VFD_BUSY_CYCLES = 3328,
  // VFD: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_VFD_STALL_CYCLES_UCHE = 3329,
  // VFD: stall cycles VPC alloc
  HPC_GPU_ADRENO_A6XX_VFD_STALL_CYCLES_VPC_ALLOC = 3330,
  // VFD: stall cycles SP info
  HPC_GPU_ADRENO_A6XX_VFD_STALL_CYCLES_SP_INFO = 3331,
  // VFD: stall cycles SP attr
  HPC_GPU_ADRENO_A6XX_VFD_STALL_CYCLES_SP_ATTR = 3332,
  // VFD: starve cycles UCHE
  HPC_GPU_ADRENO_A6XX_VFD_STARVE_CYCLES_UCHE = 3333,
  // VFD: rbuffer full
  HPC_GPU_ADRENO_A6XX_VFD_RBUFFER_FULL = 3334,
  // VFD: attr info fifo full
  HPC_GPU_ADRENO_A6XX_VFD_ATTR_INFO_FIFO_FULL = 3335,
  // VFD: decoded attribute bytes
  HPC_GPU_ADRENO_A6XX_VFD_DECODED_ATTRIBUTE_BYTES = 3336,
  // VFD: num attributes
  HPC_GPU_ADRENO_A6XX_VFD_NUM_ATTRIBUTES = 3337,
  // VFD: upper shader fibers
  HPC_GPU_ADRENO_A6XX_VFD_UPPER_SHADER_FIBERS = 3338,
  // VFD: lower shader fibers
  HPC_GPU_ADRENO_A6XX_VFD_LOWER_SHADER_FIBERS = 3339,
  // VFD: mode 0 fibers
  HPC_GPU_ADRENO_A6XX_VFD_MODE_0_FIBERS = 3340,
  // VFD: mode 1 fibers
  HPC_GPU_ADRENO_A6XX_VFD_MODE_1_FIBERS = 3341,
  // VFD: mode 2 fibers
  HPC_GPU_ADRENO_A6XX_VFD_MODE_2_FIBERS = 3342,
  // VFD: mode 3 fibers
  HPC_GPU_ADRENO_A6XX_VFD_MODE_3_FIBERS = 3343,
  // VFD: mode 4 fibers
  HPC_GPU_ADRENO_A6XX_VFD_MODE_4_FIBERS = 3344,
  // VFD: total vertices
  HPC_GPU_ADRENO_A6XX_VFD_TOTAL_VERTICES = 3345,
  // VFD: vfdp stall cycles VFD
  HPC_GPU_ADRENO_A6XX_VFD_VFDP_STALL_CYCLES_VFD = 3346,
  // VFD: vfdp stall cycles VFD index
  HPC_GPU_ADRENO_A6XX_VFD_VFDP_STALL_CYCLES_VFD_INDEX = 3347,
  // VFD: vfdp stall cycles VFD prog
  HPC_GPU_ADRENO_A6XX_VFD_VFDP_STALL_CYCLES_VFD_PROG = 3348,
  // VFD: vfdp starve cycles PC
  HPC_GPU_ADRENO_A6XX_VFD_VFDP_STARVE_CYCLES_PC = 3349,
  // VFD: vfdp VS stage waves
  HPC_GPU_ADRENO_A6XX_VFD_VFDP_VS_STAGE_WAVES = 3350,
  // VPC: busy cycles
  HPC_GPU_ADRENO_A6XX_VPC_BUSY_CYCLES = 3584,
  // VPC: working cycles
  HPC_GPU_ADRENO_A6XX_VPC_WORKING_CYCLES = 3585,
  // VPC: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_VPC_STALL_CYCLES_UCHE = 3586,
  // VPC: stall cycles VFD wack
  HPC_GPU_ADRENO_A6XX_VPC_STALL_CYCLES_VFD_WACK = 3587,
  // VPC: stall cycles HLSQ prim alloc
  HPC_GPU_ADRENO_A6XX_VPC_STALL_CYCLES_HLSQ_PRIM_ALLOC = 3588,
  // VPC: stall cycles PC
  HPC_GPU_ADRENO_A6XX_VPC_STALL_CYCLES_PC = 3589,
  // VPC: stall cycles SP LM
  HPC_GPU_ADRENO_A6XX_VPC_STALL_CYCLES_SP_LM = 3590,
  // VPC: starve cycles SP
  HPC_GPU_ADRENO_A6XX_VPC_STARVE_CYCLES_SP = 3591,
  // VPC: starve cycles LRZ
  HPC_GPU_ADRENO_A6XX_VPC_STARVE_CYCLES_LRZ = 3592,
  // VPC: PC primitives
  HPC_GPU_ADRENO_A6XX_VPC_PC_PRIMITIVES = 3593,
  // VPC: SP components
  HPC_GPU_ADRENO_A6XX_VPC_SP_COMPONENTS = 3594,
  // VPC: stall cycles vpcram pos
  HPC_GPU_ADRENO_A6XX_VPC_STALL_CYCLES_VPCRAM_POS = 3595,
  // VPC: LRZ assign primitives
  HPC_GPU_ADRENO_A6XX_VPC_LRZ_ASSIGN_PRIMITIVES = 3596,
  // VPC: RB visible primitives
  HPC_GPU_ADRENO_A6XX_VPC_RB_VISIBLE_PRIMITIVES = 3597,
  // VPC: LM transaction
  HPC_GPU_ADRENO_A6XX_VPC_LM_TRANSACTION = 3598,
  // VPC: streamout transaction
  HPC_GPU_ADRENO_A6XX_VPC_STREAMOUT_TRANSACTION = 3599,
  // VPC: VS busy cycles
  HPC_GPU_ADRENO_A6XX_VPC_VS_BUSY_CYCLES = 3600,
  // VPC: PS busy cycles
  HPC_GPU_ADRENO_A6XX_VPC_PS_BUSY_CYCLES = 3601,
  // VPC: VS working cycles
  HPC_GPU_ADRENO_A6XX_VPC_VS_WORKING_CYCLES = 3602,
  // VPC: PS working cycles
  HPC_GPU_ADRENO_A6XX_VPC_PS_WORKING_CYCLES = 3603,
  // VPC: starve cycles RB
  HPC_GPU_ADRENO_A6XX_VPC_STARVE_CYCLES_RB = 3604,
  // VPC: num vpcram read pos
  HPC_GPU_ADRENO_A6XX_VPC_NUM_VPCRAM_READ_POS = 3605,
  // VPC: wit full cycles
  HPC_GPU_ADRENO_A6XX_VPC_WIT_FULL_CYCLES = 3606,
  // VPC: vpcram full cycles
  HPC_GPU_ADRENO_A6XX_VPC_VPCRAM_FULL_CYCLES = 3607,
  // VPC: LM full wait for intp end
  HPC_GPU_ADRENO_A6XX_VPC_LM_FULL_WAIT_FOR_INTP_END = 3608,
  // VPC: num vpcram write
  HPC_GPU_ADRENO_A6XX_VPC_NUM_VPCRAM_WRITE = 3609,
  // VPC: num vpcram read SO
  HPC_GPU_ADRENO_A6XX_VPC_NUM_VPCRAM_READ_SO = 3610,
  // VPC: num attr req LM
  HPC_GPU_ADRENO_A6XX_VPC_NUM_ATTR_REQ_LM = 3611,
  // VSC: busy cycles
  HPC_GPU_ADRENO_A6XX_VSC_BUSY_CYCLES = 3840,
  // VSC: working cycles
  HPC_GPU_ADRENO_A6XX_VSC_WORKING_CYCLES = 3841,
  // VSC: stall cycles UCHE
  HPC_GPU_ADRENO_A6XX_VSC_STALL_CYCLES_UCHE = 3842,
  // VSC: eot num
  HPC_GPU_ADRENO_A6XX_VSC_EOT_NUM = 3843,
  // VSC: input tiles
  HPC_GPU_ADRENO_A6XX_VSC_INPUT_TILES = 3844,
} hpc_gpu_adreno_a6xx_perfcounter_t;

#endif  // HPC_GPU_ADRENO_A6XX_H_
